/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.mdm.liferay.model.impl;

import com.adjecti.mdm.liferay.model.OrganizationHistory;
import com.adjecti.mdm.liferay.model.OrganizationHistoryModel;
import com.adjecti.mdm.liferay.model.OrganizationHistorySoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OrganizationHistory service. Represents a row in the &quot;mdm_OrganizationHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OrganizationHistoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OrganizationHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OrganizationHistoryImpl
 * @generated
 */
@JSON(strict = true)
public class OrganizationHistoryModelImpl
	extends BaseModelImpl<OrganizationHistory>
	implements OrganizationHistoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a organization history model instance should use the <code>OrganizationHistory</code> interface instead.
	 */
	public static final String TABLE_NAME = "mdm_OrganizationHistory";

	public static final Object[][] TABLE_COLUMNS = {
		{"organizationHistoryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"organizationId", Types.BIGINT},
		{"previousOrganizationName", Types.VARCHAR},
		{"previousOrganizationId", Types.BIGINT},
		{"previousParentOrganizationName", Types.VARCHAR},
		{"previousParentOrganizationId", Types.BIGINT},
		{"organizationName", Types.VARCHAR}, {"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("organizationHistoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("previousOrganizationName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("previousOrganizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("previousParentOrganizationName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("previousParentOrganizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizationName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table mdm_OrganizationHistory (organizationHistoryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,organizationId LONG,previousOrganizationName VARCHAR(75) null,previousOrganizationId LONG,previousParentOrganizationName VARCHAR(75) null,previousParentOrganizationId LONG,organizationName VARCHAR(75) null,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table mdm_OrganizationHistory";

	public static final String ORDER_BY_JPQL =
		" ORDER BY organizationHistory.organizationHistoryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY mdm_OrganizationHistory.organizationHistoryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ORGANIZATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PREVIOUSORGANIZATIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ORGANIZATIONHISTORYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static OrganizationHistory toModel(
		OrganizationHistorySoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		OrganizationHistory model = new OrganizationHistoryImpl();

		model.setOrganizationHistoryId(soapModel.getOrganizationHistoryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setOrganizationId(soapModel.getOrganizationId());
		model.setPreviousOrganizationName(
			soapModel.getPreviousOrganizationName());
		model.setPreviousOrganizationId(soapModel.getPreviousOrganizationId());
		model.setPreviousParentOrganizationName(
			soapModel.getPreviousParentOrganizationName());
		model.setPreviousParentOrganizationId(
			soapModel.getPreviousParentOrganizationId());
		model.setOrganizationName(soapModel.getOrganizationName());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<OrganizationHistory> toModels(
		OrganizationHistorySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<OrganizationHistory> models = new ArrayList<OrganizationHistory>(
			soapModels.length);

		for (OrganizationHistorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public OrganizationHistoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _organizationHistoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOrganizationHistoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _organizationHistoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OrganizationHistory.class;
	}

	@Override
	public String getModelClassName() {
		return OrganizationHistory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OrganizationHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OrganizationHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OrganizationHistory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((OrganizationHistory)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OrganizationHistory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OrganizationHistory, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OrganizationHistory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OrganizationHistory, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OrganizationHistory, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, OrganizationHistory>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			OrganizationHistory.class.getClassLoader(),
			OrganizationHistory.class, ModelWrapper.class);

		try {
			Constructor<OrganizationHistory> constructor =
				(Constructor<OrganizationHistory>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<OrganizationHistory, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OrganizationHistory, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OrganizationHistory, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<OrganizationHistory, Object>>();
		Map<String, BiConsumer<OrganizationHistory, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<OrganizationHistory, ?>>();

		attributeGetterFunctions.put(
			"organizationHistoryId",
			OrganizationHistory::getOrganizationHistoryId);
		attributeSetterBiConsumers.put(
			"organizationHistoryId",
			(BiConsumer<OrganizationHistory, Long>)
				OrganizationHistory::setOrganizationHistoryId);
		attributeGetterFunctions.put(
			"groupId", OrganizationHistory::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<OrganizationHistory, Long>)
				OrganizationHistory::setGroupId);
		attributeGetterFunctions.put(
			"companyId", OrganizationHistory::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<OrganizationHistory, Long>)
				OrganizationHistory::setCompanyId);
		attributeGetterFunctions.put("userId", OrganizationHistory::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<OrganizationHistory, Long>)
				OrganizationHistory::setUserId);
		attributeGetterFunctions.put(
			"userName", OrganizationHistory::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<OrganizationHistory, String>)
				OrganizationHistory::setUserName);
		attributeGetterFunctions.put(
			"createDate", OrganizationHistory::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<OrganizationHistory, Date>)
				OrganizationHistory::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", OrganizationHistory::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<OrganizationHistory, Date>)
				OrganizationHistory::setModifiedDate);
		attributeGetterFunctions.put(
			"organizationId", OrganizationHistory::getOrganizationId);
		attributeSetterBiConsumers.put(
			"organizationId",
			(BiConsumer<OrganizationHistory, Long>)
				OrganizationHistory::setOrganizationId);
		attributeGetterFunctions.put(
			"previousOrganizationName",
			OrganizationHistory::getPreviousOrganizationName);
		attributeSetterBiConsumers.put(
			"previousOrganizationName",
			(BiConsumer<OrganizationHistory, String>)
				OrganizationHistory::setPreviousOrganizationName);
		attributeGetterFunctions.put(
			"previousOrganizationId",
			OrganizationHistory::getPreviousOrganizationId);
		attributeSetterBiConsumers.put(
			"previousOrganizationId",
			(BiConsumer<OrganizationHistory, Long>)
				OrganizationHistory::setPreviousOrganizationId);
		attributeGetterFunctions.put(
			"previousParentOrganizationName",
			OrganizationHistory::getPreviousParentOrganizationName);
		attributeSetterBiConsumers.put(
			"previousParentOrganizationName",
			(BiConsumer<OrganizationHistory, String>)
				OrganizationHistory::setPreviousParentOrganizationName);
		attributeGetterFunctions.put(
			"previousParentOrganizationId",
			OrganizationHistory::getPreviousParentOrganizationId);
		attributeSetterBiConsumers.put(
			"previousParentOrganizationId",
			(BiConsumer<OrganizationHistory, Long>)
				OrganizationHistory::setPreviousParentOrganizationId);
		attributeGetterFunctions.put(
			"organizationName", OrganizationHistory::getOrganizationName);
		attributeSetterBiConsumers.put(
			"organizationName",
			(BiConsumer<OrganizationHistory, String>)
				OrganizationHistory::setOrganizationName);
		attributeGetterFunctions.put("status", OrganizationHistory::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<OrganizationHistory, String>)
				OrganizationHistory::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getOrganizationHistoryId() {
		return _organizationHistoryId;
	}

	@Override
	public void setOrganizationHistoryId(long organizationHistoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organizationHistoryId = organizationHistoryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organizationId = organizationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalOrganizationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("organizationId"));
	}

	@JSON
	@Override
	public String getPreviousOrganizationName() {
		if (_previousOrganizationName == null) {
			return "";
		}
		else {
			return _previousOrganizationName;
		}
	}

	@Override
	public void setPreviousOrganizationName(String previousOrganizationName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_previousOrganizationName = previousOrganizationName;
	}

	@JSON
	@Override
	public long getPreviousOrganizationId() {
		return _previousOrganizationId;
	}

	@Override
	public void setPreviousOrganizationId(long previousOrganizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_previousOrganizationId = previousOrganizationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPreviousOrganizationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("previousOrganizationId"));
	}

	@JSON
	@Override
	public String getPreviousParentOrganizationName() {
		if (_previousParentOrganizationName == null) {
			return "";
		}
		else {
			return _previousParentOrganizationName;
		}
	}

	@Override
	public void setPreviousParentOrganizationName(
		String previousParentOrganizationName) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_previousParentOrganizationName = previousParentOrganizationName;
	}

	@JSON
	@Override
	public long getPreviousParentOrganizationId() {
		return _previousParentOrganizationId;
	}

	@Override
	public void setPreviousParentOrganizationId(
		long previousParentOrganizationId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_previousParentOrganizationId = previousParentOrganizationId;
	}

	@JSON
	@Override
	public String getOrganizationName() {
		if (_organizationName == null) {
			return "";
		}
		else {
			return _organizationName;
		}
	}

	@Override
	public void setOrganizationName(String organizationName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organizationName = organizationName;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), OrganizationHistory.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OrganizationHistory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OrganizationHistory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OrganizationHistoryImpl organizationHistoryImpl =
			new OrganizationHistoryImpl();

		organizationHistoryImpl.setOrganizationHistoryId(
			getOrganizationHistoryId());
		organizationHistoryImpl.setGroupId(getGroupId());
		organizationHistoryImpl.setCompanyId(getCompanyId());
		organizationHistoryImpl.setUserId(getUserId());
		organizationHistoryImpl.setUserName(getUserName());
		organizationHistoryImpl.setCreateDate(getCreateDate());
		organizationHistoryImpl.setModifiedDate(getModifiedDate());
		organizationHistoryImpl.setOrganizationId(getOrganizationId());
		organizationHistoryImpl.setPreviousOrganizationName(
			getPreviousOrganizationName());
		organizationHistoryImpl.setPreviousOrganizationId(
			getPreviousOrganizationId());
		organizationHistoryImpl.setPreviousParentOrganizationName(
			getPreviousParentOrganizationName());
		organizationHistoryImpl.setPreviousParentOrganizationId(
			getPreviousParentOrganizationId());
		organizationHistoryImpl.setOrganizationName(getOrganizationName());
		organizationHistoryImpl.setStatus(getStatus());

		organizationHistoryImpl.resetOriginalValues();

		return organizationHistoryImpl;
	}

	@Override
	public int compareTo(OrganizationHistory organizationHistory) {
		long primaryKey = organizationHistory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OrganizationHistory)) {
			return false;
		}

		OrganizationHistory organizationHistory = (OrganizationHistory)object;

		long primaryKey = organizationHistory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OrganizationHistory> toCacheModel() {
		OrganizationHistoryCacheModel organizationHistoryCacheModel =
			new OrganizationHistoryCacheModel();

		organizationHistoryCacheModel.organizationHistoryId =
			getOrganizationHistoryId();

		organizationHistoryCacheModel.groupId = getGroupId();

		organizationHistoryCacheModel.companyId = getCompanyId();

		organizationHistoryCacheModel.userId = getUserId();

		organizationHistoryCacheModel.userName = getUserName();

		String userName = organizationHistoryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			organizationHistoryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			organizationHistoryCacheModel.createDate = createDate.getTime();
		}
		else {
			organizationHistoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			organizationHistoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			organizationHistoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		organizationHistoryCacheModel.organizationId = getOrganizationId();

		organizationHistoryCacheModel.previousOrganizationName =
			getPreviousOrganizationName();

		String previousOrganizationName =
			organizationHistoryCacheModel.previousOrganizationName;

		if ((previousOrganizationName != null) &&
			(previousOrganizationName.length() == 0)) {

			organizationHistoryCacheModel.previousOrganizationName = null;
		}

		organizationHistoryCacheModel.previousOrganizationId =
			getPreviousOrganizationId();

		organizationHistoryCacheModel.previousParentOrganizationName =
			getPreviousParentOrganizationName();

		String previousParentOrganizationName =
			organizationHistoryCacheModel.previousParentOrganizationName;

		if ((previousParentOrganizationName != null) &&
			(previousParentOrganizationName.length() == 0)) {

			organizationHistoryCacheModel.previousParentOrganizationName = null;
		}

		organizationHistoryCacheModel.previousParentOrganizationId =
			getPreviousParentOrganizationId();

		organizationHistoryCacheModel.organizationName = getOrganizationName();

		String organizationName =
			organizationHistoryCacheModel.organizationName;

		if ((organizationName != null) && (organizationName.length() == 0)) {
			organizationHistoryCacheModel.organizationName = null;
		}

		organizationHistoryCacheModel.status = getStatus();

		String status = organizationHistoryCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			organizationHistoryCacheModel.status = null;
		}

		return organizationHistoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OrganizationHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OrganizationHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OrganizationHistory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((OrganizationHistory)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<OrganizationHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<OrganizationHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OrganizationHistory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((OrganizationHistory)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OrganizationHistory>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _organizationHistoryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _organizationId;
	private String _previousOrganizationName;
	private long _previousOrganizationId;
	private String _previousParentOrganizationName;
	private long _previousParentOrganizationId;
	private String _organizationName;
	private String _status;

	public <T> T getColumnValue(String columnName) {
		Function<OrganizationHistory, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OrganizationHistory)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"organizationHistoryId", _organizationHistoryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("organizationId", _organizationId);
		_columnOriginalValues.put(
			"previousOrganizationName", _previousOrganizationName);
		_columnOriginalValues.put(
			"previousOrganizationId", _previousOrganizationId);
		_columnOriginalValues.put(
			"previousParentOrganizationName", _previousParentOrganizationName);
		_columnOriginalValues.put(
			"previousParentOrganizationId", _previousParentOrganizationId);
		_columnOriginalValues.put("organizationName", _organizationName);
		_columnOriginalValues.put("status", _status);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("organizationHistoryId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("organizationId", 128L);

		columnBitmasks.put("previousOrganizationName", 256L);

		columnBitmasks.put("previousOrganizationId", 512L);

		columnBitmasks.put("previousParentOrganizationName", 1024L);

		columnBitmasks.put("previousParentOrganizationId", 2048L);

		columnBitmasks.put("organizationName", 4096L);

		columnBitmasks.put("status", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OrganizationHistory _escapedModel;

}