/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.mdm.liferay.model.impl;

import com.adjecti.mdm.liferay.model.PayComponent;
import com.adjecti.mdm.liferay.model.PayComponentModel;
import com.adjecti.mdm.liferay.model.PayComponentSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PayComponent service. Represents a row in the &quot;mdm_PayComponent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PayComponentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PayComponentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PayComponentImpl
 * @generated
 */
@JSON(strict = true)
public class PayComponentModelImpl
	extends BaseModelImpl<PayComponent> implements PayComponentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pay component model instance should use the <code>PayComponent</code> interface instead.
	 */
	public static final String TABLE_NAME = "mdm_PayComponent";

	public static final Object[][] TABLE_COLUMNS = {
		{"payComponentId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"active_", Types.BOOLEAN},
		{"amount", Types.FLOAT}, {"amountType", Types.VARCHAR},
		{"fromDate", Types.TIMESTAMP}, {"toDate", Types.TIMESTAMP},
		{"dependantId", Types.BIGINT}, {"headId", Types.BIGINT},
		{"structureId", Types.BIGINT}, {"deleted", Types.BOOLEAN},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("payComponentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("amount", Types.FLOAT);
		TABLE_COLUMNS_MAP.put("amountType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fromDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("toDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dependantId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("headId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("structureId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("deleted", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table mdm_PayComponent (payComponentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,active_ BOOLEAN,amount DOUBLE,amountType VARCHAR(75) null,fromDate DATE null,toDate DATE null,dependantId LONG,headId LONG,structureId LONG,deleted BOOLEAN,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table mdm_PayComponent";

	public static final String ORDER_BY_JPQL =
		" ORDER BY payComponent.payComponentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY mdm_PayComponent.payComponentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PAYCOMPONENTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static PayComponent toModel(PayComponentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PayComponent model = new PayComponentImpl();

		model.setPayComponentId(soapModel.getPayComponentId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setActive(soapModel.isActive());
		model.setAmount(soapModel.getAmount());
		model.setAmountType(soapModel.getAmountType());
		model.setFromDate(soapModel.getFromDate());
		model.setToDate(soapModel.getToDate());
		model.setDependantId(soapModel.getDependantId());
		model.setHeadId(soapModel.getHeadId());
		model.setStructureId(soapModel.getStructureId());
		model.setDeleted(soapModel.isDeleted());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<PayComponent> toModels(PayComponentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PayComponent> models = new ArrayList<PayComponent>(
			soapModels.length);

		for (PayComponentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PayComponentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _payComponentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPayComponentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _payComponentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PayComponent.class;
	}

	@Override
	public String getModelClassName() {
		return PayComponent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PayComponent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PayComponent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PayComponent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PayComponent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PayComponent, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PayComponent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PayComponent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PayComponent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PayComponent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PayComponent>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PayComponent.class.getClassLoader(), PayComponent.class,
			ModelWrapper.class);

		try {
			Constructor<PayComponent> constructor =
				(Constructor<PayComponent>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PayComponent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PayComponent, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PayComponent, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PayComponent, Object>>();
		Map<String, BiConsumer<PayComponent, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PayComponent, ?>>();

		attributeGetterFunctions.put(
			"payComponentId", PayComponent::getPayComponentId);
		attributeSetterBiConsumers.put(
			"payComponentId",
			(BiConsumer<PayComponent, Long>)PayComponent::setPayComponentId);
		attributeGetterFunctions.put("groupId", PayComponent::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<PayComponent, Long>)PayComponent::setGroupId);
		attributeGetterFunctions.put("companyId", PayComponent::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<PayComponent, Long>)PayComponent::setCompanyId);
		attributeGetterFunctions.put("userId", PayComponent::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<PayComponent, Long>)PayComponent::setUserId);
		attributeGetterFunctions.put("userName", PayComponent::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<PayComponent, String>)PayComponent::setUserName);
		attributeGetterFunctions.put("createDate", PayComponent::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<PayComponent, Date>)PayComponent::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", PayComponent::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<PayComponent, Date>)PayComponent::setModifiedDate);
		attributeGetterFunctions.put("active", PayComponent::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<PayComponent, Boolean>)PayComponent::setActive);
		attributeGetterFunctions.put("amount", PayComponent::getAmount);
		attributeSetterBiConsumers.put(
			"amount", (BiConsumer<PayComponent, Float>)PayComponent::setAmount);
		attributeGetterFunctions.put("amountType", PayComponent::getAmountType);
		attributeSetterBiConsumers.put(
			"amountType",
			(BiConsumer<PayComponent, String>)PayComponent::setAmountType);
		attributeGetterFunctions.put("fromDate", PayComponent::getFromDate);
		attributeSetterBiConsumers.put(
			"fromDate",
			(BiConsumer<PayComponent, Date>)PayComponent::setFromDate);
		attributeGetterFunctions.put("toDate", PayComponent::getToDate);
		attributeSetterBiConsumers.put(
			"toDate", (BiConsumer<PayComponent, Date>)PayComponent::setToDate);
		attributeGetterFunctions.put(
			"dependantId", PayComponent::getDependantId);
		attributeSetterBiConsumers.put(
			"dependantId",
			(BiConsumer<PayComponent, Long>)PayComponent::setDependantId);
		attributeGetterFunctions.put("headId", PayComponent::getHeadId);
		attributeSetterBiConsumers.put(
			"headId", (BiConsumer<PayComponent, Long>)PayComponent::setHeadId);
		attributeGetterFunctions.put(
			"structureId", PayComponent::getStructureId);
		attributeSetterBiConsumers.put(
			"structureId",
			(BiConsumer<PayComponent, Long>)PayComponent::setStructureId);
		attributeGetterFunctions.put("deleted", PayComponent::getDeleted);
		attributeSetterBiConsumers.put(
			"deleted",
			(BiConsumer<PayComponent, Boolean>)PayComponent::setDeleted);
		attributeGetterFunctions.put("status", PayComponent::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<PayComponent, Integer>)PayComponent::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getPayComponentId() {
		return _payComponentId;
	}

	@Override
	public void setPayComponentId(long payComponentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_payComponentId = payComponentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public float getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(float amount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amount = amount;
	}

	@JSON
	@Override
	public String getAmountType() {
		if (_amountType == null) {
			return "";
		}
		else {
			return _amountType;
		}
	}

	@Override
	public void setAmountType(String amountType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amountType = amountType;
	}

	@JSON
	@Override
	public Date getFromDate() {
		return _fromDate;
	}

	@Override
	public void setFromDate(Date fromDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fromDate = fromDate;
	}

	@JSON
	@Override
	public Date getToDate() {
		return _toDate;
	}

	@Override
	public void setToDate(Date toDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_toDate = toDate;
	}

	@JSON
	@Override
	public long getDependantId() {
		return _dependantId;
	}

	@Override
	public void setDependantId(long dependantId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dependantId = dependantId;
	}

	@JSON
	@Override
	public long getHeadId() {
		return _headId;
	}

	@Override
	public void setHeadId(long headId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_headId = headId;
	}

	@JSON
	@Override
	public long getStructureId() {
		return _structureId;
	}

	@Override
	public void setStructureId(long structureId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_structureId = structureId;
	}

	@JSON
	@Override
	public boolean getDeleted() {
		return _deleted;
	}

	@JSON
	@Override
	public boolean isDeleted() {
		return _deleted;
	}

	@Override
	public void setDeleted(boolean deleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deleted = deleted;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PayComponent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PayComponent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PayComponent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PayComponentImpl payComponentImpl = new PayComponentImpl();

		payComponentImpl.setPayComponentId(getPayComponentId());
		payComponentImpl.setGroupId(getGroupId());
		payComponentImpl.setCompanyId(getCompanyId());
		payComponentImpl.setUserId(getUserId());
		payComponentImpl.setUserName(getUserName());
		payComponentImpl.setCreateDate(getCreateDate());
		payComponentImpl.setModifiedDate(getModifiedDate());
		payComponentImpl.setActive(isActive());
		payComponentImpl.setAmount(getAmount());
		payComponentImpl.setAmountType(getAmountType());
		payComponentImpl.setFromDate(getFromDate());
		payComponentImpl.setToDate(getToDate());
		payComponentImpl.setDependantId(getDependantId());
		payComponentImpl.setHeadId(getHeadId());
		payComponentImpl.setStructureId(getStructureId());
		payComponentImpl.setDeleted(isDeleted());
		payComponentImpl.setStatus(getStatus());

		payComponentImpl.resetOriginalValues();

		return payComponentImpl;
	}

	@Override
	public int compareTo(PayComponent payComponent) {
		long primaryKey = payComponent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PayComponent)) {
			return false;
		}

		PayComponent payComponent = (PayComponent)object;

		long primaryKey = payComponent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PayComponent> toCacheModel() {
		PayComponentCacheModel payComponentCacheModel =
			new PayComponentCacheModel();

		payComponentCacheModel.payComponentId = getPayComponentId();

		payComponentCacheModel.groupId = getGroupId();

		payComponentCacheModel.companyId = getCompanyId();

		payComponentCacheModel.userId = getUserId();

		payComponentCacheModel.userName = getUserName();

		String userName = payComponentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			payComponentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			payComponentCacheModel.createDate = createDate.getTime();
		}
		else {
			payComponentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			payComponentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			payComponentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		payComponentCacheModel.active = isActive();

		payComponentCacheModel.amount = getAmount();

		payComponentCacheModel.amountType = getAmountType();

		String amountType = payComponentCacheModel.amountType;

		if ((amountType != null) && (amountType.length() == 0)) {
			payComponentCacheModel.amountType = null;
		}

		Date fromDate = getFromDate();

		if (fromDate != null) {
			payComponentCacheModel.fromDate = fromDate.getTime();
		}
		else {
			payComponentCacheModel.fromDate = Long.MIN_VALUE;
		}

		Date toDate = getToDate();

		if (toDate != null) {
			payComponentCacheModel.toDate = toDate.getTime();
		}
		else {
			payComponentCacheModel.toDate = Long.MIN_VALUE;
		}

		payComponentCacheModel.dependantId = getDependantId();

		payComponentCacheModel.headId = getHeadId();

		payComponentCacheModel.structureId = getStructureId();

		payComponentCacheModel.deleted = isDeleted();

		payComponentCacheModel.status = getStatus();

		return payComponentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PayComponent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PayComponent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PayComponent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((PayComponent)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PayComponent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PayComponent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PayComponent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PayComponent)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PayComponent>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _payComponentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _active;
	private float _amount;
	private String _amountType;
	private Date _fromDate;
	private Date _toDate;
	private long _dependantId;
	private long _headId;
	private long _structureId;
	private boolean _deleted;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PayComponent, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PayComponent)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("payComponentId", _payComponentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("amount", _amount);
		_columnOriginalValues.put("amountType", _amountType);
		_columnOriginalValues.put("fromDate", _fromDate);
		_columnOriginalValues.put("toDate", _toDate);
		_columnOriginalValues.put("dependantId", _dependantId);
		_columnOriginalValues.put("headId", _headId);
		_columnOriginalValues.put("structureId", _structureId);
		_columnOriginalValues.put("deleted", _deleted);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("payComponentId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("active_", 128L);

		columnBitmasks.put("amount", 256L);

		columnBitmasks.put("amountType", 512L);

		columnBitmasks.put("fromDate", 1024L);

		columnBitmasks.put("toDate", 2048L);

		columnBitmasks.put("dependantId", 4096L);

		columnBitmasks.put("headId", 8192L);

		columnBitmasks.put("structureId", 16384L);

		columnBitmasks.put("deleted", 32768L);

		columnBitmasks.put("status", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PayComponent _escapedModel;

}