/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.mdm.liferay.model.impl;

import com.adjecti.mdm.liferay.model.UnitType;
import com.adjecti.mdm.liferay.model.UnitTypeModel;
import com.adjecti.mdm.liferay.model.UnitTypeSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UnitType service. Represents a row in the &quot;mdm_UnitType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UnitTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UnitTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UnitTypeImpl
 * @generated
 */
@JSON(strict = true)
public class UnitTypeModelImpl
	extends BaseModelImpl<UnitType> implements UnitTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a unit type model instance should use the <code>UnitType</code> interface instead.
	 */
	public static final String TABLE_NAME = "mdm_UnitType";

	public static final Object[][] TABLE_COLUMNS = {
		{"unitTypeId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"description", Types.VARCHAR},
		{"code_", Types.VARCHAR}, {"shortDiscription", Types.VARCHAR},
		{"longDiscription", Types.VARCHAR}, {"deleted", Types.BOOLEAN},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("unitTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("shortDiscription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("longDiscription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("deleted", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table mdm_UnitType (unitTypeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,description VARCHAR(75) null,code_ VARCHAR(75) null,shortDiscription VARCHAR(75) null,longDiscription VARCHAR(75) null,deleted BOOLEAN,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table mdm_UnitType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY unitType.unitTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY mdm_UnitType.unitTypeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UNITTYPEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static UnitType toModel(UnitTypeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UnitType model = new UnitTypeImpl();

		model.setUnitTypeId(soapModel.getUnitTypeId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDescription(soapModel.getDescription());
		model.setCode(soapModel.getCode());
		model.setShortDiscription(soapModel.getShortDiscription());
		model.setLongDiscription(soapModel.getLongDiscription());
		model.setDeleted(soapModel.isDeleted());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<UnitType> toModels(UnitTypeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UnitType> models = new ArrayList<UnitType>(soapModels.length);

		for (UnitTypeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public UnitTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _unitTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUnitTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _unitTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UnitType.class;
	}

	@Override
	public String getModelClassName() {
		return UnitType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UnitType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UnitType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UnitType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((UnitType)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UnitType, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UnitType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UnitType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UnitType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UnitType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, UnitType>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			UnitType.class.getClassLoader(), UnitType.class,
			ModelWrapper.class);

		try {
			Constructor<UnitType> constructor =
				(Constructor<UnitType>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<UnitType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<UnitType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<UnitType, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<UnitType, Object>>();
		Map<String, BiConsumer<UnitType, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<UnitType, ?>>();

		attributeGetterFunctions.put("unitTypeId", UnitType::getUnitTypeId);
		attributeSetterBiConsumers.put(
			"unitTypeId", (BiConsumer<UnitType, Long>)UnitType::setUnitTypeId);
		attributeGetterFunctions.put("groupId", UnitType::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<UnitType, Long>)UnitType::setGroupId);
		attributeGetterFunctions.put("companyId", UnitType::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<UnitType, Long>)UnitType::setCompanyId);
		attributeGetterFunctions.put("userId", UnitType::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<UnitType, Long>)UnitType::setUserId);
		attributeGetterFunctions.put("userName", UnitType::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<UnitType, String>)UnitType::setUserName);
		attributeGetterFunctions.put("createDate", UnitType::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<UnitType, Date>)UnitType::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", UnitType::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<UnitType, Date>)UnitType::setModifiedDate);
		attributeGetterFunctions.put("description", UnitType::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<UnitType, String>)UnitType::setDescription);
		attributeGetterFunctions.put("code", UnitType::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<UnitType, String>)UnitType::setCode);
		attributeGetterFunctions.put(
			"shortDiscription", UnitType::getShortDiscription);
		attributeSetterBiConsumers.put(
			"shortDiscription",
			(BiConsumer<UnitType, String>)UnitType::setShortDiscription);
		attributeGetterFunctions.put(
			"longDiscription", UnitType::getLongDiscription);
		attributeSetterBiConsumers.put(
			"longDiscription",
			(BiConsumer<UnitType, String>)UnitType::setLongDiscription);
		attributeGetterFunctions.put("deleted", UnitType::getDeleted);
		attributeSetterBiConsumers.put(
			"deleted", (BiConsumer<UnitType, Boolean>)UnitType::setDeleted);
		attributeGetterFunctions.put("status", UnitType::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<UnitType, Integer>)UnitType::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getUnitTypeId() {
		return _unitTypeId;
	}

	@Override
	public void setUnitTypeId(long unitTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_unitTypeId = unitTypeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	@JSON
	@Override
	public String getShortDiscription() {
		if (_shortDiscription == null) {
			return "";
		}
		else {
			return _shortDiscription;
		}
	}

	@Override
	public void setShortDiscription(String shortDiscription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_shortDiscription = shortDiscription;
	}

	@JSON
	@Override
	public String getLongDiscription() {
		if (_longDiscription == null) {
			return "";
		}
		else {
			return _longDiscription;
		}
	}

	@Override
	public void setLongDiscription(String longDiscription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_longDiscription = longDiscription;
	}

	@JSON
	@Override
	public boolean getDeleted() {
		return _deleted;
	}

	@JSON
	@Override
	public boolean isDeleted() {
		return _deleted;
	}

	@Override
	public void setDeleted(boolean deleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deleted = deleted;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), UnitType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UnitType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UnitType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UnitTypeImpl unitTypeImpl = new UnitTypeImpl();

		unitTypeImpl.setUnitTypeId(getUnitTypeId());
		unitTypeImpl.setGroupId(getGroupId());
		unitTypeImpl.setCompanyId(getCompanyId());
		unitTypeImpl.setUserId(getUserId());
		unitTypeImpl.setUserName(getUserName());
		unitTypeImpl.setCreateDate(getCreateDate());
		unitTypeImpl.setModifiedDate(getModifiedDate());
		unitTypeImpl.setDescription(getDescription());
		unitTypeImpl.setCode(getCode());
		unitTypeImpl.setShortDiscription(getShortDiscription());
		unitTypeImpl.setLongDiscription(getLongDiscription());
		unitTypeImpl.setDeleted(isDeleted());
		unitTypeImpl.setStatus(getStatus());

		unitTypeImpl.resetOriginalValues();

		return unitTypeImpl;
	}

	@Override
	public int compareTo(UnitType unitType) {
		long primaryKey = unitType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UnitType)) {
			return false;
		}

		UnitType unitType = (UnitType)object;

		long primaryKey = unitType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UnitType> toCacheModel() {
		UnitTypeCacheModel unitTypeCacheModel = new UnitTypeCacheModel();

		unitTypeCacheModel.unitTypeId = getUnitTypeId();

		unitTypeCacheModel.groupId = getGroupId();

		unitTypeCacheModel.companyId = getCompanyId();

		unitTypeCacheModel.userId = getUserId();

		unitTypeCacheModel.userName = getUserName();

		String userName = unitTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			unitTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			unitTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			unitTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			unitTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			unitTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		unitTypeCacheModel.description = getDescription();

		String description = unitTypeCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			unitTypeCacheModel.description = null;
		}

		unitTypeCacheModel.code = getCode();

		String code = unitTypeCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			unitTypeCacheModel.code = null;
		}

		unitTypeCacheModel.shortDiscription = getShortDiscription();

		String shortDiscription = unitTypeCacheModel.shortDiscription;

		if ((shortDiscription != null) && (shortDiscription.length() == 0)) {
			unitTypeCacheModel.shortDiscription = null;
		}

		unitTypeCacheModel.longDiscription = getLongDiscription();

		String longDiscription = unitTypeCacheModel.longDiscription;

		if ((longDiscription != null) && (longDiscription.length() == 0)) {
			unitTypeCacheModel.longDiscription = null;
		}

		unitTypeCacheModel.deleted = isDeleted();

		unitTypeCacheModel.status = getStatus();

		return unitTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UnitType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UnitType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UnitType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((UnitType)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<UnitType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<UnitType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UnitType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((UnitType)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UnitType>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _unitTypeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _description;
	private String _code;
	private String _shortDiscription;
	private String _longDiscription;
	private boolean _deleted;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<UnitType, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UnitType)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("unitTypeId", _unitTypeId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("code_", _code);
		_columnOriginalValues.put("shortDiscription", _shortDiscription);
		_columnOriginalValues.put("longDiscription", _longDiscription);
		_columnOriginalValues.put("deleted", _deleted);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("code_", "code");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("unitTypeId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("description", 128L);

		columnBitmasks.put("code_", 256L);

		columnBitmasks.put("shortDiscription", 512L);

		columnBitmasks.put("longDiscription", 1024L);

		columnBitmasks.put("deleted", 2048L);

		columnBitmasks.put("status", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UnitType _escapedModel;

}