/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.noting.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Noting service. Represents a row in the &quot;OFB_Noting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.noting.model.impl.NotingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.noting.model.impl.NotingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Noting
 * @generated
 */
@ProviderType
public interface NotingModel
	extends BaseModel<Noting>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a noting model instance should use the {@link Noting} interface instead.
	 */

	/**
	 * Returns the primary key of this noting.
	 *
	 * @return the primary key of this noting
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this noting.
	 *
	 * @param primaryKey the primary key of this noting
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this noting.
	 *
	 * @return the uuid of this noting
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this noting.
	 *
	 * @param uuid the uuid of this noting
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the note ID of this noting.
	 *
	 * @return the note ID of this noting
	 */
	public long getNoteId();

	/**
	 * Sets the note ID of this noting.
	 *
	 * @param noteId the note ID of this noting
	 */
	public void setNoteId(long noteId);

	/**
	 * Returns the group ID of this noting.
	 *
	 * @return the group ID of this noting
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this noting.
	 *
	 * @param groupId the group ID of this noting
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this noting.
	 *
	 * @return the company ID of this noting
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this noting.
	 *
	 * @param companyId the company ID of this noting
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this noting.
	 *
	 * @return the user ID of this noting
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this noting.
	 *
	 * @param userId the user ID of this noting
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this noting.
	 *
	 * @return the user uuid of this noting
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this noting.
	 *
	 * @param userUuid the user uuid of this noting
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this noting.
	 *
	 * @return the user name of this noting
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this noting.
	 *
	 * @param userName the user name of this noting
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this noting.
	 *
	 * @return the create date of this noting
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this noting.
	 *
	 * @param createDate the create date of this noting
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this noting.
	 *
	 * @return the modified date of this noting
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this noting.
	 *
	 * @param modifiedDate the modified date of this noting
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the content of this noting.
	 *
	 * @return the content of this noting
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this noting.
	 *
	 * @param content the content of this noting
	 */
	public void setContent(String content);

	/**
	 * Returns the title of this noting.
	 *
	 * @return the title of this noting
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this noting.
	 *
	 * @param title the title of this noting
	 */
	public void setTitle(String title);

	/**
	 * Returns the pdf ID of this noting.
	 *
	 * @return the pdf ID of this noting
	 */
	public long getPdfId();

	/**
	 * Sets the pdf ID of this noting.
	 *
	 * @param pdfId the pdf ID of this noting
	 */
	public void setPdfId(long pdfId);

}