create table pis_Address (
	addressId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	addressTypeId INTEGER,
	addressLine1 VARCHAR(75) null,
	addressLine2 VARCHAR(75) null,
	addressLine3 VARCHAR(75) null,
	city VARCHAR(75) null,
	pinCode VARCHAR(75) null,
	countryId LONG,
	stateId LONG,
	accomodationTypeId LONG,
	districtId LONG,
	joiningProcessId LONG,
	addressProofId LONG
);

create table pis_Contact (
	contactId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	altEmailAddress VARCHAR(75) null,
	emergencyMobile VARCHAR(75) null,
	facebookId VARCHAR(75) null,
	instagramId VARCHAR(75) null,
	linkedInId VARCHAR(75) null,
	mobile VARCHAR(75) null,
	phone VARCHAR(75) null,
	twitterId VARCHAR(75) null,
	landline VARCHAR(75) null,
	emergencyNo VARCHAR(75) null,
	fax VARCHAR(75) null,
	telegram VARCHAR(75) null,
	telex VARCHAR(75) null,
	personalEmail VARCHAR(75) null
);

create table pis_DeputationProcess (
	uuid_ VARCHAR(75) null,
	deputationProcessId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	processFileId LONG,
	processFileNo LONG,
	notingContent VARCHAR(75) null,
	notingSubmittedDate DATE null,
	notingApprovedDate DATE null,
	processStatus INTEGER,
	processCompletedDate DATE null,
	reviewDate DATE null,
	reviewerUserId LONG,
	approveDate DATE null,
	approverUserId LONG
);

create table pis_DeputationProcessRequest (
	uuid_ VARCHAR(75) null,
	deputationProcessRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	deputationProcessId LONG,
	employeeId LONG,
	deputedOrganization VARCHAR(75) null,
	deputedAddress VARCHAR(75) null,
	deputedCity VARCHAR(75) null,
	deputedState VARCHAR(75) null,
	deputedStartDate DATE null,
	lastDateInCurrentUnit DATE null,
	processFileId LONG,
	processFileNo VARCHAR(75) null,
	officeOrderNo VARCHAR(75) null,
	doPart1Content VARCHAR(75) null,
	doPart1FileId LONG,
	doPart2Content VARCHAR(75) null,
	doPart2FileId LONG
);

create table pis_Employee (
	uuid_ VARCHAR(75) null,
	employeeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	state_ VARCHAR(75) null,
	personalNo VARCHAR(75) null,
	peopleId LONG,
	emailId VARCHAR(75) null,
	designationId LONG,
	gradeId LONG,
	payLevelId LONG,
	postId LONG,
	tradeId LONG,
	cadreId LONG,
	organizationId LONG,
	subOrganizationId LONG,
	gradeModeId LONG,
	designationClassId LONG,
	designationGroupId LONG,
	postName VARCHAR(75) null,
	employmentStatus INTEGER,
	dateOfJoining DATE null,
	dateOfJoiningOrganization DATE null,
	currentDesignationDate DATE null,
	retirementDate DATE null,
	joiningProcessId LONG,
	processType VARCHAR(75) null,
	loginId VARCHAR(75) null,
	bioData STRING null,
	message STRING null,
	gpfNps VARCHAR(75) null,
	gpfNpsNo VARCHAR(75) null,
	rank_ INTEGER
);

create table pis_EmployeeAddress (
	employeeAddressId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromDate DATE null,
	permanent BOOLEAN,
	toDate DATE null,
	addressLine1 VARCHAR(75) null,
	addressLine2 VARCHAR(75) null,
	addressLine3 VARCHAR(75) null,
	city VARCHAR(75) null,
	pinCode VARCHAR(75) null,
	countryId LONG,
	stateId LONG,
	accomodationTypeId LONG,
	districtId LONG,
	joiningProcessId LONG,
	addressProofId LONG,
	status INTEGER,
	addressId LONG,
	employeeId LONG
);

create table pis_EmployeeApplication (
	employeeApplicationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	applicationId LONG
);

create table pis_EmployeeApplicationAccess (
	employeeApplicationAccessId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	loginId VARCHAR(75) null,
	status INTEGER,
	deleted BOOLEAN,
	idamUser BOOLEAN,
	emailAccess BOOLEAN,
	digitalSigning BOOLEAN,
	eGovAccess BOOLEAN,
	pisAccess BOOLEAN,
	statusMessage VARCHAR(75) null,
	userCreated BOOLEAN
);

create table pis_EmployeeBenefitScheme (
	employeeBenefitSchemeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	documentNo VARCHAR(75) null,
	fromDate DATE null,
	toDate DATE null,
	employeeId LONG,
	benefitSchemeId LONG,
	status INTEGER
);

create table pis_EmployeeBiodata (
	employeeBiodataId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	biodata VARCHAR(75) null,
	biodataFileId LONG
);

create table pis_EmployeeConfirmation (
	employeeConfirmationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	confirmationDate DATE null,
	confirmationLetterId LONG,
	designationId LONG,
	gradeId LONG,
	gradeModeId LONG,
	joiningId LONG,
	promotionId LONG,
	organizationId LONG,
	confirmationPostId LONG,
	status INTEGER,
	employeeId LONG
);

create table pis_EmployeeContact (
	employeeContactId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	deskNo VARCHAR(75) null,
	extn VARCHAR(75) null,
	phoneNo VARCHAR(75) null,
	contactId LONG,
	employeeId LONG,
	directNo VARCHAR(75) null
);

create table pis_EmployeeDelegation (
	employeeDelegationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	delegationType LONG,
	delegatedEmployeeId LONG,
	employeeId LONG
);

create table pis_EmployeeDeputation (
	employeeDeputationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromDate DATE null,
	officeAddress VARCHAR(75) null,
	remark VARCHAR(75) null,
	toDate DATE null,
	deputationTypeId LONG,
	departmentId LONG,
	employeeId LONG,
	ministryId LONG,
	postId LONG,
	deputedPostId LONG,
	status INTEGER
);

create table pis_EmployeeDesignation (
	employeeDesignationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromDate DATE null,
	toDate DATE null,
	designationId LONG,
	employeeId LONG
);

create table pis_EmployeeDigitalSignature (
	employeeDigitalSignatureId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	cid VARCHAR(75) null,
	details VARCHAR(75) null,
	issueDate DATE null,
	revokeDate DATE null,
	revoked BOOLEAN
);

create table pis_EmployeeDocument (
	employeeDocumentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	documentId LONG,
	employeeId LONG,
	title VARCHAR(75) null,
	documentTypeId LONG,
	discription VARCHAR(75) null
);

create table pis_EmployeeDsc (
	employeeDscId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	cid VARCHAR(75) null,
	details VARCHAR(75) null,
	ofbDSCReissueDate DATE null,
	ofbDSCRevocationDate DATE null,
	ofbDSCRevocationStatus BOOLEAN,
	ofbDSCReissueStatus BOOLEAN
);

create table pis_EmployeeEmail (
	employeeEmailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	emailAddress VARCHAR(75) null,
	emailAddressType VARCHAR(75) null,
	active_ BOOLEAN
);

create table pis_EmployeeExperience (
	employeeExperienceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromDate DATE null,
	toDate DATE null,
	designationId LONG,
	employeeId LONG,
	postId LONG,
	tradeId LONG,
	experienceId LONG,
	organizationId LONG,
	workAreaId LONG,
	workAreaMinorId LONG,
	status INTEGER
);

create table pis_EmployeeFamily (
	employeeFamilyId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	alive BOOLEAN,
	dateOfBirth DATE null,
	dateOfDemise DATE null,
	dependant BOOLEAN,
	name VARCHAR(75) null,
	employeeId LONG,
	genderId LONG,
	occupationId LONG,
	relationId LONG,
	cgegisPercentage DOUBLE,
	dcrcPercentage DOUBLE,
	healthProblem VARCHAR(75) null,
	nominee BOOLEAN,
	pfPercentage DOUBLE,
	documentProofId LONG,
	status INTEGER
);

create table pis_EmployeeGrade (
	employeeGradeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromDate DATE null,
	toDate DATE null,
	employeeId LONG,
	gradeId LONG,
	gradeModeId LONG
);

create table pis_EmployeeJoining (
	employeeJoiningId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	aadhaarNo VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	exServiceMan BOOLEAN,
	panNo VARCHAR(75) null,
	personalNo VARCHAR(75) null,
	peopleId LONG,
	fullName VARCHAR(75) null,
	designationId LONG,
	gradeId LONG,
	payLevelId LONG,
	postId LONG,
	tradeId LONG,
	organizationId LONG,
	subOrganizationId LONG,
	designationClassId LONG,
	designationGroupId LONG,
	joiningModeId LONG,
	joiningLetterId LONG,
	gradeModeId LONG,
	fromDate DATE null,
	toDate DATE null,
	selectionDate DATE null,
	confirmationDate DATE null,
	gradeConfirmationDate DATE null,
	govtServiceDate DATE null,
	recruitmentBatch VARCHAR(75) null,
	employeeId LONG,
	emailId VARCHAR(75) null,
	postBox VARCHAR(75) null,
	dateOfJoining DATE null,
	dateOfJoiningOrganization DATE null,
	rank_ LONG,
	joiningProcessId LONG,
	status INTEGER
);

create table pis_EmployeeMessage (
	employeeMessageId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	title VARCHAR(75) null,
	message VARCHAR(75) null
);

create table pis_EmployeeOrganization (
	employeeOrganizationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	personalNo VARCHAR(75) null,
	organizationId LONG,
	organizationCode VARCHAR(75) null,
	subOrganizationId LONG,
	subOrganizationCode VARCHAR(75) null,
	active_ BOOLEAN,
	status INTEGER
);

create table pis_EmployeePastExperience (
	employeePastExperienceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromDate DATE null,
	toDate DATE null,
	organization VARCHAR(75) null,
	employeeId LONG,
	experienceLetterId LONG,
	workAreaId LONG,
	designation VARCHAR(75) null,
	joiningProcessId LONG,
	exServiceMan BOOLEAN,
	status INTEGER
);

create table pis_EmployeePayStructure (
	employeePayStructureId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromDate DATE null,
	toDate DATE null,
	employeeId LONG,
	levelId LONG,
	structureId LONG
);

create table pis_EmployeePermission (
	employeePermissionId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	idamUser BOOLEAN,
	digitalSigning BOOLEAN,
	pisAccess BOOLEAN,
	emailAccess BOOLEAN,
	eGovAccess BOOLEAN,
	idamUserCreated BOOLEAN,
	userCreated BOOLEAN,
	employeeCreated BOOLEAN,
	firstName VARCHAR(75) null,
	personalNo LONG,
	lastName VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	designationId LONG,
	employeeId LONG,
	joiningProcessId LONG,
	singleUserOnboardingId LONG,
	registrationRequestId LONG,
	form VARCHAR(75) null,
	currentState VARCHAR(75) null
);

create table pis_EmployeePost (
	employeePostId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromDate DATE null,
	toDate DATE null,
	postId LONG,
	delegatedPostId LONG,
	employeeId LONG,
	status INTEGER
);

create table pis_EmployeeProfile (
	employeeProfileId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	profileDocumentId LONG,
	profileDescription VARCHAR(75) null
);

create table pis_EmployeePromotion (
	employeePromotionId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	promotionDate DATE null,
	designationId LONG,
	employeeId LONG,
	gradeId LONG,
	gradeModeId LONG,
	promotionLetterId LONG,
	organizationId LONG,
	personalNo LONG,
	status INTEGER
);

create table pis_EmployeeQualification (
	employeeQualificationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	foreignDegree BOOLEAN,
	foreignInstitution VARCHAR(75) null,
	fromYear INTEGER,
	marksSecured DOUBLE,
	toYear INTEGER,
	documentProofId LONG,
	employeeId LONG,
	gradeId LONG,
	levelId LONG,
	qualificationId LONG,
	specializationId LONG,
	marksPercentage LONG,
	passedDate DATE null,
	certificateId LONG,
	qualificationDate DATE null,
	institution VARCHAR(75) null,
	joiningProcessId LONG,
	status INTEGER
);

create table pis_EmployeeReporting (
	employeeReportingId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	reportingToId LONG,
	active_ BOOLEAN,
	fromDate DATE null,
	toDate DATE null,
	status INTEGER
);

create table pis_EmployeeSavingScheme (
	employeeSavingSchemeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	documentNo VARCHAR(75) null,
	fromDate DATE null,
	toDate DATE null,
	employeeId LONG,
	gradeId LONG
);



create table pis_EmployeeTrade (
	employeeTradeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromDate DATE null,
	toDate DATE null,
	employeeId LONG,
	tradeId LONG
);

create table pis_EmployeeTraining (
	employeeTrainingId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	durationMonths INTEGER,
	fromMonth DATE null,
	toMonth DATE null,
	courseId LONG,
	employeeId LONG,
	organizationId LONG,
	certificateId LONG,
	endDate DATE null,
	startDate DATE null,
	instituteId LONG,
	status INTEGER
);

create table pis_EmployeeTransfer (
	employeeTransferId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	personalNo VARCHAR(75) null,
	transferDate DATE null,
	designationId LONG,
	employeeId LONG,
	fromOrganizationId LONG,
	gradeId LONG,
	gradeModeId LONG,
	toOrganizationId LONG,
	transferLetterId LONG,
	status INTEGER
);

create table pis_EmployeeVerification (
	employeeVerificationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	authority VARCHAR(75) null,
	documentNo VARCHAR(75) null,
	remarks VARCHAR(75) null,
	verificationDate DATE null,
	verificationTypeId LONG,
	documentId LONG,
	employeeId LONG,
	organizationId LONG,
	joiningProcessId LONG,
	status INTEGER
);

create table pis_EmployeeWorkArea (
	employeeWorkAreaId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	workAreaMajorId LONG,
	active_ BOOLEAN,
	fromDate DATE null,
	toDate DATE null
);

create table pis_EmployeeWorkstation (
	employeeWorkstationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	fromMonth DATE null,
	toMonth DATE null,
	employeeId LONG,
	workStationId LONG,
	deskNo VARCHAR(75) null,
	extnNo VARCHAR(75) null,
	directNo VARCHAR(75) null,
	phoneNo VARCHAR(75) null,
	cabinNo VARCHAR(75) null,
	floorNo VARCHAR(75) null,
	status INTEGER
);

create table pis_Employee_transferProcess (
	companyId LONG not null,
	employeeId LONG not null,
	transferProcessId LONG not null,
	primary key (employeeId, transferProcessId)
);

create table pis_FamilyBenefitScheme (
	familyBenefitSchemeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	percentage DOUBLE,
	familyMemberId LONG,
	benefitSchemeId LONG
);

create table pis_FamilyEducationDetail (
	familyEducationDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	boardUniversity VARCHAR(75) null,
	cityOfStudy VARCHAR(75) null,
	fromYear INTEGER,
	institutionName VARCHAR(75) null,
	toYear INTEGER,
	familyMemberId LONG,
	levelId LONG,
	stateId LONG
);

create table pis_FamilyHealthDetail (
	familyHealthDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	boardUniversity VARCHAR(75) null,
	cityOfStudy VARCHAR(75) null,
	deseaseDetails VARCHAR(75) null,
	fromYear INTEGER,
	institutionName VARCHAR(75) null,
	toYear INTEGER,
	familyMemberId LONG,
	stateId LONG,
	hospitalName VARCHAR(75) null,
	underTreatment BOOLEAN,
	cityOfHospital VARCHAR(75) null,
	levelId LONG,
	diseaseTypeId LONG
);

create table pis_FamilyMemberServiceDetail (
	familyMemberServiceDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	boardUniversity VARCHAR(75) null,
	fromYear INTEGER,
	toYear INTEGER,
	description VARCHAR(75) null,
	endDate DATE null,
	organization VARCHAR(75) null,
	startDate DATE null,
	familyMemberId LONG,
	levelId LONG,
	serviceTypeId LONG
);

create table pis_FamilyServiceDetail (
	familyServiceDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	boardUniversity VARCHAR(75) null,
	fromYear INTEGER,
	toYear INTEGER,
	description VARCHAR(75) null,
	endDate DATE null,
	organization VARCHAR(75) null,
	startDate DATE null,
	familyMemberId LONG,
	levelId LONG,
	serviceTypeId LONG,
	cityOfStudy VARCHAR(75) null,
	institutionName VARCHAR(75) null,
	stateId LONG,
	cityOfWork VARCHAR(75) null,
	designation VARCHAR(75) null,
	govtServant BOOLEAN,
	cityOfHospital VARCHAR(75) null,
	deseaseDetails VARCHAR(75) null,
	hospitalName VARCHAR(75) null,
	underTreatment BOOLEAN,
	diseaseTypeId LONG
);

create table pis_IDAMFailedTransaction (
	idamFailedTransactionId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	classId LONG,
	className VARCHAR(75) null,
	idamUrl VARCHAR(75) null,
	attribute VARCHAR(75) null,
	oldValue VARCHAR(75) null,
	newValue VARCHAR(75) null,
	error VARCHAR(75) null,
	firedon DATE null,
	deleted BOOLEAN,
	status INTEGER
);

create table pis_JoiningProcess (
	uuid_ VARCHAR(75) null,
	joiningProcessId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	reason VARCHAR(75) null,
	personalNo LONG,
	unitId LONG,
	processFileId LONG,
	processFileNo LONG,
	notingContent VARCHAR(75) null,
	notingSubmittedDate DATE null,
	notingApprovedDate DATE null,
	processStatus INTEGER,
	processCompletedDate DATE null,
	reviewDate DATE null,
	reviewerUserId LONG,
	approveDate DATE null,
	approverUserId LONG
);

create table pis_JoiningProcessRequest (
	uuid_ VARCHAR(75) null,
	joiningProcessRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	joiningProcessId LONG,
	employeeId LONG,
	processFileId LONG,
	processFileNo VARCHAR(75) null,
	officeOrderNo VARCHAR(75) null,
	doPart1Content VARCHAR(75) null,
	doPart1FileId LONG,
	doPart2Content VARCHAR(75) null,
	doPart2FileId LONG
);

create table pis_MonthlySalary (
	monthlySalaryId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	grossDeduction DOUBLE,
	grossIncome DOUBLE,
	netPayble DOUBLE,
	processMonth DATE null,
	employeeId LONG,
	structureId LONG
);

create table pis_MonthlySalaryComponent (
	monthlySalaryComponentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	amount DOUBLE,
	componentId LONG,
	salaryId LONG
);

create table pis_OrganizationAssignment (
	organizationAssignmentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	personalNo VARCHAR(75) null,
	organizationId LONG,
	organizationCode VARCHAR(75) null,
	subOrganizationId LONG,
	subOrganizationCode VARCHAR(75) null,
	active_ BOOLEAN
);

create table pis_People (
	peopleId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	appellationId LONG,
	firstName_Hi VARCHAR(75) null,
	firstName_En VARCHAR(75) null,
	lastName_Hi VARCHAR(75) null,
	lastName_En VARCHAR(75) null,
	middleName_Hi VARCHAR(75) null,
	middleName_En VARCHAR(75) null,
	fatherName_Hi VARCHAR(75) null,
	fatherName_En VARCHAR(75) null,
	dateOfBirth DATE null,
	genderId LONG,
	maritalStatusId LONG,
	casteCategoryId LONG,
	identityProofId LONG,
	bloodGroupId LONG,
	citizenshipId LONG,
	phTypeId LONG,
	religionId LONG,
	aadhaarNo VARCHAR(75) null,
	panNo VARCHAR(75) null,
	color VARCHAR(75) null,
	height DOUBLE,
	identificationMark VARCHAR(75) null,
	exServiceMan BOOLEAN,
	profileImageId LONG,
	joiningProcessId LONG
);

create table pis_ProcessFile (
	uuid_ VARCHAR(75) null,
	processFileId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	processFileNo LONG
);

create table pis_PromotionProcess (
	uuid_ VARCHAR(75) null,
	promotionProcessId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	processFileId LONG,
	processFileNo LONG,
	notingContent VARCHAR(75) null,
	notingSubmittedDate DATE null,
	notingApprovedDate DATE null,
	processStatus INTEGER,
	processCompletedDate DATE null,
	reviewDate DATE null,
	reviewerUserId LONG,
	approveDate DATE null,
	approverUserId LONG
);

create table pis_PromotionProcessRequest (
	uuid_ VARCHAR(75) null,
	promotionProcessRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	promotionProcessId LONG,
	employeeId LONG,
	designationId LONG,
	promotionModeId LONG,
	promotionDate DATE null,
	officeOrderNo VARCHAR(75) null,
	processFileId LONG,
	processFileNo VARCHAR(75) null,
	doPart1Content VARCHAR(75) null,
	doPart1FileId LONG,
	doPart2Content VARCHAR(75) null,
	doPart2FileId LONG
);

create table pis_SampleProcess (
	uuid_ VARCHAR(75) null,
	sampleProcessId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	processFileId LONG,
	processFileNo LONG,
	notingContent VARCHAR(75) null,
	notingSubmittedDate DATE null,
	notingApprovedDate DATE null,
	processStatus INTEGER,
	processCompletedDate DATE null,
	reviewDate DATE null,
	reviewerUserId LONG,
	approveDate DATE null,
	approverUserId LONG
);

create table pis_SampleProcessRequest (
	uuid_ VARCHAR(75) null,
	sampleProcessRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeId LONG,
	deputationOrganization VARCHAR(75) null,
	deputationAddress VARCHAR(75) null,
	deputationCity VARCHAR(75) null,
	deputationState VARCHAR(75) null,
	processFileId LONG,
	processFileNo LONG,
	doPart1Content VARCHAR(75) null,
	doPart1SumittedDate DATE null,
	doPart1ReviewDate DATE null,
	doPart1Status LONG,
	doPart2Content VARCHAR(75) null,
	doPart2SumittedDate DATE null,
	doPart2ReviewDate DATE null,
	doPart2Status LONG,
	requestStatus INTEGER,
	requestCompletedDate DATE null,
	reviewDate DATE null,
	reviewerUserId LONG,
	approveDate DATE null,
	approverUserId LONG
);

create table pis_SeparationProcess (
	uuid_ VARCHAR(75) null,
	separationProcessId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	processFileId LONG,
	processFileNo LONG,
	notingContent VARCHAR(75) null,
	notingSubmittedDate DATE null,
	notingApprovedDate DATE null,
	processStatus INTEGER,
	processCompletedDate DATE null,
	reviewDate DATE null,
	reviewerUserId LONG,
	approveDate DATE null,
	approverUserId LONG
);

create table pis_SeparationProcessRequest (
	uuid_ VARCHAR(75) null,
	separationProcessRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	separationProcessId LONG,
	employeeId LONG,
	separationMode LONG,
	separationDate DATE null,
	remarks VARCHAR(75) null,
	processFileId LONG,
	processFileNo VARCHAR(75) null,
	officeOrderNo VARCHAR(75) null,
	doPart1Content VARCHAR(75) null,
	doPart1FileId LONG,
	doPart2Content VARCHAR(75) null,
	doPart2FileId LONG
);

create table pis_ServiceRequest (
	serviceRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	active_ BOOLEAN,
	serviceRequestTypeId LONG,
	subject VARCHAR(75) null,
	description VARCHAR(75) null,
	employeeId LONG,
	documentProofId LONG,
	organizationId LONG,
	joiningProcessId LONG,
	status INTEGER,
	deleted BOOLEAN,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	state_ VARCHAR(75) null,
	comments VARCHAR(75) null
);

create table pis_ServiceRequestType (
	serviceRequestTypeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	className VARCHAR(75) null,
	action VARCHAR(75) null,
	deleted BOOLEAN,
	status INTEGER
);

create table pis_ServiceRequestWfStatusType (
	serviceRequestWfStatusTypeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name LONG,
	className VARCHAR(75) null,
	deleted BOOLEAN,
	status INTEGER
);

create table pis_ServiceRequestWorkflow (
	serviceRequestWorkflowId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	serviceRequestId LONG,
	employeeId LONG,
	className VARCHAR(75) null,
	classPK LONG,
	remark VARCHAR(75) null,
	status INTEGER
);

create table pis_SingleUserOnboarding (
	uuid_ VARCHAR(75) null,
	singleUserRegistrationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	recordNo LONG,
	unitId LONG,
	unit VARCHAR(75) null,
	personalNo LONG,
	firstName VARCHAR(75) null,
	middleName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	genderId LONG,
	gender VARCHAR(75) null,
	designationId LONG,
	designation VARCHAR(75) null,
	designationCode VARCHAR(75) null,
	tradeId LONG,
	trade VARCHAR(75) null,
	tradeCode VARCHAR(75) null,
	gradeId LONG,
	grade VARCHAR(75) null,
	gradeCode VARCHAR(75) null,
	dateOfBirth DATE null,
	dateOfJoiningOrganization DATE null,
	casteCategoryId LONG,
	casteCategory VARCHAR(75) null,
	mobile LONG,
	emailAddress VARCHAR(75) null,
	dateOfJoiningUnit DATE null,
	gpfnpsType VARCHAR(75) null,
	gpfnpsNumber LONG,
	sectionId LONG,
	section VARCHAR(75) null,
	sectionCode VARCHAR(75) null,
	loginId VARCHAR(75) null,
	idamUser BOOLEAN,
	emailAccess BOOLEAN,
	digitalSigning BOOLEAN,
	eGovAccess BOOLEAN,
	pisAccess BOOLEAN,
	state_ VARCHAR(75) null,
	idamUserCreated BOOLEAN,
	employeeCreated BOOLEAN,
	appUserCreated BOOLEAN,
	postBox VARCHAR(75) null,
	rank_ LONG,
	description VARCHAR(75) null,
	reason VARCHAR(75) null
);

create table pis_TransferProcess (
	uuid_ VARCHAR(75) null,
	transferProcessId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	processFileId LONG,
	processFileNo LONG,
	notingContent VARCHAR(75) null,
	notingSubmittedDate DATE null,
	notingApprovedDate DATE null,
	processStatus INTEGER,
	processCompletedDate DATE null,
	reviewDate DATE null,
	reviewerUserId LONG,
	approveDate DATE null,
	approverUserId LONG
);

create table pis_TransferProcessRequest (
	uuid_ VARCHAR(75) null,
	transferProcessRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	transferProcessId LONG,
	employeeId LONG,
	organizationId LONG,
	transferDate DATE null,
	startDateInNewUnit DATE null,
	lastDateInCurrentUnit DATE null,
	officeOrderNo VARCHAR(75) null,
	processFileId LONG,
	processFileNo VARCHAR(75) null,
	doPart1Content VARCHAR(75) null,
	doPart1FileId LONG,
	doPart2Content VARCHAR(75) null,
	doPart2FileId LONG
);