/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Contact service. Represents a row in the &quot;pis_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.ContactModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.ContactImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Contact
 * @generated
 */
@ProviderType
public interface ContactModel
	extends BaseModel<Contact>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact model instance should use the {@link Contact} interface instead.
	 */

	/**
	 * Returns the primary key of this contact.
	 *
	 * @return the primary key of this contact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact.
	 *
	 * @param primaryKey the primary key of this contact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the contact ID of this contact.
	 *
	 * @return the contact ID of this contact
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this contact.
	 *
	 * @param contactId the contact ID of this contact
	 */
	public void setContactId(long contactId);

	/**
	 * Returns the group ID of this contact.
	 *
	 * @return the group ID of this contact
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this contact.
	 *
	 * @param groupId the group ID of this contact
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this contact.
	 *
	 * @return the company ID of this contact
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this contact.
	 *
	 * @param companyId the company ID of this contact
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contact.
	 *
	 * @return the user ID of this contact
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this contact.
	 *
	 * @param userId the user ID of this contact
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contact.
	 *
	 * @return the user uuid of this contact
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this contact.
	 *
	 * @param userUuid the user uuid of this contact
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this contact.
	 *
	 * @return the user name of this contact
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this contact.
	 *
	 * @param userName the user name of this contact
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this contact.
	 *
	 * @return the create date of this contact
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this contact.
	 *
	 * @param createDate the create date of this contact
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contact.
	 *
	 * @return the modified date of this contact
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contact.
	 *
	 * @param modifiedDate the modified date of this contact
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the alt email address of this contact.
	 *
	 * @return the alt email address of this contact
	 */
	@AutoEscape
	public String getAltEmailAddress();

	/**
	 * Sets the alt email address of this contact.
	 *
	 * @param altEmailAddress the alt email address of this contact
	 */
	public void setAltEmailAddress(String altEmailAddress);

	/**
	 * Returns the emergency mobile of this contact.
	 *
	 * @return the emergency mobile of this contact
	 */
	@AutoEscape
	public String getEmergencyMobile();

	/**
	 * Sets the emergency mobile of this contact.
	 *
	 * @param emergencyMobile the emergency mobile of this contact
	 */
	public void setEmergencyMobile(String emergencyMobile);

	/**
	 * Returns the facebook ID of this contact.
	 *
	 * @return the facebook ID of this contact
	 */
	@AutoEscape
	public String getFacebookId();

	/**
	 * Sets the facebook ID of this contact.
	 *
	 * @param facebookId the facebook ID of this contact
	 */
	public void setFacebookId(String facebookId);

	/**
	 * Returns the instagram ID of this contact.
	 *
	 * @return the instagram ID of this contact
	 */
	@AutoEscape
	public String getInstagramId();

	/**
	 * Sets the instagram ID of this contact.
	 *
	 * @param instagramId the instagram ID of this contact
	 */
	public void setInstagramId(String instagramId);

	/**
	 * Returns the linked in ID of this contact.
	 *
	 * @return the linked in ID of this contact
	 */
	@AutoEscape
	public String getLinkedInId();

	/**
	 * Sets the linked in ID of this contact.
	 *
	 * @param linkedInId the linked in ID of this contact
	 */
	public void setLinkedInId(String linkedInId);

	/**
	 * Returns the mobile of this contact.
	 *
	 * @return the mobile of this contact
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this contact.
	 *
	 * @param mobile the mobile of this contact
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the phone of this contact.
	 *
	 * @return the phone of this contact
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this contact.
	 *
	 * @param phone the phone of this contact
	 */
	public void setPhone(String phone);

	/**
	 * Returns the twitter ID of this contact.
	 *
	 * @return the twitter ID of this contact
	 */
	@AutoEscape
	public String getTwitterId();

	/**
	 * Sets the twitter ID of this contact.
	 *
	 * @param twitterId the twitter ID of this contact
	 */
	public void setTwitterId(String twitterId);

	/**
	 * Returns the landline of this contact.
	 *
	 * @return the landline of this contact
	 */
	@AutoEscape
	public String getLandline();

	/**
	 * Sets the landline of this contact.
	 *
	 * @param landline the landline of this contact
	 */
	public void setLandline(String landline);

	/**
	 * Returns the emergency no of this contact.
	 *
	 * @return the emergency no of this contact
	 */
	@AutoEscape
	public String getEmergencyNo();

	/**
	 * Sets the emergency no of this contact.
	 *
	 * @param emergencyNo the emergency no of this contact
	 */
	public void setEmergencyNo(String emergencyNo);

	/**
	 * Returns the fax of this contact.
	 *
	 * @return the fax of this contact
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this contact.
	 *
	 * @param fax the fax of this contact
	 */
	public void setFax(String fax);

	/**
	 * Returns the telegram of this contact.
	 *
	 * @return the telegram of this contact
	 */
	@AutoEscape
	public String getTelegram();

	/**
	 * Sets the telegram of this contact.
	 *
	 * @param telegram the telegram of this contact
	 */
	public void setTelegram(String telegram);

	/**
	 * Returns the telex of this contact.
	 *
	 * @return the telex of this contact
	 */
	@AutoEscape
	public String getTelex();

	/**
	 * Sets the telex of this contact.
	 *
	 * @param telex the telex of this contact
	 */
	public void setTelex(String telex);

	/**
	 * Returns the personal email of this contact.
	 *
	 * @return the personal email of this contact
	 */
	@AutoEscape
	public String getPersonalEmail();

	/**
	 * Sets the personal email of this contact.
	 *
	 * @param personalEmail the personal email of this contact
	 */
	public void setPersonalEmail(String personalEmail);

}