/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;pis_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.EmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.EmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @generated
 */
@ProviderType
public interface EmployeeModel
	extends BaseModel<Employee>, GroupedModel, ShardedModel, StagedAuditedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee.
	 *
	 * @return the uuid of this employee
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employee.
	 *
	 * @param uuid the uuid of this employee
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the employee ID of this employee.
	 *
	 * @return the employee ID of this employee
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee.
	 *
	 * @param employeeId the employee ID of this employee
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this employee.
	 *
	 * @return the group ID of this employee
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee.
	 *
	 * @param groupId the group ID of this employee
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee.
	 *
	 * @return the company ID of this employee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee.
	 *
	 * @param companyId the company ID of this employee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee.
	 *
	 * @return the user ID of this employee
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee.
	 *
	 * @param userId the user ID of this employee
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee.
	 *
	 * @return the user uuid of this employee
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee.
	 *
	 * @param userUuid the user uuid of this employee
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee.
	 *
	 * @return the user name of this employee
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee.
	 *
	 * @param userName the user name of this employee
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee.
	 *
	 * @return the create date of this employee
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee.
	 *
	 * @param createDate the create date of this employee
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee.
	 *
	 * @return the modified date of this employee
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee.
	 *
	 * @param modifiedDate the modified date of this employee
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this employee.
	 *
	 * @return the status of this employee
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this employee.
	 *
	 * @param status the status of this employee
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this employee.
	 *
	 * @return the status by user ID of this employee
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this employee.
	 *
	 * @param statusByUserId the status by user ID of this employee
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this employee.
	 *
	 * @return the status by user uuid of this employee
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this employee.
	 *
	 * @param statusByUserUuid the status by user uuid of this employee
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this employee.
	 *
	 * @return the status by user name of this employee
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this employee.
	 *
	 * @param statusByUserName the status by user name of this employee
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this employee.
	 *
	 * @return the status date of this employee
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this employee.
	 *
	 * @param statusDate the status date of this employee
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the state of this employee.
	 *
	 * @return the state of this employee
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this employee.
	 *
	 * @param state the state of this employee
	 */
	public void setState(String state);

	/**
	 * Returns the personal no of this employee.
	 *
	 * @return the personal no of this employee
	 */
	@AutoEscape
	public String getPersonalNo();

	/**
	 * Sets the personal no of this employee.
	 *
	 * @param personalNo the personal no of this employee
	 */
	public void setPersonalNo(String personalNo);

	/**
	 * Returns the people ID of this employee.
	 *
	 * @return the people ID of this employee
	 */
	public long getPeopleId();

	/**
	 * Sets the people ID of this employee.
	 *
	 * @param peopleId the people ID of this employee
	 */
	public void setPeopleId(long peopleId);

	/**
	 * Returns the email ID of this employee.
	 *
	 * @return the email ID of this employee
	 */
	@AutoEscape
	public String getEmailId();

	/**
	 * Sets the email ID of this employee.
	 *
	 * @param emailId the email ID of this employee
	 */
	public void setEmailId(String emailId);

	/**
	 * Returns the designation ID of this employee.
	 *
	 * @return the designation ID of this employee
	 */
	public long getDesignationId();

	/**
	 * Sets the designation ID of this employee.
	 *
	 * @param designationId the designation ID of this employee
	 */
	public void setDesignationId(long designationId);

	/**
	 * Returns the grade ID of this employee.
	 *
	 * @return the grade ID of this employee
	 */
	public long getGradeId();

	/**
	 * Sets the grade ID of this employee.
	 *
	 * @param gradeId the grade ID of this employee
	 */
	public void setGradeId(long gradeId);

	/**
	 * Returns the pay level ID of this employee.
	 *
	 * @return the pay level ID of this employee
	 */
	public long getPayLevelId();

	/**
	 * Sets the pay level ID of this employee.
	 *
	 * @param payLevelId the pay level ID of this employee
	 */
	public void setPayLevelId(long payLevelId);

	/**
	 * Returns the post ID of this employee.
	 *
	 * @return the post ID of this employee
	 */
	public long getPostId();

	/**
	 * Sets the post ID of this employee.
	 *
	 * @param postId the post ID of this employee
	 */
	public void setPostId(long postId);

	/**
	 * Returns the trade ID of this employee.
	 *
	 * @return the trade ID of this employee
	 */
	public long getTradeId();

	/**
	 * Sets the trade ID of this employee.
	 *
	 * @param tradeId the trade ID of this employee
	 */
	public void setTradeId(long tradeId);

	/**
	 * Returns the cadre ID of this employee.
	 *
	 * @return the cadre ID of this employee
	 */
	public long getCadreId();

	/**
	 * Sets the cadre ID of this employee.
	 *
	 * @param cadreId the cadre ID of this employee
	 */
	public void setCadreId(long cadreId);

	/**
	 * Returns the organization ID of this employee.
	 *
	 * @return the organization ID of this employee
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this employee.
	 *
	 * @param organizationId the organization ID of this employee
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the sub organization ID of this employee.
	 *
	 * @return the sub organization ID of this employee
	 */
	public long getSubOrganizationId();

	/**
	 * Sets the sub organization ID of this employee.
	 *
	 * @param subOrganizationId the sub organization ID of this employee
	 */
	public void setSubOrganizationId(long subOrganizationId);

	/**
	 * Returns the grade mode ID of this employee.
	 *
	 * @return the grade mode ID of this employee
	 */
	public long getGradeModeId();

	/**
	 * Sets the grade mode ID of this employee.
	 *
	 * @param gradeModeId the grade mode ID of this employee
	 */
	public void setGradeModeId(long gradeModeId);

	/**
	 * Returns the designation class ID of this employee.
	 *
	 * @return the designation class ID of this employee
	 */
	public long getDesignationClassId();

	/**
	 * Sets the designation class ID of this employee.
	 *
	 * @param designationClassId the designation class ID of this employee
	 */
	public void setDesignationClassId(long designationClassId);

	/**
	 * Returns the designation group ID of this employee.
	 *
	 * @return the designation group ID of this employee
	 */
	public long getDesignationGroupId();

	/**
	 * Sets the designation group ID of this employee.
	 *
	 * @param designationGroupId the designation group ID of this employee
	 */
	public void setDesignationGroupId(long designationGroupId);

	/**
	 * Returns the post name of this employee.
	 *
	 * @return the post name of this employee
	 */
	@AutoEscape
	public String getPostName();

	/**
	 * Sets the post name of this employee.
	 *
	 * @param postName the post name of this employee
	 */
	public void setPostName(String postName);

	/**
	 * Returns the employment status of this employee.
	 *
	 * @return the employment status of this employee
	 */
	public int getEmploymentStatus();

	/**
	 * Sets the employment status of this employee.
	 *
	 * @param employmentStatus the employment status of this employee
	 */
	public void setEmploymentStatus(int employmentStatus);

	/**
	 * Returns the date of joining of this employee.
	 *
	 * @return the date of joining of this employee
	 */
	public Date getDateOfJoining();

	/**
	 * Sets the date of joining of this employee.
	 *
	 * @param dateOfJoining the date of joining of this employee
	 */
	public void setDateOfJoining(Date dateOfJoining);

	/**
	 * Returns the date of joining organization of this employee.
	 *
	 * @return the date of joining organization of this employee
	 */
	public Date getDateOfJoiningOrganization();

	/**
	 * Sets the date of joining organization of this employee.
	 *
	 * @param dateOfJoiningOrganization the date of joining organization of this employee
	 */
	public void setDateOfJoiningOrganization(Date dateOfJoiningOrganization);

	/**
	 * Returns the current designation date of this employee.
	 *
	 * @return the current designation date of this employee
	 */
	public Date getCurrentDesignationDate();

	/**
	 * Sets the current designation date of this employee.
	 *
	 * @param currentDesignationDate the current designation date of this employee
	 */
	public void setCurrentDesignationDate(Date currentDesignationDate);

	/**
	 * Returns the retirement date of this employee.
	 *
	 * @return the retirement date of this employee
	 */
	public Date getRetirementDate();

	/**
	 * Sets the retirement date of this employee.
	 *
	 * @param retirementDate the retirement date of this employee
	 */
	public void setRetirementDate(Date retirementDate);

	/**
	 * Returns the joining process ID of this employee.
	 *
	 * @return the joining process ID of this employee
	 */
	public long getJoiningProcessId();

	/**
	 * Sets the joining process ID of this employee.
	 *
	 * @param joiningProcessId the joining process ID of this employee
	 */
	public void setJoiningProcessId(long joiningProcessId);

	/**
	 * Returns the process type of this employee.
	 *
	 * @return the process type of this employee
	 */
	@AutoEscape
	public String getProcessType();

	/**
	 * Sets the process type of this employee.
	 *
	 * @param processType the process type of this employee
	 */
	public void setProcessType(String processType);

	/**
	 * Returns the login ID of this employee.
	 *
	 * @return the login ID of this employee
	 */
	@AutoEscape
	public String getLoginId();

	/**
	 * Sets the login ID of this employee.
	 *
	 * @param loginId the login ID of this employee
	 */
	public void setLoginId(String loginId);

	/**
	 * Returns the bio data of this employee.
	 *
	 * @return the bio data of this employee
	 */
	@AutoEscape
	public String getBioData();

	/**
	 * Sets the bio data of this employee.
	 *
	 * @param bioData the bio data of this employee
	 */
	public void setBioData(String bioData);

	/**
	 * Returns the message of this employee.
	 *
	 * @return the message of this employee
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this employee.
	 *
	 * @param message the message of this employee
	 */
	public void setMessage(String message);

	/**
	 * Returns the gpf nps of this employee.
	 *
	 * @return the gpf nps of this employee
	 */
	@AutoEscape
	public String getGpfNps();

	/**
	 * Sets the gpf nps of this employee.
	 *
	 * @param gpfNps the gpf nps of this employee
	 */
	public void setGpfNps(String gpfNps);

	/**
	 * Returns the gpf nps no of this employee.
	 *
	 * @return the gpf nps no of this employee
	 */
	@AutoEscape
	public String getGpfNpsNo();

	/**
	 * Sets the gpf nps no of this employee.
	 *
	 * @param gpfNpsNo the gpf nps no of this employee
	 */
	public void setGpfNpsNo(String gpfNpsNo);

	/**
	 * Returns the rank of this employee.
	 *
	 * @return the rank of this employee
	 */
	public int getRank();

	/**
	 * Sets the rank of this employee.
	 *
	 * @param rank the rank of this employee
	 */
	public void setRank(int rank);

	/**
	 * Returns <code>true</code> if this employee is approved.
	 *
	 * @return <code>true</code> if this employee is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this employee is denied.
	 *
	 * @return <code>true</code> if this employee is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this employee is a draft.
	 *
	 * @return <code>true</code> if this employee is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this employee is expired.
	 *
	 * @return <code>true</code> if this employee is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this employee is inactive.
	 *
	 * @return <code>true</code> if this employee is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this employee is incomplete.
	 *
	 * @return <code>true</code> if this employee is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this employee is pending.
	 *
	 * @return <code>true</code> if this employee is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this employee is scheduled.
	 *
	 * @return <code>true</code> if this employee is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}