/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeDeputation service. Represents a row in the &quot;pis_EmployeeDeputation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.EmployeeDeputationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.EmployeeDeputationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDeputation
 * @generated
 */
@ProviderType
public interface EmployeeDeputationModel
	extends BaseModel<EmployeeDeputation>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee deputation model instance should use the {@link EmployeeDeputation} interface instead.
	 */

	/**
	 * Returns the primary key of this employee deputation.
	 *
	 * @return the primary key of this employee deputation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee deputation.
	 *
	 * @param primaryKey the primary key of this employee deputation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee deputation ID of this employee deputation.
	 *
	 * @return the employee deputation ID of this employee deputation
	 */
	public long getEmployeeDeputationId();

	/**
	 * Sets the employee deputation ID of this employee deputation.
	 *
	 * @param employeeDeputationId the employee deputation ID of this employee deputation
	 */
	public void setEmployeeDeputationId(long employeeDeputationId);

	/**
	 * Returns the group ID of this employee deputation.
	 *
	 * @return the group ID of this employee deputation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee deputation.
	 *
	 * @param groupId the group ID of this employee deputation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee deputation.
	 *
	 * @return the company ID of this employee deputation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee deputation.
	 *
	 * @param companyId the company ID of this employee deputation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee deputation.
	 *
	 * @return the user ID of this employee deputation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee deputation.
	 *
	 * @param userId the user ID of this employee deputation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee deputation.
	 *
	 * @return the user uuid of this employee deputation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee deputation.
	 *
	 * @param userUuid the user uuid of this employee deputation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee deputation.
	 *
	 * @return the user name of this employee deputation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee deputation.
	 *
	 * @param userName the user name of this employee deputation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee deputation.
	 *
	 * @return the create date of this employee deputation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee deputation.
	 *
	 * @param createDate the create date of this employee deputation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee deputation.
	 *
	 * @return the modified date of this employee deputation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee deputation.
	 *
	 * @param modifiedDate the modified date of this employee deputation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this employee deputation.
	 *
	 * @return the active of this employee deputation
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this employee deputation is active.
	 *
	 * @return <code>true</code> if this employee deputation is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this employee deputation is active.
	 *
	 * @param active the active of this employee deputation
	 */
	public void setActive(boolean active);

	/**
	 * Returns the from date of this employee deputation.
	 *
	 * @return the from date of this employee deputation
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this employee deputation.
	 *
	 * @param fromDate the from date of this employee deputation
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the office address of this employee deputation.
	 *
	 * @return the office address of this employee deputation
	 */
	@AutoEscape
	public String getOfficeAddress();

	/**
	 * Sets the office address of this employee deputation.
	 *
	 * @param officeAddress the office address of this employee deputation
	 */
	public void setOfficeAddress(String officeAddress);

	/**
	 * Returns the remark of this employee deputation.
	 *
	 * @return the remark of this employee deputation
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this employee deputation.
	 *
	 * @param remark the remark of this employee deputation
	 */
	public void setRemark(String remark);

	/**
	 * Returns the to date of this employee deputation.
	 *
	 * @return the to date of this employee deputation
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this employee deputation.
	 *
	 * @param toDate the to date of this employee deputation
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the deputation type ID of this employee deputation.
	 *
	 * @return the deputation type ID of this employee deputation
	 */
	public long getDeputationTypeId();

	/**
	 * Sets the deputation type ID of this employee deputation.
	 *
	 * @param deputationTypeId the deputation type ID of this employee deputation
	 */
	public void setDeputationTypeId(long deputationTypeId);

	/**
	 * Returns the department ID of this employee deputation.
	 *
	 * @return the department ID of this employee deputation
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this employee deputation.
	 *
	 * @param departmentId the department ID of this employee deputation
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the employee ID of this employee deputation.
	 *
	 * @return the employee ID of this employee deputation
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee deputation.
	 *
	 * @param employeeId the employee ID of this employee deputation
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the ministry ID of this employee deputation.
	 *
	 * @return the ministry ID of this employee deputation
	 */
	public long getMinistryId();

	/**
	 * Sets the ministry ID of this employee deputation.
	 *
	 * @param ministryId the ministry ID of this employee deputation
	 */
	public void setMinistryId(long ministryId);

	/**
	 * Returns the post ID of this employee deputation.
	 *
	 * @return the post ID of this employee deputation
	 */
	public long getPostId();

	/**
	 * Sets the post ID of this employee deputation.
	 *
	 * @param postId the post ID of this employee deputation
	 */
	public void setPostId(long postId);

	/**
	 * Returns the deputed post ID of this employee deputation.
	 *
	 * @return the deputed post ID of this employee deputation
	 */
	public long getDeputedPostId();

	/**
	 * Sets the deputed post ID of this employee deputation.
	 *
	 * @param deputedPostId the deputed post ID of this employee deputation
	 */
	public void setDeputedPostId(long deputedPostId);

	/**
	 * Returns the status of this employee deputation.
	 *
	 * @return the status of this employee deputation
	 */
	public int getStatus();

	/**
	 * Sets the status of this employee deputation.
	 *
	 * @param status the status of this employee deputation
	 */
	public void setStatus(int status);

}