/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeTransfer service. Represents a row in the &quot;pis_EmployeeTransfer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.EmployeeTransferModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.EmployeeTransferImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeTransfer
 * @generated
 */
@ProviderType
public interface EmployeeTransferModel
	extends BaseModel<EmployeeTransfer>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee transfer model instance should use the {@link EmployeeTransfer} interface instead.
	 */

	/**
	 * Returns the primary key of this employee transfer.
	 *
	 * @return the primary key of this employee transfer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee transfer.
	 *
	 * @param primaryKey the primary key of this employee transfer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee transfer ID of this employee transfer.
	 *
	 * @return the employee transfer ID of this employee transfer
	 */
	public long getEmployeeTransferId();

	/**
	 * Sets the employee transfer ID of this employee transfer.
	 *
	 * @param employeeTransferId the employee transfer ID of this employee transfer
	 */
	public void setEmployeeTransferId(long employeeTransferId);

	/**
	 * Returns the group ID of this employee transfer.
	 *
	 * @return the group ID of this employee transfer
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee transfer.
	 *
	 * @param groupId the group ID of this employee transfer
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee transfer.
	 *
	 * @return the company ID of this employee transfer
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee transfer.
	 *
	 * @param companyId the company ID of this employee transfer
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee transfer.
	 *
	 * @return the user ID of this employee transfer
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee transfer.
	 *
	 * @param userId the user ID of this employee transfer
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee transfer.
	 *
	 * @return the user uuid of this employee transfer
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee transfer.
	 *
	 * @param userUuid the user uuid of this employee transfer
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee transfer.
	 *
	 * @return the user name of this employee transfer
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee transfer.
	 *
	 * @param userName the user name of this employee transfer
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee transfer.
	 *
	 * @return the create date of this employee transfer
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee transfer.
	 *
	 * @param createDate the create date of this employee transfer
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee transfer.
	 *
	 * @return the modified date of this employee transfer
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee transfer.
	 *
	 * @param modifiedDate the modified date of this employee transfer
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this employee transfer.
	 *
	 * @return the active of this employee transfer
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this employee transfer is active.
	 *
	 * @return <code>true</code> if this employee transfer is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this employee transfer is active.
	 *
	 * @param active the active of this employee transfer
	 */
	public void setActive(boolean active);

	/**
	 * Returns the personal no of this employee transfer.
	 *
	 * @return the personal no of this employee transfer
	 */
	@AutoEscape
	public String getPersonalNo();

	/**
	 * Sets the personal no of this employee transfer.
	 *
	 * @param personalNo the personal no of this employee transfer
	 */
	public void setPersonalNo(String personalNo);

	/**
	 * Returns the transfer date of this employee transfer.
	 *
	 * @return the transfer date of this employee transfer
	 */
	public Date getTransferDate();

	/**
	 * Sets the transfer date of this employee transfer.
	 *
	 * @param transferDate the transfer date of this employee transfer
	 */
	public void setTransferDate(Date transferDate);

	/**
	 * Returns the designation ID of this employee transfer.
	 *
	 * @return the designation ID of this employee transfer
	 */
	public long getDesignationId();

	/**
	 * Sets the designation ID of this employee transfer.
	 *
	 * @param designationId the designation ID of this employee transfer
	 */
	public void setDesignationId(long designationId);

	/**
	 * Returns the employee ID of this employee transfer.
	 *
	 * @return the employee ID of this employee transfer
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee transfer.
	 *
	 * @param employeeId the employee ID of this employee transfer
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the from organization ID of this employee transfer.
	 *
	 * @return the from organization ID of this employee transfer
	 */
	public long getFromOrganizationId();

	/**
	 * Sets the from organization ID of this employee transfer.
	 *
	 * @param fromOrganizationId the from organization ID of this employee transfer
	 */
	public void setFromOrganizationId(long fromOrganizationId);

	/**
	 * Returns the grade ID of this employee transfer.
	 *
	 * @return the grade ID of this employee transfer
	 */
	public long getGradeId();

	/**
	 * Sets the grade ID of this employee transfer.
	 *
	 * @param gradeId the grade ID of this employee transfer
	 */
	public void setGradeId(long gradeId);

	/**
	 * Returns the grade mode ID of this employee transfer.
	 *
	 * @return the grade mode ID of this employee transfer
	 */
	public long getGradeModeId();

	/**
	 * Sets the grade mode ID of this employee transfer.
	 *
	 * @param gradeModeId the grade mode ID of this employee transfer
	 */
	public void setGradeModeId(long gradeModeId);

	/**
	 * Returns the to organization ID of this employee transfer.
	 *
	 * @return the to organization ID of this employee transfer
	 */
	public long getToOrganizationId();

	/**
	 * Sets the to organization ID of this employee transfer.
	 *
	 * @param toOrganizationId the to organization ID of this employee transfer
	 */
	public void setToOrganizationId(long toOrganizationId);

	/**
	 * Returns the transfer letter ID of this employee transfer.
	 *
	 * @return the transfer letter ID of this employee transfer
	 */
	public long getTransferLetterId();

	/**
	 * Sets the transfer letter ID of this employee transfer.
	 *
	 * @param transferLetterId the transfer letter ID of this employee transfer
	 */
	public void setTransferLetterId(long transferLetterId);

	/**
	 * Returns the status of this employee transfer.
	 *
	 * @return the status of this employee transfer
	 */
	public int getStatus();

	/**
	 * Sets the status of this employee transfer.
	 *
	 * @param status the status of this employee transfer
	 */
	public void setStatus(int status);

}