/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeEmail service. Represents a row in the &quot;pis_EmployeeEmail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.EmployeeEmailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.EmployeeEmailImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeEmail
 * @generated
 */
@ProviderType
public interface EmployeeEmailModel
	extends BaseModel<EmployeeEmail>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee email model instance should use the {@link EmployeeEmail} interface instead.
	 */

	/**
	 * Returns the primary key of this employee email.
	 *
	 * @return the primary key of this employee email
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee email.
	 *
	 * @param primaryKey the primary key of this employee email
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee email ID of this employee email.
	 *
	 * @return the employee email ID of this employee email
	 */
	public long getEmployeeEmailId();

	/**
	 * Sets the employee email ID of this employee email.
	 *
	 * @param employeeEmailId the employee email ID of this employee email
	 */
	public void setEmployeeEmailId(long employeeEmailId);

	/**
	 * Returns the group ID of this employee email.
	 *
	 * @return the group ID of this employee email
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee email.
	 *
	 * @param groupId the group ID of this employee email
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee email.
	 *
	 * @return the company ID of this employee email
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee email.
	 *
	 * @param companyId the company ID of this employee email
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee email.
	 *
	 * @return the user ID of this employee email
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee email.
	 *
	 * @param userId the user ID of this employee email
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee email.
	 *
	 * @return the user uuid of this employee email
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee email.
	 *
	 * @param userUuid the user uuid of this employee email
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee email.
	 *
	 * @return the user name of this employee email
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee email.
	 *
	 * @param userName the user name of this employee email
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee email.
	 *
	 * @return the create date of this employee email
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee email.
	 *
	 * @param createDate the create date of this employee email
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee email.
	 *
	 * @return the modified date of this employee email
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee email.
	 *
	 * @param modifiedDate the modified date of this employee email
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee ID of this employee email.
	 *
	 * @return the employee ID of this employee email
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee email.
	 *
	 * @param employeeId the employee ID of this employee email
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the email address of this employee email.
	 *
	 * @return the email address of this employee email
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this employee email.
	 *
	 * @param emailAddress the email address of this employee email
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the email address type of this employee email.
	 *
	 * @return the email address type of this employee email
	 */
	@AutoEscape
	public String getEmailAddressType();

	/**
	 * Sets the email address type of this employee email.
	 *
	 * @param emailAddressType the email address type of this employee email
	 */
	public void setEmailAddressType(String emailAddressType);

	/**
	 * Returns the active of this employee email.
	 *
	 * @return the active of this employee email
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this employee email is active.
	 *
	 * @return <code>true</code> if this employee email is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this employee email is active.
	 *
	 * @param active the active of this employee email
	 */
	public void setActive(boolean active);

}