/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeDelegation service. Represents a row in the &quot;pis_EmployeeDelegation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.EmployeeDelegationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.EmployeeDelegationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDelegation
 * @generated
 */
@ProviderType
public interface EmployeeDelegationModel
	extends BaseModel<EmployeeDelegation>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee delegation model instance should use the {@link EmployeeDelegation} interface instead.
	 */

	/**
	 * Returns the primary key of this employee delegation.
	 *
	 * @return the primary key of this employee delegation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee delegation.
	 *
	 * @param primaryKey the primary key of this employee delegation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee delegation ID of this employee delegation.
	 *
	 * @return the employee delegation ID of this employee delegation
	 */
	public long getEmployeeDelegationId();

	/**
	 * Sets the employee delegation ID of this employee delegation.
	 *
	 * @param employeeDelegationId the employee delegation ID of this employee delegation
	 */
	public void setEmployeeDelegationId(long employeeDelegationId);

	/**
	 * Returns the group ID of this employee delegation.
	 *
	 * @return the group ID of this employee delegation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee delegation.
	 *
	 * @param groupId the group ID of this employee delegation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee delegation.
	 *
	 * @return the company ID of this employee delegation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee delegation.
	 *
	 * @param companyId the company ID of this employee delegation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee delegation.
	 *
	 * @return the user ID of this employee delegation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee delegation.
	 *
	 * @param userId the user ID of this employee delegation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee delegation.
	 *
	 * @return the user uuid of this employee delegation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee delegation.
	 *
	 * @param userUuid the user uuid of this employee delegation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee delegation.
	 *
	 * @return the user name of this employee delegation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee delegation.
	 *
	 * @param userName the user name of this employee delegation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee delegation.
	 *
	 * @return the create date of this employee delegation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee delegation.
	 *
	 * @param createDate the create date of this employee delegation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee delegation.
	 *
	 * @return the modified date of this employee delegation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee delegation.
	 *
	 * @param modifiedDate the modified date of this employee delegation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the delegation type of this employee delegation.
	 *
	 * @return the delegation type of this employee delegation
	 */
	public long getDelegationType();

	/**
	 * Sets the delegation type of this employee delegation.
	 *
	 * @param delegationType the delegation type of this employee delegation
	 */
	public void setDelegationType(long delegationType);

	/**
	 * Returns the delegated employee ID of this employee delegation.
	 *
	 * @return the delegated employee ID of this employee delegation
	 */
	public long getDelegatedEmployeeId();

	/**
	 * Sets the delegated employee ID of this employee delegation.
	 *
	 * @param delegatedEmployeeId the delegated employee ID of this employee delegation
	 */
	public void setDelegatedEmployeeId(long delegatedEmployeeId);

	/**
	 * Returns the employee ID of this employee delegation.
	 *
	 * @return the employee ID of this employee delegation
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee delegation.
	 *
	 * @param employeeId the employee ID of this employee delegation
	 */
	public void setEmployeeId(long employeeId);

}