/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeePastExperience service. Represents a row in the &quot;pis_EmployeePastExperience&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.EmployeePastExperienceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.EmployeePastExperienceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeePastExperience
 * @generated
 */
@ProviderType
public interface EmployeePastExperienceModel
	extends BaseModel<EmployeePastExperience>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee past experience model instance should use the {@link EmployeePastExperience} interface instead.
	 */

	/**
	 * Returns the primary key of this employee past experience.
	 *
	 * @return the primary key of this employee past experience
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee past experience.
	 *
	 * @param primaryKey the primary key of this employee past experience
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee past experience ID of this employee past experience.
	 *
	 * @return the employee past experience ID of this employee past experience
	 */
	public long getEmployeePastExperienceId();

	/**
	 * Sets the employee past experience ID of this employee past experience.
	 *
	 * @param employeePastExperienceId the employee past experience ID of this employee past experience
	 */
	public void setEmployeePastExperienceId(long employeePastExperienceId);

	/**
	 * Returns the group ID of this employee past experience.
	 *
	 * @return the group ID of this employee past experience
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee past experience.
	 *
	 * @param groupId the group ID of this employee past experience
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee past experience.
	 *
	 * @return the company ID of this employee past experience
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee past experience.
	 *
	 * @param companyId the company ID of this employee past experience
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee past experience.
	 *
	 * @return the user ID of this employee past experience
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee past experience.
	 *
	 * @param userId the user ID of this employee past experience
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee past experience.
	 *
	 * @return the user uuid of this employee past experience
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee past experience.
	 *
	 * @param userUuid the user uuid of this employee past experience
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee past experience.
	 *
	 * @return the user name of this employee past experience
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee past experience.
	 *
	 * @param userName the user name of this employee past experience
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee past experience.
	 *
	 * @return the create date of this employee past experience
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee past experience.
	 *
	 * @param createDate the create date of this employee past experience
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee past experience.
	 *
	 * @return the modified date of this employee past experience
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee past experience.
	 *
	 * @param modifiedDate the modified date of this employee past experience
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this employee past experience.
	 *
	 * @return the active of this employee past experience
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this employee past experience is active.
	 *
	 * @return <code>true</code> if this employee past experience is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this employee past experience is active.
	 *
	 * @param active the active of this employee past experience
	 */
	public void setActive(boolean active);

	/**
	 * Returns the from date of this employee past experience.
	 *
	 * @return the from date of this employee past experience
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this employee past experience.
	 *
	 * @param fromDate the from date of this employee past experience
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this employee past experience.
	 *
	 * @return the to date of this employee past experience
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this employee past experience.
	 *
	 * @param toDate the to date of this employee past experience
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the organization of this employee past experience.
	 *
	 * @return the organization of this employee past experience
	 */
	@AutoEscape
	public String getOrganization();

	/**
	 * Sets the organization of this employee past experience.
	 *
	 * @param organization the organization of this employee past experience
	 */
	public void setOrganization(String organization);

	/**
	 * Returns the employee ID of this employee past experience.
	 *
	 * @return the employee ID of this employee past experience
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee past experience.
	 *
	 * @param employeeId the employee ID of this employee past experience
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the experience letter ID of this employee past experience.
	 *
	 * @return the experience letter ID of this employee past experience
	 */
	public long getExperienceLetterId();

	/**
	 * Sets the experience letter ID of this employee past experience.
	 *
	 * @param experienceLetterId the experience letter ID of this employee past experience
	 */
	public void setExperienceLetterId(long experienceLetterId);

	/**
	 * Returns the work area ID of this employee past experience.
	 *
	 * @return the work area ID of this employee past experience
	 */
	public long getWorkAreaId();

	/**
	 * Sets the work area ID of this employee past experience.
	 *
	 * @param workAreaId the work area ID of this employee past experience
	 */
	public void setWorkAreaId(long workAreaId);

	/**
	 * Returns the designation of this employee past experience.
	 *
	 * @return the designation of this employee past experience
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this employee past experience.
	 *
	 * @param designation the designation of this employee past experience
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the joining process ID of this employee past experience.
	 *
	 * @return the joining process ID of this employee past experience
	 */
	public long getJoiningProcessId();

	/**
	 * Sets the joining process ID of this employee past experience.
	 *
	 * @param joiningProcessId the joining process ID of this employee past experience
	 */
	public void setJoiningProcessId(long joiningProcessId);

	/**
	 * Returns the ex service man of this employee past experience.
	 *
	 * @return the ex service man of this employee past experience
	 */
	public boolean getExServiceMan();

	/**
	 * Returns <code>true</code> if this employee past experience is ex service man.
	 *
	 * @return <code>true</code> if this employee past experience is ex service man; <code>false</code> otherwise
	 */
	public boolean isExServiceMan();

	/**
	 * Sets whether this employee past experience is ex service man.
	 *
	 * @param exServiceMan the ex service man of this employee past experience
	 */
	public void setExServiceMan(boolean exServiceMan);

	/**
	 * Returns the status of this employee past experience.
	 *
	 * @return the status of this employee past experience
	 */
	public int getStatus();

	/**
	 * Sets the status of this employee past experience.
	 *
	 * @param status the status of this employee past experience
	 */
	public void setStatus(int status);

}