/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeDsc service. Represents a row in the &quot;pis_EmployeeDsc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.EmployeeDscModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.EmployeeDscImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDsc
 * @generated
 */
@ProviderType
public interface EmployeeDscModel
	extends BaseModel<EmployeeDsc>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee dsc model instance should use the {@link EmployeeDsc} interface instead.
	 */

	/**
	 * Returns the primary key of this employee dsc.
	 *
	 * @return the primary key of this employee dsc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee dsc.
	 *
	 * @param primaryKey the primary key of this employee dsc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee dsc ID of this employee dsc.
	 *
	 * @return the employee dsc ID of this employee dsc
	 */
	public long getEmployeeDscId();

	/**
	 * Sets the employee dsc ID of this employee dsc.
	 *
	 * @param employeeDscId the employee dsc ID of this employee dsc
	 */
	public void setEmployeeDscId(long employeeDscId);

	/**
	 * Returns the group ID of this employee dsc.
	 *
	 * @return the group ID of this employee dsc
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee dsc.
	 *
	 * @param groupId the group ID of this employee dsc
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee dsc.
	 *
	 * @return the company ID of this employee dsc
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee dsc.
	 *
	 * @param companyId the company ID of this employee dsc
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee dsc.
	 *
	 * @return the user ID of this employee dsc
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee dsc.
	 *
	 * @param userId the user ID of this employee dsc
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee dsc.
	 *
	 * @return the user uuid of this employee dsc
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee dsc.
	 *
	 * @param userUuid the user uuid of this employee dsc
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee dsc.
	 *
	 * @return the user name of this employee dsc
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee dsc.
	 *
	 * @param userName the user name of this employee dsc
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee dsc.
	 *
	 * @return the create date of this employee dsc
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee dsc.
	 *
	 * @param createDate the create date of this employee dsc
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee dsc.
	 *
	 * @return the modified date of this employee dsc
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee dsc.
	 *
	 * @param modifiedDate the modified date of this employee dsc
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee ID of this employee dsc.
	 *
	 * @return the employee ID of this employee dsc
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee dsc.
	 *
	 * @param employeeId the employee ID of this employee dsc
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the cid of this employee dsc.
	 *
	 * @return the cid of this employee dsc
	 */
	@AutoEscape
	public String getCid();

	/**
	 * Sets the cid of this employee dsc.
	 *
	 * @param cid the cid of this employee dsc
	 */
	public void setCid(String cid);

	/**
	 * Returns the details of this employee dsc.
	 *
	 * @return the details of this employee dsc
	 */
	@AutoEscape
	public String getDetails();

	/**
	 * Sets the details of this employee dsc.
	 *
	 * @param details the details of this employee dsc
	 */
	public void setDetails(String details);

	/**
	 * Returns the ofb dsc reissue date of this employee dsc.
	 *
	 * @return the ofb dsc reissue date of this employee dsc
	 */
	public Date getOfbDSCReissueDate();

	/**
	 * Sets the ofb dsc reissue date of this employee dsc.
	 *
	 * @param ofbDSCReissueDate the ofb dsc reissue date of this employee dsc
	 */
	public void setOfbDSCReissueDate(Date ofbDSCReissueDate);

	/**
	 * Returns the ofb dsc revocation date of this employee dsc.
	 *
	 * @return the ofb dsc revocation date of this employee dsc
	 */
	public Date getOfbDSCRevocationDate();

	/**
	 * Sets the ofb dsc revocation date of this employee dsc.
	 *
	 * @param ofbDSCRevocationDate the ofb dsc revocation date of this employee dsc
	 */
	public void setOfbDSCRevocationDate(Date ofbDSCRevocationDate);

	/**
	 * Returns the ofb dsc revocation status of this employee dsc.
	 *
	 * @return the ofb dsc revocation status of this employee dsc
	 */
	public boolean getOfbDSCRevocationStatus();

	/**
	 * Returns <code>true</code> if this employee dsc is ofb dsc revocation status.
	 *
	 * @return <code>true</code> if this employee dsc is ofb dsc revocation status; <code>false</code> otherwise
	 */
	public boolean isOfbDSCRevocationStatus();

	/**
	 * Sets whether this employee dsc is ofb dsc revocation status.
	 *
	 * @param ofbDSCRevocationStatus the ofb dsc revocation status of this employee dsc
	 */
	public void setOfbDSCRevocationStatus(boolean ofbDSCRevocationStatus);

	/**
	 * Returns the ofb dsc reissue status of this employee dsc.
	 *
	 * @return the ofb dsc reissue status of this employee dsc
	 */
	public boolean getOfbDSCReissueStatus();

	/**
	 * Returns <code>true</code> if this employee dsc is ofb dsc reissue status.
	 *
	 * @return <code>true</code> if this employee dsc is ofb dsc reissue status; <code>false</code> otherwise
	 */
	public boolean isOfbDSCReissueStatus();

	/**
	 * Sets whether this employee dsc is ofb dsc reissue status.
	 *
	 * @param ofbDSCReissueStatus the ofb dsc reissue status of this employee dsc
	 */
	public void setOfbDSCReissueStatus(boolean ofbDSCReissueStatus);

}