/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeWorkstation service. Represents a row in the &quot;pis_EmployeeWorkstation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.EmployeeWorkstationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.EmployeeWorkstationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeWorkstation
 * @generated
 */
@ProviderType
public interface EmployeeWorkstationModel
	extends BaseModel<EmployeeWorkstation>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee workstation model instance should use the {@link EmployeeWorkstation} interface instead.
	 */

	/**
	 * Returns the primary key of this employee workstation.
	 *
	 * @return the primary key of this employee workstation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee workstation.
	 *
	 * @param primaryKey the primary key of this employee workstation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee workstation ID of this employee workstation.
	 *
	 * @return the employee workstation ID of this employee workstation
	 */
	public long getEmployeeWorkstationId();

	/**
	 * Sets the employee workstation ID of this employee workstation.
	 *
	 * @param employeeWorkstationId the employee workstation ID of this employee workstation
	 */
	public void setEmployeeWorkstationId(long employeeWorkstationId);

	/**
	 * Returns the group ID of this employee workstation.
	 *
	 * @return the group ID of this employee workstation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee workstation.
	 *
	 * @param groupId the group ID of this employee workstation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee workstation.
	 *
	 * @return the company ID of this employee workstation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee workstation.
	 *
	 * @param companyId the company ID of this employee workstation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee workstation.
	 *
	 * @return the user ID of this employee workstation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee workstation.
	 *
	 * @param userId the user ID of this employee workstation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee workstation.
	 *
	 * @return the user uuid of this employee workstation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee workstation.
	 *
	 * @param userUuid the user uuid of this employee workstation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee workstation.
	 *
	 * @return the user name of this employee workstation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee workstation.
	 *
	 * @param userName the user name of this employee workstation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee workstation.
	 *
	 * @return the create date of this employee workstation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee workstation.
	 *
	 * @param createDate the create date of this employee workstation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee workstation.
	 *
	 * @return the modified date of this employee workstation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee workstation.
	 *
	 * @param modifiedDate the modified date of this employee workstation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this employee workstation.
	 *
	 * @return the active of this employee workstation
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this employee workstation is active.
	 *
	 * @return <code>true</code> if this employee workstation is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this employee workstation is active.
	 *
	 * @param active the active of this employee workstation
	 */
	public void setActive(boolean active);

	/**
	 * Returns the from month of this employee workstation.
	 *
	 * @return the from month of this employee workstation
	 */
	public Date getFromMonth();

	/**
	 * Sets the from month of this employee workstation.
	 *
	 * @param fromMonth the from month of this employee workstation
	 */
	public void setFromMonth(Date fromMonth);

	/**
	 * Returns the to month of this employee workstation.
	 *
	 * @return the to month of this employee workstation
	 */
	public Date getToMonth();

	/**
	 * Sets the to month of this employee workstation.
	 *
	 * @param toMonth the to month of this employee workstation
	 */
	public void setToMonth(Date toMonth);

	/**
	 * Returns the employee ID of this employee workstation.
	 *
	 * @return the employee ID of this employee workstation
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee workstation.
	 *
	 * @param employeeId the employee ID of this employee workstation
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the work station ID of this employee workstation.
	 *
	 * @return the work station ID of this employee workstation
	 */
	public long getWorkStationId();

	/**
	 * Sets the work station ID of this employee workstation.
	 *
	 * @param workStationId the work station ID of this employee workstation
	 */
	public void setWorkStationId(long workStationId);

	/**
	 * Returns the desk no of this employee workstation.
	 *
	 * @return the desk no of this employee workstation
	 */
	@AutoEscape
	public String getDeskNo();

	/**
	 * Sets the desk no of this employee workstation.
	 *
	 * @param deskNo the desk no of this employee workstation
	 */
	public void setDeskNo(String deskNo);

	/**
	 * Returns the extn no of this employee workstation.
	 *
	 * @return the extn no of this employee workstation
	 */
	@AutoEscape
	public String getExtnNo();

	/**
	 * Sets the extn no of this employee workstation.
	 *
	 * @param extnNo the extn no of this employee workstation
	 */
	public void setExtnNo(String extnNo);

	/**
	 * Returns the direct no of this employee workstation.
	 *
	 * @return the direct no of this employee workstation
	 */
	@AutoEscape
	public String getDirectNo();

	/**
	 * Sets the direct no of this employee workstation.
	 *
	 * @param directNo the direct no of this employee workstation
	 */
	public void setDirectNo(String directNo);

	/**
	 * Returns the phone no of this employee workstation.
	 *
	 * @return the phone no of this employee workstation
	 */
	@AutoEscape
	public String getPhoneNo();

	/**
	 * Sets the phone no of this employee workstation.
	 *
	 * @param phoneNo the phone no of this employee workstation
	 */
	public void setPhoneNo(String phoneNo);

	/**
	 * Returns the cabin no of this employee workstation.
	 *
	 * @return the cabin no of this employee workstation
	 */
	@AutoEscape
	public String getCabinNo();

	/**
	 * Sets the cabin no of this employee workstation.
	 *
	 * @param cabinNo the cabin no of this employee workstation
	 */
	public void setCabinNo(String cabinNo);

	/**
	 * Returns the floor no of this employee workstation.
	 *
	 * @return the floor no of this employee workstation
	 */
	@AutoEscape
	public String getFloorNo();

	/**
	 * Sets the floor no of this employee workstation.
	 *
	 * @param floorNo the floor no of this employee workstation
	 */
	public void setFloorNo(String floorNo);

	/**
	 * Returns the status of this employee workstation.
	 *
	 * @return the status of this employee workstation
	 */
	public int getStatus();

	/**
	 * Sets the status of this employee workstation.
	 *
	 * @param status the status of this employee workstation
	 */
	public void setStatus(int status);

}