/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeePromotionRequest service. Represents a row in the &quot;pis_EmployeePromotionRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.EmployeePromotionRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.EmployeePromotionRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeePromotionRequest
 * @generated
 */
@ProviderType
public interface EmployeePromotionRequestModel
	extends BaseModel<EmployeePromotionRequest>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee promotion request model instance should use the {@link EmployeePromotionRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this employee promotion request.
	 *
	 * @return the primary key of this employee promotion request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee promotion request.
	 *
	 * @param primaryKey the primary key of this employee promotion request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee promotion request.
	 *
	 * @return the uuid of this employee promotion request
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employee promotion request.
	 *
	 * @param uuid the uuid of this employee promotion request
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the employee promotion request ID of this employee promotion request.
	 *
	 * @return the employee promotion request ID of this employee promotion request
	 */
	public long getEmployeePromotionRequestId();

	/**
	 * Sets the employee promotion request ID of this employee promotion request.
	 *
	 * @param employeePromotionRequestId the employee promotion request ID of this employee promotion request
	 */
	public void setEmployeePromotionRequestId(long employeePromotionRequestId);

	/**
	 * Returns the group ID of this employee promotion request.
	 *
	 * @return the group ID of this employee promotion request
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee promotion request.
	 *
	 * @param groupId the group ID of this employee promotion request
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee promotion request.
	 *
	 * @return the company ID of this employee promotion request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee promotion request.
	 *
	 * @param companyId the company ID of this employee promotion request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee promotion request.
	 *
	 * @return the user ID of this employee promotion request
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee promotion request.
	 *
	 * @param userId the user ID of this employee promotion request
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee promotion request.
	 *
	 * @return the user uuid of this employee promotion request
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee promotion request.
	 *
	 * @param userUuid the user uuid of this employee promotion request
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee promotion request.
	 *
	 * @return the user name of this employee promotion request
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee promotion request.
	 *
	 * @param userName the user name of this employee promotion request
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee promotion request.
	 *
	 * @return the create date of this employee promotion request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee promotion request.
	 *
	 * @param createDate the create date of this employee promotion request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee promotion request.
	 *
	 * @return the modified date of this employee promotion request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee promotion request.
	 *
	 * @param modifiedDate the modified date of this employee promotion request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee ID of this employee promotion request.
	 *
	 * @return the employee ID of this employee promotion request
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee promotion request.
	 *
	 * @param employeeId the employee ID of this employee promotion request
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the designation ID of this employee promotion request.
	 *
	 * @return the designation ID of this employee promotion request
	 */
	public Long getDesignationId();

	/**
	 * Sets the designation ID of this employee promotion request.
	 *
	 * @param designationId the designation ID of this employee promotion request
	 */
	public void setDesignationId(Long designationId);

	/**
	 * Returns the promotion mode ID of this employee promotion request.
	 *
	 * @return the promotion mode ID of this employee promotion request
	 */
	public Long getPromotionModeId();

	/**
	 * Sets the promotion mode ID of this employee promotion request.
	 *
	 * @param promotionModeId the promotion mode ID of this employee promotion request
	 */
	public void setPromotionModeId(Long promotionModeId);

	/**
	 * Returns the promotion date of this employee promotion request.
	 *
	 * @return the promotion date of this employee promotion request
	 */
	public Date getPromotionDate();

	/**
	 * Sets the promotion date of this employee promotion request.
	 *
	 * @param promotionDate the promotion date of this employee promotion request
	 */
	public void setPromotionDate(Date promotionDate);

	/**
	 * Returns the office order no of this employee promotion request.
	 *
	 * @return the office order no of this employee promotion request
	 */
	@AutoEscape
	public String getOfficeOrderNo();

	/**
	 * Sets the office order no of this employee promotion request.
	 *
	 * @param officeOrderNo the office order no of this employee promotion request
	 */
	public void setOfficeOrderNo(String officeOrderNo);

	/**
	 * Returns the process file ID of this employee promotion request.
	 *
	 * @return the process file ID of this employee promotion request
	 */
	public long getProcessFileId();

	/**
	 * Sets the process file ID of this employee promotion request.
	 *
	 * @param processFileId the process file ID of this employee promotion request
	 */
	public void setProcessFileId(long processFileId);

	/**
	 * Returns the process file no of this employee promotion request.
	 *
	 * @return the process file no of this employee promotion request
	 */
	@AutoEscape
	public String getProcessFileNo();

	/**
	 * Sets the process file no of this employee promotion request.
	 *
	 * @param processFileNo the process file no of this employee promotion request
	 */
	public void setProcessFileNo(String processFileNo);

}