/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ServiceRequest service. Represents a row in the &quot;pis_ServiceRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.pis.liferay.model.impl.ServiceRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.pis.liferay.model.impl.ServiceRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServiceRequest
 * @generated
 */
@ProviderType
public interface ServiceRequestModel
	extends BaseModel<ServiceRequest>, GroupedModel, ShardedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service request model instance should use the {@link ServiceRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this service request.
	 *
	 * @return the primary key of this service request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service request.
	 *
	 * @param primaryKey the primary key of this service request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the service request ID of this service request.
	 *
	 * @return the service request ID of this service request
	 */
	public long getServiceRequestId();

	/**
	 * Sets the service request ID of this service request.
	 *
	 * @param serviceRequestId the service request ID of this service request
	 */
	public void setServiceRequestId(long serviceRequestId);

	/**
	 * Returns the group ID of this service request.
	 *
	 * @return the group ID of this service request
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this service request.
	 *
	 * @param groupId the group ID of this service request
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this service request.
	 *
	 * @return the company ID of this service request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this service request.
	 *
	 * @param companyId the company ID of this service request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this service request.
	 *
	 * @return the user ID of this service request
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this service request.
	 *
	 * @param userId the user ID of this service request
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this service request.
	 *
	 * @return the user uuid of this service request
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this service request.
	 *
	 * @param userUuid the user uuid of this service request
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this service request.
	 *
	 * @return the user name of this service request
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this service request.
	 *
	 * @param userName the user name of this service request
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this service request.
	 *
	 * @return the create date of this service request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this service request.
	 *
	 * @param createDate the create date of this service request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this service request.
	 *
	 * @return the modified date of this service request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this service request.
	 *
	 * @param modifiedDate the modified date of this service request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this service request.
	 *
	 * @return the active of this service request
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this service request is active.
	 *
	 * @return <code>true</code> if this service request is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this service request is active.
	 *
	 * @param active the active of this service request
	 */
	public void setActive(boolean active);

	/**
	 * Returns the service request type ID of this service request.
	 *
	 * @return the service request type ID of this service request
	 */
	public long getServiceRequestTypeId();

	/**
	 * Sets the service request type ID of this service request.
	 *
	 * @param serviceRequestTypeId the service request type ID of this service request
	 */
	public void setServiceRequestTypeId(long serviceRequestTypeId);

	/**
	 * Returns the subject of this service request.
	 *
	 * @return the subject of this service request
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this service request.
	 *
	 * @param subject the subject of this service request
	 */
	public void setSubject(String subject);

	/**
	 * Returns the description of this service request.
	 *
	 * @return the description of this service request
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this service request.
	 *
	 * @param description the description of this service request
	 */
	public void setDescription(String description);

	/**
	 * Returns the employee ID of this service request.
	 *
	 * @return the employee ID of this service request
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this service request.
	 *
	 * @param employeeId the employee ID of this service request
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the document proof ID of this service request.
	 *
	 * @return the document proof ID of this service request
	 */
	public long getDocumentProofId();

	/**
	 * Sets the document proof ID of this service request.
	 *
	 * @param documentProofId the document proof ID of this service request
	 */
	public void setDocumentProofId(long documentProofId);

	/**
	 * Returns the organization ID of this service request.
	 *
	 * @return the organization ID of this service request
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this service request.
	 *
	 * @param organizationId the organization ID of this service request
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the joining process ID of this service request.
	 *
	 * @return the joining process ID of this service request
	 */
	public Long getJoiningProcessId();

	/**
	 * Sets the joining process ID of this service request.
	 *
	 * @param joiningProcessId the joining process ID of this service request
	 */
	public void setJoiningProcessId(Long joiningProcessId);

	/**
	 * Returns the status of this service request.
	 *
	 * @return the status of this service request
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this service request.
	 *
	 * @param status the status of this service request
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the deleted of this service request.
	 *
	 * @return the deleted of this service request
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this service request is deleted.
	 *
	 * @return <code>true</code> if this service request is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this service request is deleted.
	 *
	 * @param deleted the deleted of this service request
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the status by user ID of this service request.
	 *
	 * @return the status by user ID of this service request
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this service request.
	 *
	 * @param statusByUserId the status by user ID of this service request
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this service request.
	 *
	 * @return the status by user uuid of this service request
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this service request.
	 *
	 * @param statusByUserUuid the status by user uuid of this service request
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this service request.
	 *
	 * @return the status by user name of this service request
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this service request.
	 *
	 * @param statusByUserName the status by user name of this service request
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this service request.
	 *
	 * @return the status date of this service request
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this service request.
	 *
	 * @param statusDate the status date of this service request
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the state of this service request.
	 *
	 * @return the state of this service request
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this service request.
	 *
	 * @param state the state of this service request
	 */
	public void setState(String state);

	/**
	 * Returns the comments of this service request.
	 *
	 * @return the comments of this service request
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this service request.
	 *
	 * @param comments the comments of this service request
	 */
	public void setComments(String comments);

	/**
	 * Returns <code>true</code> if this service request is approved.
	 *
	 * @return <code>true</code> if this service request is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this service request is denied.
	 *
	 * @return <code>true</code> if this service request is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this service request is a draft.
	 *
	 * @return <code>true</code> if this service request is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this service request is expired.
	 *
	 * @return <code>true</code> if this service request is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this service request is inactive.
	 *
	 * @return <code>true</code> if this service request is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this service request is incomplete.
	 *
	 * @return <code>true</code> if this service request is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this service request is pending.
	 *
	 * @return <code>true</code> if this service request is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this service request is scheduled.
	 *
	 * @return <code>true</code> if this service request is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}