/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.ayudh.audit.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import net.ayudh.audit.model.AuditEventArchive;
import net.ayudh.audit.service.AuditEventArchiveLocalService;
import net.ayudh.audit.service.persistence.AuditEventArchivePersistence;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the audit event archive local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link net.ayudh.audit.service.impl.AuditEventArchiveLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see net.ayudh.audit.service.impl.AuditEventArchiveLocalServiceImpl
 * @generated
 */
public abstract class AuditEventArchiveLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, AuditEventArchiveLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AuditEventArchiveLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>net.ayudh.audit.service.AuditEventArchiveLocalServiceUtil</code>.
	 */

	/**
	 * Adds the audit event archive to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditEventArchiveLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditEventArchive the audit event archive
	 * @return the audit event archive that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AuditEventArchive addAuditEventArchive(
		AuditEventArchive auditEventArchive) {

		auditEventArchive.setNew(true);

		return auditEventArchivePersistence.update(auditEventArchive);
	}

	/**
	 * Creates a new audit event archive with the primary key. Does not add the audit event archive to the database.
	 *
	 * @param auditEventArchiveId the primary key for the new audit event archive
	 * @return the new audit event archive
	 */
	@Override
	@Transactional(enabled = false)
	public AuditEventArchive createAuditEventArchive(long auditEventArchiveId) {
		return auditEventArchivePersistence.create(auditEventArchiveId);
	}

	/**
	 * Deletes the audit event archive with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditEventArchiveLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditEventArchiveId the primary key of the audit event archive
	 * @return the audit event archive that was removed
	 * @throws PortalException if a audit event archive with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AuditEventArchive deleteAuditEventArchive(long auditEventArchiveId)
		throws PortalException {

		return auditEventArchivePersistence.remove(auditEventArchiveId);
	}

	/**
	 * Deletes the audit event archive from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditEventArchiveLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditEventArchive the audit event archive
	 * @return the audit event archive that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AuditEventArchive deleteAuditEventArchive(
		AuditEventArchive auditEventArchive) {

		return auditEventArchivePersistence.remove(auditEventArchive);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AuditEventArchive.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return auditEventArchivePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>net.ayudh.audit.model.impl.AuditEventArchiveModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return auditEventArchivePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>net.ayudh.audit.model.impl.AuditEventArchiveModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return auditEventArchivePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return auditEventArchivePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return auditEventArchivePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AuditEventArchive fetchAuditEventArchive(long auditEventArchiveId) {
		return auditEventArchivePersistence.fetchByPrimaryKey(
			auditEventArchiveId);
	}

	/**
	 * Returns the audit event archive with the primary key.
	 *
	 * @param auditEventArchiveId the primary key of the audit event archive
	 * @return the audit event archive
	 * @throws PortalException if a audit event archive with the primary key could not be found
	 */
	@Override
	public AuditEventArchive getAuditEventArchive(long auditEventArchiveId)
		throws PortalException {

		return auditEventArchivePersistence.findByPrimaryKey(
			auditEventArchiveId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			auditEventArchiveLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AuditEventArchive.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditEventArchiveId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			auditEventArchiveLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AuditEventArchive.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"auditEventArchiveId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			auditEventArchiveLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AuditEventArchive.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditEventArchiveId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return auditEventArchivePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return auditEventArchiveLocalService.deleteAuditEventArchive(
			(AuditEventArchive)persistedModel);
	}

	public BasePersistence<AuditEventArchive> getBasePersistence() {
		return auditEventArchivePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return auditEventArchivePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the audit event archives.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>net.ayudh.audit.model.impl.AuditEventArchiveModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of audit event archives
	 * @param end the upper bound of the range of audit event archives (not inclusive)
	 * @return the range of audit event archives
	 */
	@Override
	public List<AuditEventArchive> getAuditEventArchives(int start, int end) {
		return auditEventArchivePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of audit event archives.
	 *
	 * @return the number of audit event archives
	 */
	@Override
	public int getAuditEventArchivesCount() {
		return auditEventArchivePersistence.countAll();
	}

	/**
	 * Updates the audit event archive in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditEventArchiveLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditEventArchive the audit event archive
	 * @return the audit event archive that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AuditEventArchive updateAuditEventArchive(
		AuditEventArchive auditEventArchive) {

		return auditEventArchivePersistence.update(auditEventArchive);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AuditEventArchiveLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		auditEventArchiveLocalService = (AuditEventArchiveLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AuditEventArchiveLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AuditEventArchive.class;
	}

	protected String getModelClassName() {
		return AuditEventArchive.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				auditEventArchivePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected AuditEventArchiveLocalService auditEventArchiveLocalService;

	@Reference
	protected AuditEventArchivePersistence auditEventArchivePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}