/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.mdm.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Grade service. Represents a row in the &quot;mdm_Grade&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.mdm.liferay.model.impl.GradeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.mdm.liferay.model.impl.GradeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Grade
 * @generated
 */
@ProviderType
public interface GradeModel
	extends BaseModel<Grade>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a grade model instance should use the {@link Grade} interface instead.
	 */

	/**
	 * Returns the primary key of this grade.
	 *
	 * @return the primary key of this grade
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this grade.
	 *
	 * @param primaryKey the primary key of this grade
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the grade ID of this grade.
	 *
	 * @return the grade ID of this grade
	 */
	public long getGradeId();

	/**
	 * Sets the grade ID of this grade.
	 *
	 * @param gradeId the grade ID of this grade
	 */
	public void setGradeId(long gradeId);

	/**
	 * Returns the group ID of this grade.
	 *
	 * @return the group ID of this grade
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this grade.
	 *
	 * @param groupId the group ID of this grade
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this grade.
	 *
	 * @return the company ID of this grade
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this grade.
	 *
	 * @param companyId the company ID of this grade
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this grade.
	 *
	 * @return the user ID of this grade
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this grade.
	 *
	 * @param userId the user ID of this grade
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this grade.
	 *
	 * @return the user uuid of this grade
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this grade.
	 *
	 * @param userUuid the user uuid of this grade
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this grade.
	 *
	 * @return the user name of this grade
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this grade.
	 *
	 * @param userName the user name of this grade
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this grade.
	 *
	 * @return the create date of this grade
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this grade.
	 *
	 * @param createDate the create date of this grade
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this grade.
	 *
	 * @return the modified date of this grade
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this grade.
	 *
	 * @param modifiedDate the modified date of this grade
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this grade.
	 *
	 * @return the code of this grade
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this grade.
	 *
	 * @param code the code of this grade
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this grade.
	 *
	 * @return the name of this grade
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this grade.
	 *
	 * @param name the name of this grade
	 */
	public void setName(String name);

	/**
	 * Returns the description of this grade.
	 *
	 * @return the description of this grade
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this grade.
	 *
	 * @param description the description of this grade
	 */
	public void setDescription(String description);

	/**
	 * Returns the deleted of this grade.
	 *
	 * @return the deleted of this grade
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this grade is deleted.
	 *
	 * @return <code>true</code> if this grade is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this grade is deleted.
	 *
	 * @param deleted the deleted of this grade
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the status of this grade.
	 *
	 * @return the status of this grade
	 */
	public int getStatus();

	/**
	 * Sets the status of this grade.
	 *
	 * @param status the status of this grade
	 */
	public void setStatus(int status);

}