/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.mdm.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OrganizationPayStructure service. Represents a row in the &quot;mdm_OrganizationPayStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.mdm.liferay.model.impl.OrganizationPayStructureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.mdm.liferay.model.impl.OrganizationPayStructureImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OrganizationPayStructure
 * @generated
 */
@ProviderType
public interface OrganizationPayStructureModel
	extends BaseModel<OrganizationPayStructure>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a organization pay structure model instance should use the {@link OrganizationPayStructure} interface instead.
	 */

	/**
	 * Returns the primary key of this organization pay structure.
	 *
	 * @return the primary key of this organization pay structure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this organization pay structure.
	 *
	 * @param primaryKey the primary key of this organization pay structure
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the organization pay structure ID of this organization pay structure.
	 *
	 * @return the organization pay structure ID of this organization pay structure
	 */
	public long getOrganizationPayStructureId();

	/**
	 * Sets the organization pay structure ID of this organization pay structure.
	 *
	 * @param organizationPayStructureId the organization pay structure ID of this organization pay structure
	 */
	public void setOrganizationPayStructureId(long organizationPayStructureId);

	/**
	 * Returns the group ID of this organization pay structure.
	 *
	 * @return the group ID of this organization pay structure
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this organization pay structure.
	 *
	 * @param groupId the group ID of this organization pay structure
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this organization pay structure.
	 *
	 * @return the company ID of this organization pay structure
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this organization pay structure.
	 *
	 * @param companyId the company ID of this organization pay structure
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this organization pay structure.
	 *
	 * @return the user ID of this organization pay structure
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this organization pay structure.
	 *
	 * @param userId the user ID of this organization pay structure
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this organization pay structure.
	 *
	 * @return the user uuid of this organization pay structure
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this organization pay structure.
	 *
	 * @param userUuid the user uuid of this organization pay structure
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this organization pay structure.
	 *
	 * @return the user name of this organization pay structure
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this organization pay structure.
	 *
	 * @param userName the user name of this organization pay structure
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this organization pay structure.
	 *
	 * @return the create date of this organization pay structure
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this organization pay structure.
	 *
	 * @param createDate the create date of this organization pay structure
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this organization pay structure.
	 *
	 * @return the modified date of this organization pay structure
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this organization pay structure.
	 *
	 * @param modifiedDate the modified date of this organization pay structure
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this organization pay structure.
	 *
	 * @return the active of this organization pay structure
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this organization pay structure is active.
	 *
	 * @return <code>true</code> if this organization pay structure is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this organization pay structure is active.
	 *
	 * @param active the active of this organization pay structure
	 */
	public void setActive(boolean active);

	/**
	 * Returns the from date of this organization pay structure.
	 *
	 * @return the from date of this organization pay structure
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this organization pay structure.
	 *
	 * @param fromDate the from date of this organization pay structure
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this organization pay structure.
	 *
	 * @return the to date of this organization pay structure
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this organization pay structure.
	 *
	 * @param toDate the to date of this organization pay structure
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the level ID of this organization pay structure.
	 *
	 * @return the level ID of this organization pay structure
	 */
	public long getLevelId();

	/**
	 * Sets the level ID of this organization pay structure.
	 *
	 * @param levelId the level ID of this organization pay structure
	 */
	public void setLevelId(long levelId);

	/**
	 * Returns the organization ID of this organization pay structure.
	 *
	 * @return the organization ID of this organization pay structure
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this organization pay structure.
	 *
	 * @param organizationId the organization ID of this organization pay structure
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the structure ID of this organization pay structure.
	 *
	 * @return the structure ID of this organization pay structure
	 */
	public long getStructureId();

	/**
	 * Sets the structure ID of this organization pay structure.
	 *
	 * @param structureId the structure ID of this organization pay structure
	 */
	public void setStructureId(long structureId);

	/**
	 * Returns the deleted of this organization pay structure.
	 *
	 * @return the deleted of this organization pay structure
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this organization pay structure is deleted.
	 *
	 * @return <code>true</code> if this organization pay structure is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this organization pay structure is deleted.
	 *
	 * @param deleted the deleted of this organization pay structure
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the status of this organization pay structure.
	 *
	 * @return the status of this organization pay structure
	 */
	public int getStatus();

	/**
	 * Sets the status of this organization pay structure.
	 *
	 * @param status the status of this organization pay structure
	 */
	public void setStatus(int status);

}