/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.mdm.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PayComponent service. Represents a row in the &quot;mdm_PayComponent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.mdm.liferay.model.impl.PayComponentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.mdm.liferay.model.impl.PayComponentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PayComponent
 * @generated
 */
@ProviderType
public interface PayComponentModel
	extends BaseModel<PayComponent>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pay component model instance should use the {@link PayComponent} interface instead.
	 */

	/**
	 * Returns the primary key of this pay component.
	 *
	 * @return the primary key of this pay component
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pay component.
	 *
	 * @param primaryKey the primary key of this pay component
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pay component ID of this pay component.
	 *
	 * @return the pay component ID of this pay component
	 */
	public long getPayComponentId();

	/**
	 * Sets the pay component ID of this pay component.
	 *
	 * @param payComponentId the pay component ID of this pay component
	 */
	public void setPayComponentId(long payComponentId);

	/**
	 * Returns the group ID of this pay component.
	 *
	 * @return the group ID of this pay component
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pay component.
	 *
	 * @param groupId the group ID of this pay component
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pay component.
	 *
	 * @return the company ID of this pay component
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pay component.
	 *
	 * @param companyId the company ID of this pay component
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pay component.
	 *
	 * @return the user ID of this pay component
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pay component.
	 *
	 * @param userId the user ID of this pay component
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pay component.
	 *
	 * @return the user uuid of this pay component
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pay component.
	 *
	 * @param userUuid the user uuid of this pay component
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pay component.
	 *
	 * @return the user name of this pay component
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pay component.
	 *
	 * @param userName the user name of this pay component
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pay component.
	 *
	 * @return the create date of this pay component
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pay component.
	 *
	 * @param createDate the create date of this pay component
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pay component.
	 *
	 * @return the modified date of this pay component
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pay component.
	 *
	 * @param modifiedDate the modified date of this pay component
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this pay component.
	 *
	 * @return the active of this pay component
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this pay component is active.
	 *
	 * @return <code>true</code> if this pay component is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this pay component is active.
	 *
	 * @param active the active of this pay component
	 */
	public void setActive(boolean active);

	/**
	 * Returns the amount of this pay component.
	 *
	 * @return the amount of this pay component
	 */
	public float getAmount();

	/**
	 * Sets the amount of this pay component.
	 *
	 * @param amount the amount of this pay component
	 */
	public void setAmount(float amount);

	/**
	 * Returns the amount type of this pay component.
	 *
	 * @return the amount type of this pay component
	 */
	@AutoEscape
	public String getAmountType();

	/**
	 * Sets the amount type of this pay component.
	 *
	 * @param amountType the amount type of this pay component
	 */
	public void setAmountType(String amountType);

	/**
	 * Returns the from date of this pay component.
	 *
	 * @return the from date of this pay component
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this pay component.
	 *
	 * @param fromDate the from date of this pay component
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this pay component.
	 *
	 * @return the to date of this pay component
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this pay component.
	 *
	 * @param toDate the to date of this pay component
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the dependant ID of this pay component.
	 *
	 * @return the dependant ID of this pay component
	 */
	public long getDependantId();

	/**
	 * Sets the dependant ID of this pay component.
	 *
	 * @param dependantId the dependant ID of this pay component
	 */
	public void setDependantId(long dependantId);

	/**
	 * Returns the head ID of this pay component.
	 *
	 * @return the head ID of this pay component
	 */
	public long getHeadId();

	/**
	 * Sets the head ID of this pay component.
	 *
	 * @param headId the head ID of this pay component
	 */
	public void setHeadId(long headId);

	/**
	 * Returns the structure ID of this pay component.
	 *
	 * @return the structure ID of this pay component
	 */
	public long getStructureId();

	/**
	 * Sets the structure ID of this pay component.
	 *
	 * @param structureId the structure ID of this pay component
	 */
	public void setStructureId(long structureId);

	/**
	 * Returns the deleted of this pay component.
	 *
	 * @return the deleted of this pay component
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this pay component is deleted.
	 *
	 * @return <code>true</code> if this pay component is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this pay component is deleted.
	 *
	 * @param deleted the deleted of this pay component
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the status of this pay component.
	 *
	 * @return the status of this pay component
	 */
	public int getStatus();

	/**
	 * Sets the status of this pay component.
	 *
	 * @param status the status of this pay component
	 */
	public void setStatus(int status);

}