/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.mdm.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PayStructure service. Represents a row in the &quot;mdm_PayStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.mdm.liferay.model.impl.PayStructureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.mdm.liferay.model.impl.PayStructureImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PayStructure
 * @generated
 */
@ProviderType
public interface PayStructureModel
	extends BaseModel<PayStructure>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pay structure model instance should use the {@link PayStructure} interface instead.
	 */

	/**
	 * Returns the primary key of this pay structure.
	 *
	 * @return the primary key of this pay structure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pay structure.
	 *
	 * @param primaryKey the primary key of this pay structure
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pay structure ID of this pay structure.
	 *
	 * @return the pay structure ID of this pay structure
	 */
	public long getPayStructureId();

	/**
	 * Sets the pay structure ID of this pay structure.
	 *
	 * @param payStructureId the pay structure ID of this pay structure
	 */
	public void setPayStructureId(long payStructureId);

	/**
	 * Returns the group ID of this pay structure.
	 *
	 * @return the group ID of this pay structure
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pay structure.
	 *
	 * @param groupId the group ID of this pay structure
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pay structure.
	 *
	 * @return the company ID of this pay structure
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pay structure.
	 *
	 * @param companyId the company ID of this pay structure
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pay structure.
	 *
	 * @return the user ID of this pay structure
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pay structure.
	 *
	 * @param userId the user ID of this pay structure
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pay structure.
	 *
	 * @return the user uuid of this pay structure
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pay structure.
	 *
	 * @param userUuid the user uuid of this pay structure
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pay structure.
	 *
	 * @return the user name of this pay structure
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pay structure.
	 *
	 * @param userName the user name of this pay structure
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pay structure.
	 *
	 * @return the create date of this pay structure
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pay structure.
	 *
	 * @param createDate the create date of this pay structure
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pay structure.
	 *
	 * @return the modified date of this pay structure
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pay structure.
	 *
	 * @param modifiedDate the modified date of this pay structure
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this pay structure.
	 *
	 * @return the active of this pay structure
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this pay structure is active.
	 *
	 * @return <code>true</code> if this pay structure is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this pay structure is active.
	 *
	 * @param active the active of this pay structure
	 */
	public void setActive(boolean active);

	/**
	 * Returns the currency of this pay structure.
	 *
	 * @return the currency of this pay structure
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this pay structure.
	 *
	 * @param currency the currency of this pay structure
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the effective date of this pay structure.
	 *
	 * @return the effective date of this pay structure
	 */
	public Date getEffectiveDate();

	/**
	 * Sets the effective date of this pay structure.
	 *
	 * @param effectiveDate the effective date of this pay structure
	 */
	public void setEffectiveDate(Date effectiveDate);

	/**
	 * Returns the expiry date of this pay structure.
	 *
	 * @return the expiry date of this pay structure
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this pay structure.
	 *
	 * @param expiryDate the expiry date of this pay structure
	 */
	public void setExpiryDate(Date expiryDate);

	/**
	 * Returns the name of this pay structure.
	 *
	 * @return the name of this pay structure
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this pay structure.
	 *
	 * @param name the name of this pay structure
	 */
	public void setName(String name);

	/**
	 * Returns the deleted of this pay structure.
	 *
	 * @return the deleted of this pay structure
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this pay structure is deleted.
	 *
	 * @return <code>true</code> if this pay structure is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this pay structure is deleted.
	 *
	 * @param deleted the deleted of this pay structure
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the status of this pay structure.
	 *
	 * @return the status of this pay structure
	 */
	public int getStatus();

	/**
	 * Sets the status of this pay structure.
	 *
	 * @param status the status of this pay structure
	 */
	public void setStatus(int status);

}