/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.mdm.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the WorkArea service. Represents a row in the &quot;mdm_WorkArea&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.mdm.liferay.model.impl.WorkAreaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.mdm.liferay.model.impl.WorkAreaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WorkArea
 * @generated
 */
@ProviderType
public interface WorkAreaModel
	extends BaseModel<WorkArea>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a work area model instance should use the {@link WorkArea} interface instead.
	 */

	/**
	 * Returns the primary key of this work area.
	 *
	 * @return the primary key of this work area
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this work area.
	 *
	 * @param primaryKey the primary key of this work area
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the work area ID of this work area.
	 *
	 * @return the work area ID of this work area
	 */
	public long getWorkAreaId();

	/**
	 * Sets the work area ID of this work area.
	 *
	 * @param workAreaId the work area ID of this work area
	 */
	public void setWorkAreaId(long workAreaId);

	/**
	 * Returns the group ID of this work area.
	 *
	 * @return the group ID of this work area
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this work area.
	 *
	 * @param groupId the group ID of this work area
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this work area.
	 *
	 * @return the company ID of this work area
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this work area.
	 *
	 * @param companyId the company ID of this work area
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this work area.
	 *
	 * @return the user ID of this work area
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this work area.
	 *
	 * @param userId the user ID of this work area
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this work area.
	 *
	 * @return the user uuid of this work area
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this work area.
	 *
	 * @param userUuid the user uuid of this work area
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this work area.
	 *
	 * @return the user name of this work area
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this work area.
	 *
	 * @param userName the user name of this work area
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this work area.
	 *
	 * @return the create date of this work area
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this work area.
	 *
	 * @param createDate the create date of this work area
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this work area.
	 *
	 * @return the modified date of this work area
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this work area.
	 *
	 * @param modifiedDate the modified date of this work area
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this work area.
	 *
	 * @return the code of this work area
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this work area.
	 *
	 * @param code the code of this work area
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this work area.
	 *
	 * @return the name of this work area
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this work area.
	 *
	 * @param name the name of this work area
	 */
	public void setName(String name);

	/**
	 * Returns the work area type ID of this work area.
	 *
	 * @return the work area type ID of this work area
	 */
	public long getWorkAreaTypeId();

	/**
	 * Sets the work area type ID of this work area.
	 *
	 * @param workAreaTypeId the work area type ID of this work area
	 */
	public void setWorkAreaTypeId(long workAreaTypeId);

	/**
	 * Returns the parent work area ID of this work area.
	 *
	 * @return the parent work area ID of this work area
	 */
	public long getParentWorkAreaId();

	/**
	 * Sets the parent work area ID of this work area.
	 *
	 * @param parentWorkAreaId the parent work area ID of this work area
	 */
	public void setParentWorkAreaId(long parentWorkAreaId);

	/**
	 * Returns the deleted of this work area.
	 *
	 * @return the deleted of this work area
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this work area is deleted.
	 *
	 * @return <code>true</code> if this work area is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this work area is deleted.
	 *
	 * @param deleted the deleted of this work area
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the status of this work area.
	 *
	 * @return the status of this work area
	 */
	public int getStatus();

	/**
	 * Sets the status of this work area.
	 *
	 * @param status the status of this work area
	 */
	public void setStatus(int status);

}