/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.mdm.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the WorkStation service. Represents a row in the &quot;mdm_WorkStation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.mdm.liferay.model.impl.WorkStationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.mdm.liferay.model.impl.WorkStationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WorkStation
 * @generated
 */
@ProviderType
public interface WorkStationModel
	extends BaseModel<WorkStation>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a work station model instance should use the {@link WorkStation} interface instead.
	 */

	/**
	 * Returns the primary key of this work station.
	 *
	 * @return the primary key of this work station
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this work station.
	 *
	 * @param primaryKey the primary key of this work station
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the work station ID of this work station.
	 *
	 * @return the work station ID of this work station
	 */
	public long getWorkStationId();

	/**
	 * Sets the work station ID of this work station.
	 *
	 * @param workStationId the work station ID of this work station
	 */
	public void setWorkStationId(long workStationId);

	/**
	 * Returns the group ID of this work station.
	 *
	 * @return the group ID of this work station
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this work station.
	 *
	 * @param groupId the group ID of this work station
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this work station.
	 *
	 * @return the company ID of this work station
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this work station.
	 *
	 * @param companyId the company ID of this work station
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this work station.
	 *
	 * @return the user ID of this work station
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this work station.
	 *
	 * @param userId the user ID of this work station
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this work station.
	 *
	 * @return the user uuid of this work station
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this work station.
	 *
	 * @param userUuid the user uuid of this work station
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this work station.
	 *
	 * @return the user name of this work station
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this work station.
	 *
	 * @param userName the user name of this work station
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this work station.
	 *
	 * @return the create date of this work station
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this work station.
	 *
	 * @param createDate the create date of this work station
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this work station.
	 *
	 * @return the modified date of this work station
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this work station.
	 *
	 * @param modifiedDate the modified date of this work station
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this work station.
	 *
	 * @return the code of this work station
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this work station.
	 *
	 * @param code the code of this work station
	 */
	public void setCode(String code);

	/**
	 * Returns the desk no of this work station.
	 *
	 * @return the desk no of this work station
	 */
	@AutoEscape
	public String getDeskNo();

	/**
	 * Sets the desk no of this work station.
	 *
	 * @param deskNo the desk no of this work station
	 */
	public void setDeskNo(String deskNo);

	/**
	 * Returns the extn no of this work station.
	 *
	 * @return the extn no of this work station
	 */
	@AutoEscape
	public String getExtnNo();

	/**
	 * Sets the extn no of this work station.
	 *
	 * @param extnNo the extn no of this work station
	 */
	public void setExtnNo(String extnNo);

	/**
	 * Returns the direct no of this work station.
	 *
	 * @return the direct no of this work station
	 */
	@AutoEscape
	public String getDirectNo();

	/**
	 * Sets the direct no of this work station.
	 *
	 * @param directNo the direct no of this work station
	 */
	public void setDirectNo(String directNo);

	/**
	 * Returns the phone no of this work station.
	 *
	 * @return the phone no of this work station
	 */
	@AutoEscape
	public String getPhoneNo();

	/**
	 * Sets the phone no of this work station.
	 *
	 * @param phoneNo the phone no of this work station
	 */
	public void setPhoneNo(String phoneNo);

	/**
	 * Returns the cabin no of this work station.
	 *
	 * @return the cabin no of this work station
	 */
	@AutoEscape
	public String getCabinNo();

	/**
	 * Sets the cabin no of this work station.
	 *
	 * @param cabinNo the cabin no of this work station
	 */
	public void setCabinNo(String cabinNo);

	/**
	 * Returns the floor no of this work station.
	 *
	 * @return the floor no of this work station
	 */
	@AutoEscape
	public String getFloorNo();

	/**
	 * Sets the floor no of this work station.
	 *
	 * @param floorNo the floor no of this work station
	 */
	public void setFloorNo(String floorNo);

	/**
	 * Returns the deleted of this work station.
	 *
	 * @return the deleted of this work station
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this work station is deleted.
	 *
	 * @return <code>true</code> if this work station is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this work station is deleted.
	 *
	 * @param deleted the deleted of this work station
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the status of this work station.
	 *
	 * @return the status of this work station
	 */
	public int getStatus();

	/**
	 * Sets the status of this work station.
	 *
	 * @param status the status of this work station
	 */
	public void setStatus(int status);

}