/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model.impl;

import com.adjecti.pis.liferay.model.EmployeeTransferRequest;
import com.adjecti.pis.liferay.model.EmployeeTransferRequestModel;
import com.adjecti.pis.liferay.model.EmployeeTransferRequestSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeTransferRequest service. Represents a row in the &quot;pis_EmployeeTransferRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeTransferRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeTransferRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeTransferRequestImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeTransferRequestModelImpl
	extends BaseModelImpl<EmployeeTransferRequest>
	implements EmployeeTransferRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee transfer request model instance should use the <code>EmployeeTransferRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "pis_EmployeeTransferRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"employeeTransferRequestId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"employeeId", Types.BIGINT}, {"organizationId", Types.BIGINT},
		{"transferDate", Types.VARCHAR},
		{"startDateInNewUnit", Types.TIMESTAMP},
		{"lastDateInCurrentUnit", Types.TIMESTAMP},
		{"officeOrderNo", Types.VARCHAR}, {"processFileId", Types.BIGINT},
		{"processFileNo", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeTransferRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("transferDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDateInNewUnit", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastDateInCurrentUnit", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("officeOrderNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("processFileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("processFileNo", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table pis_EmployeeTransferRequest (uuid_ VARCHAR(75) null,employeeTransferRequestId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,employeeId LONG,organizationId LONG,transferDate VARCHAR(75) null,startDateInNewUnit DATE null,lastDateInCurrentUnit DATE null,officeOrderNo VARCHAR(75) null,processFileId LONG,processFileNo VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table pis_EmployeeTransferRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeTransferRequest.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY pis_EmployeeTransferRequest.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static EmployeeTransferRequest toModel(
		EmployeeTransferRequestSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		EmployeeTransferRequest model = new EmployeeTransferRequestImpl();

		model.setUuid(soapModel.getUuid());
		model.setEmployeeTransferRequestId(
			soapModel.getEmployeeTransferRequestId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setOrganizationId(soapModel.getOrganizationId());
		model.setTransferDate(soapModel.getTransferDate());
		model.setStartDateInNewUnit(soapModel.getStartDateInNewUnit());
		model.setLastDateInCurrentUnit(soapModel.getLastDateInCurrentUnit());
		model.setOfficeOrderNo(soapModel.getOfficeOrderNo());
		model.setProcessFileId(soapModel.getProcessFileId());
		model.setProcessFileNo(soapModel.getProcessFileNo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<EmployeeTransferRequest> toModels(
		EmployeeTransferRequestSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EmployeeTransferRequest> models =
			new ArrayList<EmployeeTransferRequest>(soapModels.length);

		for (EmployeeTransferRequestSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EmployeeTransferRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeTransferRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeTransferRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeTransferRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeTransferRequest.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeTransferRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeTransferRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeTransferRequest, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeTransferRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeTransferRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeTransferRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeTransferRequest, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeTransferRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeTransferRequest, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeTransferRequest, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EmployeeTransferRequest>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EmployeeTransferRequest.class.getClassLoader(),
			EmployeeTransferRequest.class, ModelWrapper.class);

		try {
			Constructor<EmployeeTransferRequest> constructor =
				(Constructor<EmployeeTransferRequest>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EmployeeTransferRequest, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<EmployeeTransferRequest, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<EmployeeTransferRequest, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EmployeeTransferRequest, Object>>();
		Map<String, BiConsumer<EmployeeTransferRequest, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<EmployeeTransferRequest, ?>>();

		attributeGetterFunctions.put("uuid", EmployeeTransferRequest::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EmployeeTransferRequest, String>)
				EmployeeTransferRequest::setUuid);
		attributeGetterFunctions.put(
			"employeeTransferRequestId",
			EmployeeTransferRequest::getEmployeeTransferRequestId);
		attributeSetterBiConsumers.put(
			"employeeTransferRequestId",
			(BiConsumer<EmployeeTransferRequest, Long>)
				EmployeeTransferRequest::setEmployeeTransferRequestId);
		attributeGetterFunctions.put(
			"groupId", EmployeeTransferRequest::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EmployeeTransferRequest, Long>)
				EmployeeTransferRequest::setGroupId);
		attributeGetterFunctions.put(
			"companyId", EmployeeTransferRequest::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EmployeeTransferRequest, Long>)
				EmployeeTransferRequest::setCompanyId);
		attributeGetterFunctions.put(
			"userId", EmployeeTransferRequest::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EmployeeTransferRequest, Long>)
				EmployeeTransferRequest::setUserId);
		attributeGetterFunctions.put(
			"userName", EmployeeTransferRequest::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EmployeeTransferRequest, String>)
				EmployeeTransferRequest::setUserName);
		attributeGetterFunctions.put(
			"createDate", EmployeeTransferRequest::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EmployeeTransferRequest, Date>)
				EmployeeTransferRequest::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EmployeeTransferRequest::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EmployeeTransferRequest, Date>)
				EmployeeTransferRequest::setModifiedDate);
		attributeGetterFunctions.put(
			"employeeId", EmployeeTransferRequest::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId",
			(BiConsumer<EmployeeTransferRequest, Long>)
				EmployeeTransferRequest::setEmployeeId);
		attributeGetterFunctions.put(
			"organizationId", EmployeeTransferRequest::getOrganizationId);
		attributeSetterBiConsumers.put(
			"organizationId",
			(BiConsumer<EmployeeTransferRequest, Long>)
				EmployeeTransferRequest::setOrganizationId);
		attributeGetterFunctions.put(
			"transferDate", EmployeeTransferRequest::getTransferDate);
		attributeSetterBiConsumers.put(
			"transferDate",
			(BiConsumer<EmployeeTransferRequest, String>)
				EmployeeTransferRequest::setTransferDate);
		attributeGetterFunctions.put(
			"startDateInNewUnit",
			EmployeeTransferRequest::getStartDateInNewUnit);
		attributeSetterBiConsumers.put(
			"startDateInNewUnit",
			(BiConsumer<EmployeeTransferRequest, Date>)
				EmployeeTransferRequest::setStartDateInNewUnit);
		attributeGetterFunctions.put(
			"lastDateInCurrentUnit",
			EmployeeTransferRequest::getLastDateInCurrentUnit);
		attributeSetterBiConsumers.put(
			"lastDateInCurrentUnit",
			(BiConsumer<EmployeeTransferRequest, Date>)
				EmployeeTransferRequest::setLastDateInCurrentUnit);
		attributeGetterFunctions.put(
			"officeOrderNo", EmployeeTransferRequest::getOfficeOrderNo);
		attributeSetterBiConsumers.put(
			"officeOrderNo",
			(BiConsumer<EmployeeTransferRequest, String>)
				EmployeeTransferRequest::setOfficeOrderNo);
		attributeGetterFunctions.put(
			"processFileId", EmployeeTransferRequest::getProcessFileId);
		attributeSetterBiConsumers.put(
			"processFileId",
			(BiConsumer<EmployeeTransferRequest, Long>)
				EmployeeTransferRequest::setProcessFileId);
		attributeGetterFunctions.put(
			"processFileNo", EmployeeTransferRequest::getProcessFileNo);
		attributeSetterBiConsumers.put(
			"processFileNo",
			(BiConsumer<EmployeeTransferRequest, String>)
				EmployeeTransferRequest::setProcessFileNo);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEmployeeTransferRequestId() {
		return _employeeTransferRequestId;
	}

	@Override
	public void setEmployeeTransferRequestId(long employeeTransferRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeTransferRequestId = employeeTransferRequestId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public Long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(Long organizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organizationId = organizationId;
	}

	@JSON
	@Override
	public String getTransferDate() {
		if (_transferDate == null) {
			return "";
		}
		else {
			return _transferDate;
		}
	}

	@Override
	public void setTransferDate(String transferDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_transferDate = transferDate;
	}

	@JSON
	@Override
	public Date getStartDateInNewUnit() {
		return _startDateInNewUnit;
	}

	@Override
	public void setStartDateInNewUnit(Date startDateInNewUnit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDateInNewUnit = startDateInNewUnit;
	}

	@JSON
	@Override
	public Date getLastDateInCurrentUnit() {
		return _lastDateInCurrentUnit;
	}

	@Override
	public void setLastDateInCurrentUnit(Date lastDateInCurrentUnit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastDateInCurrentUnit = lastDateInCurrentUnit;
	}

	@JSON
	@Override
	public String getOfficeOrderNo() {
		if (_officeOrderNo == null) {
			return "";
		}
		else {
			return _officeOrderNo;
		}
	}

	@Override
	public void setOfficeOrderNo(String officeOrderNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_officeOrderNo = officeOrderNo;
	}

	@JSON
	@Override
	public long getProcessFileId() {
		return _processFileId;
	}

	@Override
	public void setProcessFileId(long processFileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_processFileId = processFileId;
	}

	@JSON
	@Override
	public String getProcessFileNo() {
		if (_processFileNo == null) {
			return "";
		}
		else {
			return _processFileNo;
		}
	}

	@Override
	public void setProcessFileNo(String processFileNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_processFileNo = processFileNo;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeTransferRequest.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeTransferRequest.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeTransferRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeTransferRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeTransferRequestImpl employeeTransferRequestImpl =
			new EmployeeTransferRequestImpl();

		employeeTransferRequestImpl.setUuid(getUuid());
		employeeTransferRequestImpl.setEmployeeTransferRequestId(
			getEmployeeTransferRequestId());
		employeeTransferRequestImpl.setGroupId(getGroupId());
		employeeTransferRequestImpl.setCompanyId(getCompanyId());
		employeeTransferRequestImpl.setUserId(getUserId());
		employeeTransferRequestImpl.setUserName(getUserName());
		employeeTransferRequestImpl.setCreateDate(getCreateDate());
		employeeTransferRequestImpl.setModifiedDate(getModifiedDate());
		employeeTransferRequestImpl.setEmployeeId(getEmployeeId());
		employeeTransferRequestImpl.setOrganizationId(getOrganizationId());
		employeeTransferRequestImpl.setTransferDate(getTransferDate());
		employeeTransferRequestImpl.setStartDateInNewUnit(
			getStartDateInNewUnit());
		employeeTransferRequestImpl.setLastDateInCurrentUnit(
			getLastDateInCurrentUnit());
		employeeTransferRequestImpl.setOfficeOrderNo(getOfficeOrderNo());
		employeeTransferRequestImpl.setProcessFileId(getProcessFileId());
		employeeTransferRequestImpl.setProcessFileNo(getProcessFileNo());

		employeeTransferRequestImpl.resetOriginalValues();

		return employeeTransferRequestImpl;
	}

	@Override
	public int compareTo(EmployeeTransferRequest employeeTransferRequest) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), employeeTransferRequest.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeTransferRequest)) {
			return false;
		}

		EmployeeTransferRequest employeeTransferRequest =
			(EmployeeTransferRequest)object;

		long primaryKey = employeeTransferRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeTransferRequest> toCacheModel() {
		EmployeeTransferRequestCacheModel employeeTransferRequestCacheModel =
			new EmployeeTransferRequestCacheModel();

		employeeTransferRequestCacheModel.uuid = getUuid();

		String uuid = employeeTransferRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeTransferRequestCacheModel.uuid = null;
		}

		employeeTransferRequestCacheModel.employeeTransferRequestId =
			getEmployeeTransferRequestId();

		employeeTransferRequestCacheModel.groupId = getGroupId();

		employeeTransferRequestCacheModel.companyId = getCompanyId();

		employeeTransferRequestCacheModel.userId = getUserId();

		employeeTransferRequestCacheModel.userName = getUserName();

		String userName = employeeTransferRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			employeeTransferRequestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeTransferRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeTransferRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeTransferRequestCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			employeeTransferRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeTransferRequestCacheModel.employeeId = getEmployeeId();

		Long organizationId = getOrganizationId();

		if (organizationId != null) {
			employeeTransferRequestCacheModel.organizationId = organizationId;
		}

		employeeTransferRequestCacheModel.transferDate = getTransferDate();

		String transferDate = employeeTransferRequestCacheModel.transferDate;

		if ((transferDate != null) && (transferDate.length() == 0)) {
			employeeTransferRequestCacheModel.transferDate = null;
		}

		Date startDateInNewUnit = getStartDateInNewUnit();

		if (startDateInNewUnit != null) {
			employeeTransferRequestCacheModel.startDateInNewUnit =
				startDateInNewUnit.getTime();
		}
		else {
			employeeTransferRequestCacheModel.startDateInNewUnit =
				Long.MIN_VALUE;
		}

		Date lastDateInCurrentUnit = getLastDateInCurrentUnit();

		if (lastDateInCurrentUnit != null) {
			employeeTransferRequestCacheModel.lastDateInCurrentUnit =
				lastDateInCurrentUnit.getTime();
		}
		else {
			employeeTransferRequestCacheModel.lastDateInCurrentUnit =
				Long.MIN_VALUE;
		}

		employeeTransferRequestCacheModel.officeOrderNo = getOfficeOrderNo();

		String officeOrderNo = employeeTransferRequestCacheModel.officeOrderNo;

		if ((officeOrderNo != null) && (officeOrderNo.length() == 0)) {
			employeeTransferRequestCacheModel.officeOrderNo = null;
		}

		employeeTransferRequestCacheModel.processFileId = getProcessFileId();

		employeeTransferRequestCacheModel.processFileNo = getProcessFileNo();

		String processFileNo = employeeTransferRequestCacheModel.processFileNo;

		if ((processFileNo != null) && (processFileNo.length() == 0)) {
			employeeTransferRequestCacheModel.processFileNo = null;
		}

		return employeeTransferRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeTransferRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeTransferRequest, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeTransferRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((EmployeeTransferRequest)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EmployeeTransferRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EmployeeTransferRequest, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeTransferRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((EmployeeTransferRequest)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, EmployeeTransferRequest>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private String _uuid;
	private long _employeeTransferRequestId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _employeeId;
	private Long _organizationId;
	private String _transferDate;
	private Date _startDateInNewUnit;
	private Date _lastDateInCurrentUnit;
	private String _officeOrderNo;
	private long _processFileId;
	private String _processFileNo;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeTransferRequest, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeTransferRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"employeeTransferRequestId", _employeeTransferRequestId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("organizationId", _organizationId);
		_columnOriginalValues.put("transferDate", _transferDate);
		_columnOriginalValues.put("startDateInNewUnit", _startDateInNewUnit);
		_columnOriginalValues.put(
			"lastDateInCurrentUnit", _lastDateInCurrentUnit);
		_columnOriginalValues.put("officeOrderNo", _officeOrderNo);
		_columnOriginalValues.put("processFileId", _processFileId);
		_columnOriginalValues.put("processFileNo", _processFileNo);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("employeeTransferRequestId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("employeeId", 256L);

		columnBitmasks.put("organizationId", 512L);

		columnBitmasks.put("transferDate", 1024L);

		columnBitmasks.put("startDateInNewUnit", 2048L);

		columnBitmasks.put("lastDateInCurrentUnit", 4096L);

		columnBitmasks.put("officeOrderNo", 8192L);

		columnBitmasks.put("processFileId", 16384L);

		columnBitmasks.put("processFileNo", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeTransferRequest _escapedModel;

}