/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model.impl;

import com.adjecti.pis.liferay.model.EmployeePayStructure;
import com.adjecti.pis.liferay.model.EmployeePayStructureModel;
import com.adjecti.pis.liferay.model.EmployeePayStructureSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeePayStructure service. Represents a row in the &quot;pis_EmployeePayStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeePayStructureModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeePayStructureImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeePayStructureImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeePayStructureModelImpl
	extends BaseModelImpl<EmployeePayStructure>
	implements EmployeePayStructureModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee pay structure model instance should use the <code>EmployeePayStructure</code> interface instead.
	 */
	public static final String TABLE_NAME = "pis_EmployeePayStructure";

	public static final Object[][] TABLE_COLUMNS = {
		{"employeePayStructureId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"active_", Types.BOOLEAN},
		{"fromDate", Types.TIMESTAMP}, {"toDate", Types.TIMESTAMP},
		{"employeeId", Types.BIGINT}, {"levelId", Types.BIGINT},
		{"structureId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("employeePayStructureId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("fromDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("toDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("levelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("structureId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table pis_EmployeePayStructure (employeePayStructureId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,active_ BOOLEAN,fromDate DATE null,toDate DATE null,employeeId LONG,levelId LONG,structureId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table pis_EmployeePayStructure";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeePayStructure.employeePayStructureId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY pis_EmployeePayStructure.employeePayStructureId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEPAYSTRUCTUREID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static EmployeePayStructure toModel(
		EmployeePayStructureSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		EmployeePayStructure model = new EmployeePayStructureImpl();

		model.setEmployeePayStructureId(soapModel.getEmployeePayStructureId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setActive(soapModel.isActive());
		model.setFromDate(soapModel.getFromDate());
		model.setToDate(soapModel.getToDate());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setLevelId(soapModel.getLevelId());
		model.setStructureId(soapModel.getStructureId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<EmployeePayStructure> toModels(
		EmployeePayStructureSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EmployeePayStructure> models = new ArrayList<EmployeePayStructure>(
			soapModels.length);

		for (EmployeePayStructureSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EmployeePayStructureModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeePayStructureId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeePayStructureId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeePayStructureId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeePayStructure.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeePayStructure.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeePayStructure, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeePayStructure, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeePayStructure, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeePayStructure)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeePayStructure, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeePayStructure, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeePayStructure)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeePayStructure, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeePayStructure, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EmployeePayStructure>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EmployeePayStructure.class.getClassLoader(),
			EmployeePayStructure.class, ModelWrapper.class);

		try {
			Constructor<EmployeePayStructure> constructor =
				(Constructor<EmployeePayStructure>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EmployeePayStructure, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EmployeePayStructure, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EmployeePayStructure, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EmployeePayStructure, Object>>();
		Map<String, BiConsumer<EmployeePayStructure, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<EmployeePayStructure, ?>>();

		attributeGetterFunctions.put(
			"employeePayStructureId",
			EmployeePayStructure::getEmployeePayStructureId);
		attributeSetterBiConsumers.put(
			"employeePayStructureId",
			(BiConsumer<EmployeePayStructure, Long>)
				EmployeePayStructure::setEmployeePayStructureId);
		attributeGetterFunctions.put(
			"groupId", EmployeePayStructure::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EmployeePayStructure, Long>)
				EmployeePayStructure::setGroupId);
		attributeGetterFunctions.put(
			"companyId", EmployeePayStructure::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EmployeePayStructure, Long>)
				EmployeePayStructure::setCompanyId);
		attributeGetterFunctions.put("userId", EmployeePayStructure::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EmployeePayStructure, Long>)
				EmployeePayStructure::setUserId);
		attributeGetterFunctions.put(
			"userName", EmployeePayStructure::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EmployeePayStructure, String>)
				EmployeePayStructure::setUserName);
		attributeGetterFunctions.put(
			"createDate", EmployeePayStructure::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EmployeePayStructure, Date>)
				EmployeePayStructure::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EmployeePayStructure::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EmployeePayStructure, Date>)
				EmployeePayStructure::setModifiedDate);
		attributeGetterFunctions.put("active", EmployeePayStructure::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<EmployeePayStructure, Boolean>)
				EmployeePayStructure::setActive);
		attributeGetterFunctions.put(
			"fromDate", EmployeePayStructure::getFromDate);
		attributeSetterBiConsumers.put(
			"fromDate",
			(BiConsumer<EmployeePayStructure, Date>)
				EmployeePayStructure::setFromDate);
		attributeGetterFunctions.put("toDate", EmployeePayStructure::getToDate);
		attributeSetterBiConsumers.put(
			"toDate",
			(BiConsumer<EmployeePayStructure, Date>)
				EmployeePayStructure::setToDate);
		attributeGetterFunctions.put(
			"employeeId", EmployeePayStructure::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId",
			(BiConsumer<EmployeePayStructure, Long>)
				EmployeePayStructure::setEmployeeId);
		attributeGetterFunctions.put(
			"levelId", EmployeePayStructure::getLevelId);
		attributeSetterBiConsumers.put(
			"levelId",
			(BiConsumer<EmployeePayStructure, Long>)
				EmployeePayStructure::setLevelId);
		attributeGetterFunctions.put(
			"structureId", EmployeePayStructure::getStructureId);
		attributeSetterBiConsumers.put(
			"structureId",
			(BiConsumer<EmployeePayStructure, Long>)
				EmployeePayStructure::setStructureId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getEmployeePayStructureId() {
		return _employeePayStructureId;
	}

	@Override
	public void setEmployeePayStructureId(long employeePayStructureId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeePayStructureId = employeePayStructureId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public Date getFromDate() {
		return _fromDate;
	}

	@Override
	public void setFromDate(Date fromDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fromDate = fromDate;
	}

	@JSON
	@Override
	public Date getToDate() {
		return _toDate;
	}

	@Override
	public void setToDate(Date toDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_toDate = toDate;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public long getLevelId() {
		return _levelId;
	}

	@Override
	public void setLevelId(long levelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_levelId = levelId;
	}

	@JSON
	@Override
	public long getStructureId() {
		return _structureId;
	}

	@Override
	public void setStructureId(long structureId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_structureId = structureId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeePayStructure.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeePayStructure toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeePayStructure>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeePayStructureImpl employeePayStructureImpl =
			new EmployeePayStructureImpl();

		employeePayStructureImpl.setEmployeePayStructureId(
			getEmployeePayStructureId());
		employeePayStructureImpl.setGroupId(getGroupId());
		employeePayStructureImpl.setCompanyId(getCompanyId());
		employeePayStructureImpl.setUserId(getUserId());
		employeePayStructureImpl.setUserName(getUserName());
		employeePayStructureImpl.setCreateDate(getCreateDate());
		employeePayStructureImpl.setModifiedDate(getModifiedDate());
		employeePayStructureImpl.setActive(isActive());
		employeePayStructureImpl.setFromDate(getFromDate());
		employeePayStructureImpl.setToDate(getToDate());
		employeePayStructureImpl.setEmployeeId(getEmployeeId());
		employeePayStructureImpl.setLevelId(getLevelId());
		employeePayStructureImpl.setStructureId(getStructureId());

		employeePayStructureImpl.resetOriginalValues();

		return employeePayStructureImpl;
	}

	@Override
	public int compareTo(EmployeePayStructure employeePayStructure) {
		long primaryKey = employeePayStructure.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeePayStructure)) {
			return false;
		}

		EmployeePayStructure employeePayStructure =
			(EmployeePayStructure)object;

		long primaryKey = employeePayStructure.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeePayStructure> toCacheModel() {
		EmployeePayStructureCacheModel employeePayStructureCacheModel =
			new EmployeePayStructureCacheModel();

		employeePayStructureCacheModel.employeePayStructureId =
			getEmployeePayStructureId();

		employeePayStructureCacheModel.groupId = getGroupId();

		employeePayStructureCacheModel.companyId = getCompanyId();

		employeePayStructureCacheModel.userId = getUserId();

		employeePayStructureCacheModel.userName = getUserName();

		String userName = employeePayStructureCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			employeePayStructureCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeePayStructureCacheModel.createDate = createDate.getTime();
		}
		else {
			employeePayStructureCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeePayStructureCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			employeePayStructureCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeePayStructureCacheModel.active = isActive();

		Date fromDate = getFromDate();

		if (fromDate != null) {
			employeePayStructureCacheModel.fromDate = fromDate.getTime();
		}
		else {
			employeePayStructureCacheModel.fromDate = Long.MIN_VALUE;
		}

		Date toDate = getToDate();

		if (toDate != null) {
			employeePayStructureCacheModel.toDate = toDate.getTime();
		}
		else {
			employeePayStructureCacheModel.toDate = Long.MIN_VALUE;
		}

		employeePayStructureCacheModel.employeeId = getEmployeeId();

		employeePayStructureCacheModel.levelId = getLevelId();

		employeePayStructureCacheModel.structureId = getStructureId();

		return employeePayStructureCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeePayStructure, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeePayStructure, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeePayStructure, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((EmployeePayStructure)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EmployeePayStructure, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EmployeePayStructure, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeePayStructure, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((EmployeePayStructure)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeePayStructure>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _employeePayStructureId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _active;
	private Date _fromDate;
	private Date _toDate;
	private long _employeeId;
	private long _levelId;
	private long _structureId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeePayStructure, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeePayStructure)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"employeePayStructureId", _employeePayStructureId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("fromDate", _fromDate);
		_columnOriginalValues.put("toDate", _toDate);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("levelId", _levelId);
		_columnOriginalValues.put("structureId", _structureId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("employeePayStructureId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("active_", 128L);

		columnBitmasks.put("fromDate", 256L);

		columnBitmasks.put("toDate", 512L);

		columnBitmasks.put("employeeId", 1024L);

		columnBitmasks.put("levelId", 2048L);

		columnBitmasks.put("structureId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeePayStructure _escapedModel;

}