/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model.impl;

import com.adjecti.pis.liferay.model.EmployeeDsc;
import com.adjecti.pis.liferay.model.EmployeeDscModel;
import com.adjecti.pis.liferay.model.EmployeeDscSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeDsc service. Represents a row in the &quot;pis_EmployeeDsc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeDscModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeDscImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDscImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeDscModelImpl
	extends BaseModelImpl<EmployeeDsc> implements EmployeeDscModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee dsc model instance should use the <code>EmployeeDsc</code> interface instead.
	 */
	public static final String TABLE_NAME = "pis_EmployeeDsc";

	public static final Object[][] TABLE_COLUMNS = {
		{"employeeDscId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"employeeId", Types.BIGINT},
		{"cid", Types.VARCHAR}, {"details", Types.VARCHAR},
		{"ofbDSCReissueDate", Types.TIMESTAMP},
		{"ofbDSCRevocationDate", Types.TIMESTAMP},
		{"ofbDSCRevocationStatus", Types.BOOLEAN},
		{"ofbDSCReissueStatus", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("employeeDscId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("details", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ofbDSCReissueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ofbDSCRevocationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ofbDSCRevocationStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("ofbDSCReissueStatus", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table pis_EmployeeDsc (employeeDscId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,employeeId LONG,cid VARCHAR(75) null,details VARCHAR(75) null,ofbDSCReissueDate DATE null,ofbDSCRevocationDate DATE null,ofbDSCRevocationStatus BOOLEAN,ofbDSCReissueStatus BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table pis_EmployeeDsc";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeDsc.employeeDscId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY pis_EmployeeDsc.employeeDscId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long CID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEDSCID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static EmployeeDsc toModel(EmployeeDscSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EmployeeDsc model = new EmployeeDscImpl();

		model.setEmployeeDscId(soapModel.getEmployeeDscId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setCid(soapModel.getCid());
		model.setDetails(soapModel.getDetails());
		model.setOfbDSCReissueDate(soapModel.getOfbDSCReissueDate());
		model.setOfbDSCRevocationDate(soapModel.getOfbDSCRevocationDate());
		model.setOfbDSCRevocationStatus(soapModel.isOfbDSCRevocationStatus());
		model.setOfbDSCReissueStatus(soapModel.isOfbDSCReissueStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<EmployeeDsc> toModels(EmployeeDscSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EmployeeDsc> models = new ArrayList<EmployeeDsc>(
			soapModels.length);

		for (EmployeeDscSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EmployeeDscModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeDscId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeDscId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeDscId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeDsc.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeDsc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeDsc, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeDsc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDsc, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeDsc)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeDsc, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeDsc, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeDsc)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeDsc, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeDsc, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EmployeeDsc>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EmployeeDsc.class.getClassLoader(), EmployeeDsc.class,
			ModelWrapper.class);

		try {
			Constructor<EmployeeDsc> constructor =
				(Constructor<EmployeeDsc>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EmployeeDsc, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EmployeeDsc, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EmployeeDsc, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EmployeeDsc, Object>>();
		Map<String, BiConsumer<EmployeeDsc, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EmployeeDsc, ?>>();

		attributeGetterFunctions.put(
			"employeeDscId", EmployeeDsc::getEmployeeDscId);
		attributeSetterBiConsumers.put(
			"employeeDscId",
			(BiConsumer<EmployeeDsc, Long>)EmployeeDsc::setEmployeeDscId);
		attributeGetterFunctions.put("groupId", EmployeeDsc::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<EmployeeDsc, Long>)EmployeeDsc::setGroupId);
		attributeGetterFunctions.put("companyId", EmployeeDsc::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EmployeeDsc, Long>)EmployeeDsc::setCompanyId);
		attributeGetterFunctions.put("userId", EmployeeDsc::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<EmployeeDsc, Long>)EmployeeDsc::setUserId);
		attributeGetterFunctions.put("userName", EmployeeDsc::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EmployeeDsc, String>)EmployeeDsc::setUserName);
		attributeGetterFunctions.put("createDate", EmployeeDsc::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EmployeeDsc, Date>)EmployeeDsc::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EmployeeDsc::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EmployeeDsc, Date>)EmployeeDsc::setModifiedDate);
		attributeGetterFunctions.put("employeeId", EmployeeDsc::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId",
			(BiConsumer<EmployeeDsc, Long>)EmployeeDsc::setEmployeeId);
		attributeGetterFunctions.put("cid", EmployeeDsc::getCid);
		attributeSetterBiConsumers.put(
			"cid", (BiConsumer<EmployeeDsc, String>)EmployeeDsc::setCid);
		attributeGetterFunctions.put("details", EmployeeDsc::getDetails);
		attributeSetterBiConsumers.put(
			"details",
			(BiConsumer<EmployeeDsc, String>)EmployeeDsc::setDetails);
		attributeGetterFunctions.put(
			"ofbDSCReissueDate", EmployeeDsc::getOfbDSCReissueDate);
		attributeSetterBiConsumers.put(
			"ofbDSCReissueDate",
			(BiConsumer<EmployeeDsc, Date>)EmployeeDsc::setOfbDSCReissueDate);
		attributeGetterFunctions.put(
			"ofbDSCRevocationDate", EmployeeDsc::getOfbDSCRevocationDate);
		attributeSetterBiConsumers.put(
			"ofbDSCRevocationDate",
			(BiConsumer<EmployeeDsc, Date>)
				EmployeeDsc::setOfbDSCRevocationDate);
		attributeGetterFunctions.put(
			"ofbDSCRevocationStatus", EmployeeDsc::getOfbDSCRevocationStatus);
		attributeSetterBiConsumers.put(
			"ofbDSCRevocationStatus",
			(BiConsumer<EmployeeDsc, Boolean>)
				EmployeeDsc::setOfbDSCRevocationStatus);
		attributeGetterFunctions.put(
			"ofbDSCReissueStatus", EmployeeDsc::getOfbDSCReissueStatus);
		attributeSetterBiConsumers.put(
			"ofbDSCReissueStatus",
			(BiConsumer<EmployeeDsc, Boolean>)
				EmployeeDsc::setOfbDSCReissueStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getEmployeeDscId() {
		return _employeeDscId;
	}

	@Override
	public void setEmployeeDscId(long employeeDscId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeDscId = employeeDscId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public String getCid() {
		if (_cid == null) {
			return "";
		}
		else {
			return _cid;
		}
	}

	@Override
	public void setCid(String cid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cid = cid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCid() {
		return getColumnOriginalValue("cid");
	}

	@JSON
	@Override
	public String getDetails() {
		if (_details == null) {
			return "";
		}
		else {
			return _details;
		}
	}

	@Override
	public void setDetails(String details) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_details = details;
	}

	@JSON
	@Override
	public Date getOfbDSCReissueDate() {
		return _ofbDSCReissueDate;
	}

	@Override
	public void setOfbDSCReissueDate(Date ofbDSCReissueDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ofbDSCReissueDate = ofbDSCReissueDate;
	}

	@JSON
	@Override
	public Date getOfbDSCRevocationDate() {
		return _ofbDSCRevocationDate;
	}

	@Override
	public void setOfbDSCRevocationDate(Date ofbDSCRevocationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ofbDSCRevocationDate = ofbDSCRevocationDate;
	}

	@JSON
	@Override
	public boolean getOfbDSCRevocationStatus() {
		return _ofbDSCRevocationStatus;
	}

	@JSON
	@Override
	public boolean isOfbDSCRevocationStatus() {
		return _ofbDSCRevocationStatus;
	}

	@Override
	public void setOfbDSCRevocationStatus(boolean ofbDSCRevocationStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ofbDSCRevocationStatus = ofbDSCRevocationStatus;
	}

	@JSON
	@Override
	public boolean getOfbDSCReissueStatus() {
		return _ofbDSCReissueStatus;
	}

	@JSON
	@Override
	public boolean isOfbDSCReissueStatus() {
		return _ofbDSCReissueStatus;
	}

	@Override
	public void setOfbDSCReissueStatus(boolean ofbDSCReissueStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ofbDSCReissueStatus = ofbDSCReissueStatus;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeDsc.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeDsc toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeDsc>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeDscImpl employeeDscImpl = new EmployeeDscImpl();

		employeeDscImpl.setEmployeeDscId(getEmployeeDscId());
		employeeDscImpl.setGroupId(getGroupId());
		employeeDscImpl.setCompanyId(getCompanyId());
		employeeDscImpl.setUserId(getUserId());
		employeeDscImpl.setUserName(getUserName());
		employeeDscImpl.setCreateDate(getCreateDate());
		employeeDscImpl.setModifiedDate(getModifiedDate());
		employeeDscImpl.setEmployeeId(getEmployeeId());
		employeeDscImpl.setCid(getCid());
		employeeDscImpl.setDetails(getDetails());
		employeeDscImpl.setOfbDSCReissueDate(getOfbDSCReissueDate());
		employeeDscImpl.setOfbDSCRevocationDate(getOfbDSCRevocationDate());
		employeeDscImpl.setOfbDSCRevocationStatus(isOfbDSCRevocationStatus());
		employeeDscImpl.setOfbDSCReissueStatus(isOfbDSCReissueStatus());

		employeeDscImpl.resetOriginalValues();

		return employeeDscImpl;
	}

	@Override
	public int compareTo(EmployeeDsc employeeDsc) {
		long primaryKey = employeeDsc.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeDsc)) {
			return false;
		}

		EmployeeDsc employeeDsc = (EmployeeDsc)object;

		long primaryKey = employeeDsc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeDsc> toCacheModel() {
		EmployeeDscCacheModel employeeDscCacheModel =
			new EmployeeDscCacheModel();

		employeeDscCacheModel.employeeDscId = getEmployeeDscId();

		employeeDscCacheModel.groupId = getGroupId();

		employeeDscCacheModel.companyId = getCompanyId();

		employeeDscCacheModel.userId = getUserId();

		employeeDscCacheModel.userName = getUserName();

		String userName = employeeDscCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			employeeDscCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeDscCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeDscCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeDscCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeDscCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeDscCacheModel.employeeId = getEmployeeId();

		employeeDscCacheModel.cid = getCid();

		String cid = employeeDscCacheModel.cid;

		if ((cid != null) && (cid.length() == 0)) {
			employeeDscCacheModel.cid = null;
		}

		employeeDscCacheModel.details = getDetails();

		String details = employeeDscCacheModel.details;

		if ((details != null) && (details.length() == 0)) {
			employeeDscCacheModel.details = null;
		}

		Date ofbDSCReissueDate = getOfbDSCReissueDate();

		if (ofbDSCReissueDate != null) {
			employeeDscCacheModel.ofbDSCReissueDate =
				ofbDSCReissueDate.getTime();
		}
		else {
			employeeDscCacheModel.ofbDSCReissueDate = Long.MIN_VALUE;
		}

		Date ofbDSCRevocationDate = getOfbDSCRevocationDate();

		if (ofbDSCRevocationDate != null) {
			employeeDscCacheModel.ofbDSCRevocationDate =
				ofbDSCRevocationDate.getTime();
		}
		else {
			employeeDscCacheModel.ofbDSCRevocationDate = Long.MIN_VALUE;
		}

		employeeDscCacheModel.ofbDSCRevocationStatus =
			isOfbDSCRevocationStatus();

		employeeDscCacheModel.ofbDSCReissueStatus = isOfbDSCReissueStatus();

		return employeeDscCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeDsc, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeDsc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDsc, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EmployeeDsc)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EmployeeDsc, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EmployeeDsc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDsc, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EmployeeDsc)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeDsc>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _employeeDscId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _employeeId;
	private String _cid;
	private String _details;
	private Date _ofbDSCReissueDate;
	private Date _ofbDSCRevocationDate;
	private boolean _ofbDSCRevocationStatus;
	private boolean _ofbDSCReissueStatus;

	public <T> T getColumnValue(String columnName) {
		Function<EmployeeDsc, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeDsc)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("employeeDscId", _employeeDscId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("cid", _cid);
		_columnOriginalValues.put("details", _details);
		_columnOriginalValues.put("ofbDSCReissueDate", _ofbDSCReissueDate);
		_columnOriginalValues.put(
			"ofbDSCRevocationDate", _ofbDSCRevocationDate);
		_columnOriginalValues.put(
			"ofbDSCRevocationStatus", _ofbDSCRevocationStatus);
		_columnOriginalValues.put("ofbDSCReissueStatus", _ofbDSCReissueStatus);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("employeeDscId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("employeeId", 128L);

		columnBitmasks.put("cid", 256L);

		columnBitmasks.put("details", 512L);

		columnBitmasks.put("ofbDSCReissueDate", 1024L);

		columnBitmasks.put("ofbDSCRevocationDate", 2048L);

		columnBitmasks.put("ofbDSCRevocationStatus", 4096L);

		columnBitmasks.put("ofbDSCReissueStatus", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeDsc _escapedModel;

}