/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model.impl;

import com.adjecti.pis.liferay.model.EmployeePromotion;
import com.adjecti.pis.liferay.model.EmployeePromotionModel;
import com.adjecti.pis.liferay.model.EmployeePromotionSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeePromotion service. Represents a row in the &quot;pis_EmployeePromotion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeePromotionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeePromotionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeePromotionImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeePromotionModelImpl
	extends BaseModelImpl<EmployeePromotion> implements EmployeePromotionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee promotion model instance should use the <code>EmployeePromotion</code> interface instead.
	 */
	public static final String TABLE_NAME = "pis_EmployeePromotion";

	public static final Object[][] TABLE_COLUMNS = {
		{"employeePromotionId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"active_", Types.BOOLEAN},
		{"promotionDate", Types.TIMESTAMP}, {"designationId", Types.BIGINT},
		{"employeeId", Types.BIGINT}, {"gradeId", Types.BIGINT},
		{"gradeModeId", Types.BIGINT}, {"promotionLetterId", Types.BIGINT},
		{"organizationId", Types.BIGINT}, {"personalNo", Types.BIGINT},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("employeePromotionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("promotionDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("designationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("gradeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("gradeModeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("promotionLetterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("personalNo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table pis_EmployeePromotion (employeePromotionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,active_ BOOLEAN,promotionDate DATE null,designationId LONG,employeeId LONG,gradeId LONG,gradeModeId LONG,promotionLetterId LONG,organizationId LONG,personalNo LONG,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table pis_EmployeePromotion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeePromotion.employeePromotionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY pis_EmployeePromotion.employeePromotionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GRADEMODEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ORGANIZATIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEPROMOTIONID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static EmployeePromotion toModel(EmployeePromotionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EmployeePromotion model = new EmployeePromotionImpl();

		model.setEmployeePromotionId(soapModel.getEmployeePromotionId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setActive(soapModel.isActive());
		model.setPromotionDate(soapModel.getPromotionDate());
		model.setDesignationId(soapModel.getDesignationId());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setGradeId(soapModel.getGradeId());
		model.setGradeModeId(soapModel.getGradeModeId());
		model.setPromotionLetterId(soapModel.getPromotionLetterId());
		model.setOrganizationId(soapModel.getOrganizationId());
		model.setPersonalNo(soapModel.getPersonalNo());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<EmployeePromotion> toModels(
		EmployeePromotionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EmployeePromotion> models = new ArrayList<EmployeePromotion>(
			soapModels.length);

		for (EmployeePromotionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EmployeePromotionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeePromotionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeePromotionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeePromotionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeePromotion.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeePromotion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeePromotion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeePromotion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeePromotion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeePromotion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeePromotion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeePromotion, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeePromotion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeePromotion, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeePromotion, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EmployeePromotion>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EmployeePromotion.class.getClassLoader(), EmployeePromotion.class,
			ModelWrapper.class);

		try {
			Constructor<EmployeePromotion> constructor =
				(Constructor<EmployeePromotion>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EmployeePromotion, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EmployeePromotion, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EmployeePromotion, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EmployeePromotion, Object>>();
		Map<String, BiConsumer<EmployeePromotion, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<EmployeePromotion, ?>>();

		attributeGetterFunctions.put(
			"employeePromotionId", EmployeePromotion::getEmployeePromotionId);
		attributeSetterBiConsumers.put(
			"employeePromotionId",
			(BiConsumer<EmployeePromotion, Long>)
				EmployeePromotion::setEmployeePromotionId);
		attributeGetterFunctions.put("groupId", EmployeePromotion::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EmployeePromotion, Long>)EmployeePromotion::setGroupId);
		attributeGetterFunctions.put(
			"companyId", EmployeePromotion::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EmployeePromotion, Long>)
				EmployeePromotion::setCompanyId);
		attributeGetterFunctions.put("userId", EmployeePromotion::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EmployeePromotion, Long>)EmployeePromotion::setUserId);
		attributeGetterFunctions.put(
			"userName", EmployeePromotion::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EmployeePromotion, String>)
				EmployeePromotion::setUserName);
		attributeGetterFunctions.put(
			"createDate", EmployeePromotion::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EmployeePromotion, Date>)
				EmployeePromotion::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EmployeePromotion::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EmployeePromotion, Date>)
				EmployeePromotion::setModifiedDate);
		attributeGetterFunctions.put("active", EmployeePromotion::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<EmployeePromotion, Boolean>)
				EmployeePromotion::setActive);
		attributeGetterFunctions.put(
			"promotionDate", EmployeePromotion::getPromotionDate);
		attributeSetterBiConsumers.put(
			"promotionDate",
			(BiConsumer<EmployeePromotion, Date>)
				EmployeePromotion::setPromotionDate);
		attributeGetterFunctions.put(
			"designationId", EmployeePromotion::getDesignationId);
		attributeSetterBiConsumers.put(
			"designationId",
			(BiConsumer<EmployeePromotion, Long>)
				EmployeePromotion::setDesignationId);
		attributeGetterFunctions.put(
			"employeeId", EmployeePromotion::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId",
			(BiConsumer<EmployeePromotion, Long>)
				EmployeePromotion::setEmployeeId);
		attributeGetterFunctions.put("gradeId", EmployeePromotion::getGradeId);
		attributeSetterBiConsumers.put(
			"gradeId",
			(BiConsumer<EmployeePromotion, Long>)EmployeePromotion::setGradeId);
		attributeGetterFunctions.put(
			"gradeModeId", EmployeePromotion::getGradeModeId);
		attributeSetterBiConsumers.put(
			"gradeModeId",
			(BiConsumer<EmployeePromotion, Long>)
				EmployeePromotion::setGradeModeId);
		attributeGetterFunctions.put(
			"promotionLetterId", EmployeePromotion::getPromotionLetterId);
		attributeSetterBiConsumers.put(
			"promotionLetterId",
			(BiConsumer<EmployeePromotion, Long>)
				EmployeePromotion::setPromotionLetterId);
		attributeGetterFunctions.put(
			"organizationId", EmployeePromotion::getOrganizationId);
		attributeSetterBiConsumers.put(
			"organizationId",
			(BiConsumer<EmployeePromotion, Long>)
				EmployeePromotion::setOrganizationId);
		attributeGetterFunctions.put(
			"personalNo", EmployeePromotion::getPersonalNo);
		attributeSetterBiConsumers.put(
			"personalNo",
			(BiConsumer<EmployeePromotion, Long>)
				EmployeePromotion::setPersonalNo);
		attributeGetterFunctions.put("status", EmployeePromotion::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<EmployeePromotion, Integer>)
				EmployeePromotion::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getEmployeePromotionId() {
		return _employeePromotionId;
	}

	@Override
	public void setEmployeePromotionId(long employeePromotionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeePromotionId = employeePromotionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public Date getPromotionDate() {
		return _promotionDate;
	}

	@Override
	public void setPromotionDate(Date promotionDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_promotionDate = promotionDate;
	}

	@JSON
	@Override
	public long getDesignationId() {
		return _designationId;
	}

	@Override
	public void setDesignationId(long designationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designationId = designationId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public long getGradeId() {
		return _gradeId;
	}

	@Override
	public void setGradeId(long gradeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gradeId = gradeId;
	}

	@JSON
	@Override
	public long getGradeModeId() {
		return _gradeModeId;
	}

	@Override
	public void setGradeModeId(long gradeModeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gradeModeId = gradeModeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGradeModeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("gradeModeId"));
	}

	@JSON
	@Override
	public long getPromotionLetterId() {
		return _promotionLetterId;
	}

	@Override
	public void setPromotionLetterId(long promotionLetterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_promotionLetterId = promotionLetterId;
	}

	@JSON
	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organizationId = organizationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalOrganizationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("organizationId"));
	}

	@JSON
	@Override
	public long getPersonalNo() {
		return _personalNo;
	}

	@Override
	public void setPersonalNo(long personalNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_personalNo = personalNo;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeePromotion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeePromotion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeePromotion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeePromotionImpl employeePromotionImpl =
			new EmployeePromotionImpl();

		employeePromotionImpl.setEmployeePromotionId(getEmployeePromotionId());
		employeePromotionImpl.setGroupId(getGroupId());
		employeePromotionImpl.setCompanyId(getCompanyId());
		employeePromotionImpl.setUserId(getUserId());
		employeePromotionImpl.setUserName(getUserName());
		employeePromotionImpl.setCreateDate(getCreateDate());
		employeePromotionImpl.setModifiedDate(getModifiedDate());
		employeePromotionImpl.setActive(isActive());
		employeePromotionImpl.setPromotionDate(getPromotionDate());
		employeePromotionImpl.setDesignationId(getDesignationId());
		employeePromotionImpl.setEmployeeId(getEmployeeId());
		employeePromotionImpl.setGradeId(getGradeId());
		employeePromotionImpl.setGradeModeId(getGradeModeId());
		employeePromotionImpl.setPromotionLetterId(getPromotionLetterId());
		employeePromotionImpl.setOrganizationId(getOrganizationId());
		employeePromotionImpl.setPersonalNo(getPersonalNo());
		employeePromotionImpl.setStatus(getStatus());

		employeePromotionImpl.resetOriginalValues();

		return employeePromotionImpl;
	}

	@Override
	public int compareTo(EmployeePromotion employeePromotion) {
		long primaryKey = employeePromotion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeePromotion)) {
			return false;
		}

		EmployeePromotion employeePromotion = (EmployeePromotion)object;

		long primaryKey = employeePromotion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeePromotion> toCacheModel() {
		EmployeePromotionCacheModel employeePromotionCacheModel =
			new EmployeePromotionCacheModel();

		employeePromotionCacheModel.employeePromotionId =
			getEmployeePromotionId();

		employeePromotionCacheModel.groupId = getGroupId();

		employeePromotionCacheModel.companyId = getCompanyId();

		employeePromotionCacheModel.userId = getUserId();

		employeePromotionCacheModel.userName = getUserName();

		String userName = employeePromotionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			employeePromotionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeePromotionCacheModel.createDate = createDate.getTime();
		}
		else {
			employeePromotionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeePromotionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeePromotionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeePromotionCacheModel.active = isActive();

		Date promotionDate = getPromotionDate();

		if (promotionDate != null) {
			employeePromotionCacheModel.promotionDate = promotionDate.getTime();
		}
		else {
			employeePromotionCacheModel.promotionDate = Long.MIN_VALUE;
		}

		employeePromotionCacheModel.designationId = getDesignationId();

		employeePromotionCacheModel.employeeId = getEmployeeId();

		employeePromotionCacheModel.gradeId = getGradeId();

		employeePromotionCacheModel.gradeModeId = getGradeModeId();

		employeePromotionCacheModel.promotionLetterId = getPromotionLetterId();

		employeePromotionCacheModel.organizationId = getOrganizationId();

		employeePromotionCacheModel.personalNo = getPersonalNo();

		employeePromotionCacheModel.status = getStatus();

		return employeePromotionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeePromotion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeePromotion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeePromotion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EmployeePromotion)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EmployeePromotion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EmployeePromotion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeePromotion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EmployeePromotion)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeePromotion>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _employeePromotionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _active;
	private Date _promotionDate;
	private long _designationId;
	private long _employeeId;
	private long _gradeId;
	private long _gradeModeId;
	private long _promotionLetterId;
	private long _organizationId;
	private long _personalNo;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeePromotion, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeePromotion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("employeePromotionId", _employeePromotionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("promotionDate", _promotionDate);
		_columnOriginalValues.put("designationId", _designationId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("gradeId", _gradeId);
		_columnOriginalValues.put("gradeModeId", _gradeModeId);
		_columnOriginalValues.put("promotionLetterId", _promotionLetterId);
		_columnOriginalValues.put("organizationId", _organizationId);
		_columnOriginalValues.put("personalNo", _personalNo);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("employeePromotionId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("active_", 128L);

		columnBitmasks.put("promotionDate", 256L);

		columnBitmasks.put("designationId", 512L);

		columnBitmasks.put("employeeId", 1024L);

		columnBitmasks.put("gradeId", 2048L);

		columnBitmasks.put("gradeModeId", 4096L);

		columnBitmasks.put("promotionLetterId", 8192L);

		columnBitmasks.put("organizationId", 16384L);

		columnBitmasks.put("personalNo", 32768L);

		columnBitmasks.put("status", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeePromotion _escapedModel;

}