/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model.impl;

import com.adjecti.pis.liferay.model.EmployeeDocument;
import com.adjecti.pis.liferay.model.EmployeeDocumentModel;
import com.adjecti.pis.liferay.model.EmployeeDocumentSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeDocument service. Represents a row in the &quot;pis_EmployeeDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeDocumentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeDocumentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDocumentImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeDocumentModelImpl
	extends BaseModelImpl<EmployeeDocument> implements EmployeeDocumentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee document model instance should use the <code>EmployeeDocument</code> interface instead.
	 */
	public static final String TABLE_NAME = "pis_EmployeeDocument";

	public static final Object[][] TABLE_COLUMNS = {
		{"employeeDocumentId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"active_", Types.BOOLEAN},
		{"documentId", Types.BIGINT}, {"employeeId", Types.BIGINT},
		{"title", Types.VARCHAR}, {"documentTypeId", Types.BIGINT},
		{"discription", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("employeeDocumentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("documentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("discription", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table pis_EmployeeDocument (employeeDocumentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,active_ BOOLEAN,documentId LONG,employeeId LONG,title VARCHAR(75) null,documentTypeId LONG,discription VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table pis_EmployeeDocument";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeDocument.employeeDocumentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY pis_EmployeeDocument.employeeDocumentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long DOCUMENTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEDOCUMENTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static EmployeeDocument toModel(EmployeeDocumentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EmployeeDocument model = new EmployeeDocumentImpl();

		model.setEmployeeDocumentId(soapModel.getEmployeeDocumentId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setActive(soapModel.isActive());
		model.setDocumentId(soapModel.getDocumentId());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setTitle(soapModel.getTitle());
		model.setDocumentTypeId(soapModel.getDocumentTypeId());
		model.setDiscription(soapModel.getDiscription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<EmployeeDocument> toModels(
		EmployeeDocumentSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EmployeeDocument> models = new ArrayList<EmployeeDocument>(
			soapModels.length);

		for (EmployeeDocumentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EmployeeDocumentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeDocumentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeDocumentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeDocumentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeDocument.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeDocument.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeDocument, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeDocument, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDocument, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeDocument)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeDocument, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeDocument, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeDocument)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeDocument, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeDocument, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EmployeeDocument>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EmployeeDocument.class.getClassLoader(), EmployeeDocument.class,
			ModelWrapper.class);

		try {
			Constructor<EmployeeDocument> constructor =
				(Constructor<EmployeeDocument>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EmployeeDocument, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EmployeeDocument, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EmployeeDocument, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<EmployeeDocument, Object>>();
		Map<String, BiConsumer<EmployeeDocument, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<EmployeeDocument, ?>>();

		attributeGetterFunctions.put(
			"employeeDocumentId", EmployeeDocument::getEmployeeDocumentId);
		attributeSetterBiConsumers.put(
			"employeeDocumentId",
			(BiConsumer<EmployeeDocument, Long>)
				EmployeeDocument::setEmployeeDocumentId);
		attributeGetterFunctions.put("groupId", EmployeeDocument::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EmployeeDocument, Long>)EmployeeDocument::setGroupId);
		attributeGetterFunctions.put(
			"companyId", EmployeeDocument::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EmployeeDocument, Long>)EmployeeDocument::setCompanyId);
		attributeGetterFunctions.put("userId", EmployeeDocument::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EmployeeDocument, Long>)EmployeeDocument::setUserId);
		attributeGetterFunctions.put("userName", EmployeeDocument::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EmployeeDocument, String>)
				EmployeeDocument::setUserName);
		attributeGetterFunctions.put(
			"createDate", EmployeeDocument::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EmployeeDocument, Date>)
				EmployeeDocument::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EmployeeDocument::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EmployeeDocument, Date>)
				EmployeeDocument::setModifiedDate);
		attributeGetterFunctions.put("active", EmployeeDocument::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<EmployeeDocument, Boolean>)EmployeeDocument::setActive);
		attributeGetterFunctions.put(
			"documentId", EmployeeDocument::getDocumentId);
		attributeSetterBiConsumers.put(
			"documentId",
			(BiConsumer<EmployeeDocument, Long>)
				EmployeeDocument::setDocumentId);
		attributeGetterFunctions.put(
			"employeeId", EmployeeDocument::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId",
			(BiConsumer<EmployeeDocument, Long>)
				EmployeeDocument::setEmployeeId);
		attributeGetterFunctions.put("title", EmployeeDocument::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<EmployeeDocument, String>)EmployeeDocument::setTitle);
		attributeGetterFunctions.put(
			"documentTypeId", EmployeeDocument::getDocumentTypeId);
		attributeSetterBiConsumers.put(
			"documentTypeId",
			(BiConsumer<EmployeeDocument, Long>)
				EmployeeDocument::setDocumentTypeId);
		attributeGetterFunctions.put(
			"discription", EmployeeDocument::getDiscription);
		attributeSetterBiConsumers.put(
			"discription",
			(BiConsumer<EmployeeDocument, String>)
				EmployeeDocument::setDiscription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getEmployeeDocumentId() {
		return _employeeDocumentId;
	}

	@Override
	public void setEmployeeDocumentId(long employeeDocumentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeDocumentId = employeeDocumentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getDocumentId() {
		return _documentId;
	}

	@Override
	public void setDocumentId(long documentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentId = documentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDocumentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("documentId"));
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public long getDocumentTypeId() {
		return _documentTypeId;
	}

	@Override
	public void setDocumentTypeId(long documentTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentTypeId = documentTypeId;
	}

	@JSON
	@Override
	public String getDiscription() {
		if (_discription == null) {
			return "";
		}
		else {
			return _discription;
		}
	}

	@Override
	public void setDiscription(String discription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_discription = discription;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeDocument.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeDocument toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeDocument>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeDocumentImpl employeeDocumentImpl = new EmployeeDocumentImpl();

		employeeDocumentImpl.setEmployeeDocumentId(getEmployeeDocumentId());
		employeeDocumentImpl.setGroupId(getGroupId());
		employeeDocumentImpl.setCompanyId(getCompanyId());
		employeeDocumentImpl.setUserId(getUserId());
		employeeDocumentImpl.setUserName(getUserName());
		employeeDocumentImpl.setCreateDate(getCreateDate());
		employeeDocumentImpl.setModifiedDate(getModifiedDate());
		employeeDocumentImpl.setActive(isActive());
		employeeDocumentImpl.setDocumentId(getDocumentId());
		employeeDocumentImpl.setEmployeeId(getEmployeeId());
		employeeDocumentImpl.setTitle(getTitle());
		employeeDocumentImpl.setDocumentTypeId(getDocumentTypeId());
		employeeDocumentImpl.setDiscription(getDiscription());

		employeeDocumentImpl.resetOriginalValues();

		return employeeDocumentImpl;
	}

	@Override
	public int compareTo(EmployeeDocument employeeDocument) {
		long primaryKey = employeeDocument.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeDocument)) {
			return false;
		}

		EmployeeDocument employeeDocument = (EmployeeDocument)object;

		long primaryKey = employeeDocument.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeDocument> toCacheModel() {
		EmployeeDocumentCacheModel employeeDocumentCacheModel =
			new EmployeeDocumentCacheModel();

		employeeDocumentCacheModel.employeeDocumentId = getEmployeeDocumentId();

		employeeDocumentCacheModel.groupId = getGroupId();

		employeeDocumentCacheModel.companyId = getCompanyId();

		employeeDocumentCacheModel.userId = getUserId();

		employeeDocumentCacheModel.userName = getUserName();

		String userName = employeeDocumentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			employeeDocumentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeDocumentCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeDocumentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeDocumentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeDocumentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeDocumentCacheModel.active = isActive();

		employeeDocumentCacheModel.documentId = getDocumentId();

		employeeDocumentCacheModel.employeeId = getEmployeeId();

		employeeDocumentCacheModel.title = getTitle();

		String title = employeeDocumentCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			employeeDocumentCacheModel.title = null;
		}

		employeeDocumentCacheModel.documentTypeId = getDocumentTypeId();

		employeeDocumentCacheModel.discription = getDiscription();

		String discription = employeeDocumentCacheModel.discription;

		if ((discription != null) && (discription.length() == 0)) {
			employeeDocumentCacheModel.discription = null;
		}

		return employeeDocumentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeDocument, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeDocument, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDocument, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EmployeeDocument)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EmployeeDocument, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EmployeeDocument, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDocument, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EmployeeDocument)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeDocument>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _employeeDocumentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _active;
	private long _documentId;
	private long _employeeId;
	private String _title;
	private long _documentTypeId;
	private String _discription;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeDocument, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeDocument)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("employeeDocumentId", _employeeDocumentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("documentId", _documentId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("documentTypeId", _documentTypeId);
		_columnOriginalValues.put("discription", _discription);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("employeeDocumentId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("active_", 128L);

		columnBitmasks.put("documentId", 256L);

		columnBitmasks.put("employeeId", 512L);

		columnBitmasks.put("title", 1024L);

		columnBitmasks.put("documentTypeId", 2048L);

		columnBitmasks.put("discription", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeDocument _escapedModel;

}