/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model.impl;

import com.adjecti.pis.liferay.model.EmployeePastExperience;
import com.adjecti.pis.liferay.model.EmployeePastExperienceModel;
import com.adjecti.pis.liferay.model.EmployeePastExperienceSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeePastExperience service. Represents a row in the &quot;pis_EmployeePastExperience&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeePastExperienceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeePastExperienceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeePastExperienceImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeePastExperienceModelImpl
	extends BaseModelImpl<EmployeePastExperience>
	implements EmployeePastExperienceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee past experience model instance should use the <code>EmployeePastExperience</code> interface instead.
	 */
	public static final String TABLE_NAME = "pis_EmployeePastExperience";

	public static final Object[][] TABLE_COLUMNS = {
		{"employeePastExperienceId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"active_", Types.BOOLEAN},
		{"fromDate", Types.TIMESTAMP}, {"toDate", Types.TIMESTAMP},
		{"organization", Types.VARCHAR}, {"employeeId", Types.BIGINT},
		{"experienceLetterId", Types.BIGINT}, {"workAreaId", Types.BIGINT},
		{"designation", Types.VARCHAR}, {"joiningProcessId", Types.BIGINT},
		{"exServiceMan", Types.BOOLEAN}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("employeePastExperienceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("fromDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("toDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("organization", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("experienceLetterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workAreaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("designation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("joiningProcessId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("exServiceMan", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table pis_EmployeePastExperience (employeePastExperienceId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,active_ BOOLEAN,fromDate DATE null,toDate DATE null,organization VARCHAR(75) null,employeeId LONG,experienceLetterId LONG,workAreaId LONG,designation VARCHAR(75) null,joiningProcessId LONG,exServiceMan BOOLEAN,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table pis_EmployeePastExperience";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeePastExperience.employeePastExperienceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY pis_EmployeePastExperience.employeePastExperienceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long JOININGPROCESSID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long WORKAREAID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EMPLOYEEPASTEXPERIENCEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static EmployeePastExperience toModel(
		EmployeePastExperienceSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		EmployeePastExperience model = new EmployeePastExperienceImpl();

		model.setEmployeePastExperienceId(
			soapModel.getEmployeePastExperienceId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setActive(soapModel.isActive());
		model.setFromDate(soapModel.getFromDate());
		model.setToDate(soapModel.getToDate());
		model.setOrganization(soapModel.getOrganization());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setExperienceLetterId(soapModel.getExperienceLetterId());
		model.setWorkAreaId(soapModel.getWorkAreaId());
		model.setDesignation(soapModel.getDesignation());
		model.setJoiningProcessId(soapModel.getJoiningProcessId());
		model.setExServiceMan(soapModel.isExServiceMan());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<EmployeePastExperience> toModels(
		EmployeePastExperienceSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EmployeePastExperience> models =
			new ArrayList<EmployeePastExperience>(soapModels.length);

		for (EmployeePastExperienceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EmployeePastExperienceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeePastExperienceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeePastExperienceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeePastExperienceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeePastExperience.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeePastExperience.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeePastExperience, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeePastExperience, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeePastExperience, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeePastExperience)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeePastExperience, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeePastExperience, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeePastExperience)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeePastExperience, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeePastExperience, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EmployeePastExperience>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EmployeePastExperience.class.getClassLoader(),
			EmployeePastExperience.class, ModelWrapper.class);

		try {
			Constructor<EmployeePastExperience> constructor =
				(Constructor<EmployeePastExperience>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EmployeePastExperience, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EmployeePastExperience, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EmployeePastExperience, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EmployeePastExperience, Object>>();
		Map<String, BiConsumer<EmployeePastExperience, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<EmployeePastExperience, ?>>();

		attributeGetterFunctions.put(
			"employeePastExperienceId",
			EmployeePastExperience::getEmployeePastExperienceId);
		attributeSetterBiConsumers.put(
			"employeePastExperienceId",
			(BiConsumer<EmployeePastExperience, Long>)
				EmployeePastExperience::setEmployeePastExperienceId);
		attributeGetterFunctions.put(
			"groupId", EmployeePastExperience::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EmployeePastExperience, Long>)
				EmployeePastExperience::setGroupId);
		attributeGetterFunctions.put(
			"companyId", EmployeePastExperience::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EmployeePastExperience, Long>)
				EmployeePastExperience::setCompanyId);
		attributeGetterFunctions.put(
			"userId", EmployeePastExperience::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EmployeePastExperience, Long>)
				EmployeePastExperience::setUserId);
		attributeGetterFunctions.put(
			"userName", EmployeePastExperience::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EmployeePastExperience, String>)
				EmployeePastExperience::setUserName);
		attributeGetterFunctions.put(
			"createDate", EmployeePastExperience::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EmployeePastExperience, Date>)
				EmployeePastExperience::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EmployeePastExperience::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EmployeePastExperience, Date>)
				EmployeePastExperience::setModifiedDate);
		attributeGetterFunctions.put(
			"active", EmployeePastExperience::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<EmployeePastExperience, Boolean>)
				EmployeePastExperience::setActive);
		attributeGetterFunctions.put(
			"fromDate", EmployeePastExperience::getFromDate);
		attributeSetterBiConsumers.put(
			"fromDate",
			(BiConsumer<EmployeePastExperience, Date>)
				EmployeePastExperience::setFromDate);
		attributeGetterFunctions.put(
			"toDate", EmployeePastExperience::getToDate);
		attributeSetterBiConsumers.put(
			"toDate",
			(BiConsumer<EmployeePastExperience, Date>)
				EmployeePastExperience::setToDate);
		attributeGetterFunctions.put(
			"organization", EmployeePastExperience::getOrganization);
		attributeSetterBiConsumers.put(
			"organization",
			(BiConsumer<EmployeePastExperience, String>)
				EmployeePastExperience::setOrganization);
		attributeGetterFunctions.put(
			"employeeId", EmployeePastExperience::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId",
			(BiConsumer<EmployeePastExperience, Long>)
				EmployeePastExperience::setEmployeeId);
		attributeGetterFunctions.put(
			"experienceLetterId",
			EmployeePastExperience::getExperienceLetterId);
		attributeSetterBiConsumers.put(
			"experienceLetterId",
			(BiConsumer<EmployeePastExperience, Long>)
				EmployeePastExperience::setExperienceLetterId);
		attributeGetterFunctions.put(
			"workAreaId", EmployeePastExperience::getWorkAreaId);
		attributeSetterBiConsumers.put(
			"workAreaId",
			(BiConsumer<EmployeePastExperience, Long>)
				EmployeePastExperience::setWorkAreaId);
		attributeGetterFunctions.put(
			"designation", EmployeePastExperience::getDesignation);
		attributeSetterBiConsumers.put(
			"designation",
			(BiConsumer<EmployeePastExperience, String>)
				EmployeePastExperience::setDesignation);
		attributeGetterFunctions.put(
			"joiningProcessId", EmployeePastExperience::getJoiningProcessId);
		attributeSetterBiConsumers.put(
			"joiningProcessId",
			(BiConsumer<EmployeePastExperience, Long>)
				EmployeePastExperience::setJoiningProcessId);
		attributeGetterFunctions.put(
			"exServiceMan", EmployeePastExperience::getExServiceMan);
		attributeSetterBiConsumers.put(
			"exServiceMan",
			(BiConsumer<EmployeePastExperience, Boolean>)
				EmployeePastExperience::setExServiceMan);
		attributeGetterFunctions.put(
			"status", EmployeePastExperience::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<EmployeePastExperience, Integer>)
				EmployeePastExperience::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getEmployeePastExperienceId() {
		return _employeePastExperienceId;
	}

	@Override
	public void setEmployeePastExperienceId(long employeePastExperienceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeePastExperienceId = employeePastExperienceId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public Date getFromDate() {
		return _fromDate;
	}

	@Override
	public void setFromDate(Date fromDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fromDate = fromDate;
	}

	@JSON
	@Override
	public Date getToDate() {
		return _toDate;
	}

	@Override
	public void setToDate(Date toDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_toDate = toDate;
	}

	@JSON
	@Override
	public String getOrganization() {
		if (_organization == null) {
			return "";
		}
		else {
			return _organization;
		}
	}

	@Override
	public void setOrganization(String organization) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organization = organization;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public long getExperienceLetterId() {
		return _experienceLetterId;
	}

	@Override
	public void setExperienceLetterId(long experienceLetterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_experienceLetterId = experienceLetterId;
	}

	@JSON
	@Override
	public long getWorkAreaId() {
		return _workAreaId;
	}

	@Override
	public void setWorkAreaId(long workAreaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workAreaId = workAreaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalWorkAreaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("workAreaId"));
	}

	@JSON
	@Override
	public String getDesignation() {
		if (_designation == null) {
			return "";
		}
		else {
			return _designation;
		}
	}

	@Override
	public void setDesignation(String designation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designation = designation;
	}

	@JSON
	@Override
	public long getJoiningProcessId() {
		return _joiningProcessId;
	}

	@Override
	public void setJoiningProcessId(long joiningProcessId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_joiningProcessId = joiningProcessId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalJoiningProcessId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("joiningProcessId"));
	}

	@JSON
	@Override
	public boolean getExServiceMan() {
		return _exServiceMan;
	}

	@JSON
	@Override
	public boolean isExServiceMan() {
		return _exServiceMan;
	}

	@Override
	public void setExServiceMan(boolean exServiceMan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_exServiceMan = exServiceMan;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeePastExperience.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeePastExperience toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeePastExperience>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeePastExperienceImpl employeePastExperienceImpl =
			new EmployeePastExperienceImpl();

		employeePastExperienceImpl.setEmployeePastExperienceId(
			getEmployeePastExperienceId());
		employeePastExperienceImpl.setGroupId(getGroupId());
		employeePastExperienceImpl.setCompanyId(getCompanyId());
		employeePastExperienceImpl.setUserId(getUserId());
		employeePastExperienceImpl.setUserName(getUserName());
		employeePastExperienceImpl.setCreateDate(getCreateDate());
		employeePastExperienceImpl.setModifiedDate(getModifiedDate());
		employeePastExperienceImpl.setActive(isActive());
		employeePastExperienceImpl.setFromDate(getFromDate());
		employeePastExperienceImpl.setToDate(getToDate());
		employeePastExperienceImpl.setOrganization(getOrganization());
		employeePastExperienceImpl.setEmployeeId(getEmployeeId());
		employeePastExperienceImpl.setExperienceLetterId(
			getExperienceLetterId());
		employeePastExperienceImpl.setWorkAreaId(getWorkAreaId());
		employeePastExperienceImpl.setDesignation(getDesignation());
		employeePastExperienceImpl.setJoiningProcessId(getJoiningProcessId());
		employeePastExperienceImpl.setExServiceMan(isExServiceMan());
		employeePastExperienceImpl.setStatus(getStatus());

		employeePastExperienceImpl.resetOriginalValues();

		return employeePastExperienceImpl;
	}

	@Override
	public int compareTo(EmployeePastExperience employeePastExperience) {
		long primaryKey = employeePastExperience.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeePastExperience)) {
			return false;
		}

		EmployeePastExperience employeePastExperience =
			(EmployeePastExperience)object;

		long primaryKey = employeePastExperience.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeePastExperience> toCacheModel() {
		EmployeePastExperienceCacheModel employeePastExperienceCacheModel =
			new EmployeePastExperienceCacheModel();

		employeePastExperienceCacheModel.employeePastExperienceId =
			getEmployeePastExperienceId();

		employeePastExperienceCacheModel.groupId = getGroupId();

		employeePastExperienceCacheModel.companyId = getCompanyId();

		employeePastExperienceCacheModel.userId = getUserId();

		employeePastExperienceCacheModel.userName = getUserName();

		String userName = employeePastExperienceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			employeePastExperienceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeePastExperienceCacheModel.createDate = createDate.getTime();
		}
		else {
			employeePastExperienceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeePastExperienceCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			employeePastExperienceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeePastExperienceCacheModel.active = isActive();

		Date fromDate = getFromDate();

		if (fromDate != null) {
			employeePastExperienceCacheModel.fromDate = fromDate.getTime();
		}
		else {
			employeePastExperienceCacheModel.fromDate = Long.MIN_VALUE;
		}

		Date toDate = getToDate();

		if (toDate != null) {
			employeePastExperienceCacheModel.toDate = toDate.getTime();
		}
		else {
			employeePastExperienceCacheModel.toDate = Long.MIN_VALUE;
		}

		employeePastExperienceCacheModel.organization = getOrganization();

		String organization = employeePastExperienceCacheModel.organization;

		if ((organization != null) && (organization.length() == 0)) {
			employeePastExperienceCacheModel.organization = null;
		}

		employeePastExperienceCacheModel.employeeId = getEmployeeId();

		employeePastExperienceCacheModel.experienceLetterId =
			getExperienceLetterId();

		employeePastExperienceCacheModel.workAreaId = getWorkAreaId();

		employeePastExperienceCacheModel.designation = getDesignation();

		String designation = employeePastExperienceCacheModel.designation;

		if ((designation != null) && (designation.length() == 0)) {
			employeePastExperienceCacheModel.designation = null;
		}

		employeePastExperienceCacheModel.joiningProcessId =
			getJoiningProcessId();

		employeePastExperienceCacheModel.exServiceMan = isExServiceMan();

		employeePastExperienceCacheModel.status = getStatus();

		return employeePastExperienceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeePastExperience, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeePastExperience, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeePastExperience, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((EmployeePastExperience)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EmployeePastExperience, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EmployeePastExperience, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeePastExperience, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((EmployeePastExperience)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeePastExperience>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _employeePastExperienceId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _active;
	private Date _fromDate;
	private Date _toDate;
	private String _organization;
	private long _employeeId;
	private long _experienceLetterId;
	private long _workAreaId;
	private String _designation;
	private long _joiningProcessId;
	private boolean _exServiceMan;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeePastExperience, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeePastExperience)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"employeePastExperienceId", _employeePastExperienceId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("fromDate", _fromDate);
		_columnOriginalValues.put("toDate", _toDate);
		_columnOriginalValues.put("organization", _organization);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("experienceLetterId", _experienceLetterId);
		_columnOriginalValues.put("workAreaId", _workAreaId);
		_columnOriginalValues.put("designation", _designation);
		_columnOriginalValues.put("joiningProcessId", _joiningProcessId);
		_columnOriginalValues.put("exServiceMan", _exServiceMan);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("employeePastExperienceId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("active_", 128L);

		columnBitmasks.put("fromDate", 256L);

		columnBitmasks.put("toDate", 512L);

		columnBitmasks.put("organization", 1024L);

		columnBitmasks.put("employeeId", 2048L);

		columnBitmasks.put("experienceLetterId", 4096L);

		columnBitmasks.put("workAreaId", 8192L);

		columnBitmasks.put("designation", 16384L);

		columnBitmasks.put("joiningProcessId", 32768L);

		columnBitmasks.put("exServiceMan", 65536L);

		columnBitmasks.put("status", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeePastExperience _escapedModel;

}