/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model.impl;

import com.adjecti.pis.liferay.model.FamilyBenefitScheme;
import com.adjecti.pis.liferay.model.FamilyBenefitSchemeModel;
import com.adjecti.pis.liferay.model.FamilyBenefitSchemeSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FamilyBenefitScheme service. Represents a row in the &quot;pis_FamilyBenefitScheme&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FamilyBenefitSchemeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FamilyBenefitSchemeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FamilyBenefitSchemeImpl
 * @generated
 */
@JSON(strict = true)
public class FamilyBenefitSchemeModelImpl
	extends BaseModelImpl<FamilyBenefitScheme>
	implements FamilyBenefitSchemeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a family benefit scheme model instance should use the <code>FamilyBenefitScheme</code> interface instead.
	 */
	public static final String TABLE_NAME = "pis_FamilyBenefitScheme";

	public static final Object[][] TABLE_COLUMNS = {
		{"familyBenefitSchemeId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"percentage", Types.FLOAT},
		{"familyMemberId", Types.BIGINT}, {"benefitSchemeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("familyBenefitSchemeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("percentage", Types.FLOAT);
		TABLE_COLUMNS_MAP.put("familyMemberId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("benefitSchemeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table pis_FamilyBenefitScheme (familyBenefitSchemeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,percentage DOUBLE,familyMemberId LONG,benefitSchemeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table pis_FamilyBenefitScheme";

	public static final String ORDER_BY_JPQL =
		" ORDER BY familyBenefitScheme.familyBenefitSchemeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY pis_FamilyBenefitScheme.familyBenefitSchemeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long FAMILYBENEFITSCHEMEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static FamilyBenefitScheme toModel(
		FamilyBenefitSchemeSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		FamilyBenefitScheme model = new FamilyBenefitSchemeImpl();

		model.setFamilyBenefitSchemeId(soapModel.getFamilyBenefitSchemeId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPercentage(soapModel.getPercentage());
		model.setFamilyMemberId(soapModel.getFamilyMemberId());
		model.setBenefitSchemeId(soapModel.getBenefitSchemeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<FamilyBenefitScheme> toModels(
		FamilyBenefitSchemeSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<FamilyBenefitScheme> models = new ArrayList<FamilyBenefitScheme>(
			soapModels.length);

		for (FamilyBenefitSchemeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public FamilyBenefitSchemeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _familyBenefitSchemeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFamilyBenefitSchemeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _familyBenefitSchemeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FamilyBenefitScheme.class;
	}

	@Override
	public String getModelClassName() {
		return FamilyBenefitScheme.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FamilyBenefitScheme, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FamilyBenefitScheme, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FamilyBenefitScheme, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FamilyBenefitScheme)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FamilyBenefitScheme, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FamilyBenefitScheme, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FamilyBenefitScheme)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FamilyBenefitScheme, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FamilyBenefitScheme, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, FamilyBenefitScheme>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			FamilyBenefitScheme.class.getClassLoader(),
			FamilyBenefitScheme.class, ModelWrapper.class);

		try {
			Constructor<FamilyBenefitScheme> constructor =
				(Constructor<FamilyBenefitScheme>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<FamilyBenefitScheme, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FamilyBenefitScheme, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FamilyBenefitScheme, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FamilyBenefitScheme, Object>>();
		Map<String, BiConsumer<FamilyBenefitScheme, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FamilyBenefitScheme, ?>>();

		attributeGetterFunctions.put(
			"familyBenefitSchemeId",
			FamilyBenefitScheme::getFamilyBenefitSchemeId);
		attributeSetterBiConsumers.put(
			"familyBenefitSchemeId",
			(BiConsumer<FamilyBenefitScheme, Long>)
				FamilyBenefitScheme::setFamilyBenefitSchemeId);
		attributeGetterFunctions.put(
			"groupId", FamilyBenefitScheme::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FamilyBenefitScheme, Long>)
				FamilyBenefitScheme::setGroupId);
		attributeGetterFunctions.put(
			"companyId", FamilyBenefitScheme::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FamilyBenefitScheme, Long>)
				FamilyBenefitScheme::setCompanyId);
		attributeGetterFunctions.put("userId", FamilyBenefitScheme::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<FamilyBenefitScheme, Long>)
				FamilyBenefitScheme::setUserId);
		attributeGetterFunctions.put(
			"userName", FamilyBenefitScheme::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FamilyBenefitScheme, String>)
				FamilyBenefitScheme::setUserName);
		attributeGetterFunctions.put(
			"createDate", FamilyBenefitScheme::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FamilyBenefitScheme, Date>)
				FamilyBenefitScheme::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FamilyBenefitScheme::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FamilyBenefitScheme, Date>)
				FamilyBenefitScheme::setModifiedDate);
		attributeGetterFunctions.put(
			"percentage", FamilyBenefitScheme::getPercentage);
		attributeSetterBiConsumers.put(
			"percentage",
			(BiConsumer<FamilyBenefitScheme, Float>)
				FamilyBenefitScheme::setPercentage);
		attributeGetterFunctions.put(
			"familyMemberId", FamilyBenefitScheme::getFamilyMemberId);
		attributeSetterBiConsumers.put(
			"familyMemberId",
			(BiConsumer<FamilyBenefitScheme, Long>)
				FamilyBenefitScheme::setFamilyMemberId);
		attributeGetterFunctions.put(
			"benefitSchemeId", FamilyBenefitScheme::getBenefitSchemeId);
		attributeSetterBiConsumers.put(
			"benefitSchemeId",
			(BiConsumer<FamilyBenefitScheme, Long>)
				FamilyBenefitScheme::setBenefitSchemeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getFamilyBenefitSchemeId() {
		return _familyBenefitSchemeId;
	}

	@Override
	public void setFamilyBenefitSchemeId(long familyBenefitSchemeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_familyBenefitSchemeId = familyBenefitSchemeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public float getPercentage() {
		return _percentage;
	}

	@Override
	public void setPercentage(float percentage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_percentage = percentage;
	}

	@JSON
	@Override
	public long getFamilyMemberId() {
		return _familyMemberId;
	}

	@Override
	public void setFamilyMemberId(long familyMemberId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_familyMemberId = familyMemberId;
	}

	@JSON
	@Override
	public long getBenefitSchemeId() {
		return _benefitSchemeId;
	}

	@Override
	public void setBenefitSchemeId(long benefitSchemeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitSchemeId = benefitSchemeId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FamilyBenefitScheme.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FamilyBenefitScheme toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FamilyBenefitScheme>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FamilyBenefitSchemeImpl familyBenefitSchemeImpl =
			new FamilyBenefitSchemeImpl();

		familyBenefitSchemeImpl.setFamilyBenefitSchemeId(
			getFamilyBenefitSchemeId());
		familyBenefitSchemeImpl.setGroupId(getGroupId());
		familyBenefitSchemeImpl.setCompanyId(getCompanyId());
		familyBenefitSchemeImpl.setUserId(getUserId());
		familyBenefitSchemeImpl.setUserName(getUserName());
		familyBenefitSchemeImpl.setCreateDate(getCreateDate());
		familyBenefitSchemeImpl.setModifiedDate(getModifiedDate());
		familyBenefitSchemeImpl.setPercentage(getPercentage());
		familyBenefitSchemeImpl.setFamilyMemberId(getFamilyMemberId());
		familyBenefitSchemeImpl.setBenefitSchemeId(getBenefitSchemeId());

		familyBenefitSchemeImpl.resetOriginalValues();

		return familyBenefitSchemeImpl;
	}

	@Override
	public int compareTo(FamilyBenefitScheme familyBenefitScheme) {
		long primaryKey = familyBenefitScheme.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FamilyBenefitScheme)) {
			return false;
		}

		FamilyBenefitScheme familyBenefitScheme = (FamilyBenefitScheme)object;

		long primaryKey = familyBenefitScheme.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FamilyBenefitScheme> toCacheModel() {
		FamilyBenefitSchemeCacheModel familyBenefitSchemeCacheModel =
			new FamilyBenefitSchemeCacheModel();

		familyBenefitSchemeCacheModel.familyBenefitSchemeId =
			getFamilyBenefitSchemeId();

		familyBenefitSchemeCacheModel.groupId = getGroupId();

		familyBenefitSchemeCacheModel.companyId = getCompanyId();

		familyBenefitSchemeCacheModel.userId = getUserId();

		familyBenefitSchemeCacheModel.userName = getUserName();

		String userName = familyBenefitSchemeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			familyBenefitSchemeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			familyBenefitSchemeCacheModel.createDate = createDate.getTime();
		}
		else {
			familyBenefitSchemeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			familyBenefitSchemeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			familyBenefitSchemeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		familyBenefitSchemeCacheModel.percentage = getPercentage();

		familyBenefitSchemeCacheModel.familyMemberId = getFamilyMemberId();

		familyBenefitSchemeCacheModel.benefitSchemeId = getBenefitSchemeId();

		return familyBenefitSchemeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FamilyBenefitScheme, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FamilyBenefitScheme, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FamilyBenefitScheme, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((FamilyBenefitScheme)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FamilyBenefitScheme, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FamilyBenefitScheme, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FamilyBenefitScheme, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((FamilyBenefitScheme)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FamilyBenefitScheme>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _familyBenefitSchemeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private float _percentage;
	private long _familyMemberId;
	private long _benefitSchemeId;

	public <T> T getColumnValue(String columnName) {
		Function<FamilyBenefitScheme, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FamilyBenefitScheme)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"familyBenefitSchemeId", _familyBenefitSchemeId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("percentage", _percentage);
		_columnOriginalValues.put("familyMemberId", _familyMemberId);
		_columnOriginalValues.put("benefitSchemeId", _benefitSchemeId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("familyBenefitSchemeId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("percentage", 128L);

		columnBitmasks.put("familyMemberId", 256L);

		columnBitmasks.put("benefitSchemeId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FamilyBenefitScheme _escapedModel;

}