/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.pis.liferay.model.impl;

import com.adjecti.pis.liferay.model.MonthlySalary;
import com.adjecti.pis.liferay.model.MonthlySalaryModel;
import com.adjecti.pis.liferay.model.MonthlySalarySoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MonthlySalary service. Represents a row in the &quot;pis_MonthlySalary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MonthlySalaryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MonthlySalaryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MonthlySalaryImpl
 * @generated
 */
@JSON(strict = true)
public class MonthlySalaryModelImpl
	extends BaseModelImpl<MonthlySalary> implements MonthlySalaryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a monthly salary model instance should use the <code>MonthlySalary</code> interface instead.
	 */
	public static final String TABLE_NAME = "pis_MonthlySalary";

	public static final Object[][] TABLE_COLUMNS = {
		{"monthlySalaryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"grossDeduction", Types.FLOAT},
		{"grossIncome", Types.FLOAT}, {"netPayble", Types.FLOAT},
		{"processMonth", Types.TIMESTAMP}, {"employeeId", Types.BIGINT},
		{"structureId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("monthlySalaryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("grossDeduction", Types.FLOAT);
		TABLE_COLUMNS_MAP.put("grossIncome", Types.FLOAT);
		TABLE_COLUMNS_MAP.put("netPayble", Types.FLOAT);
		TABLE_COLUMNS_MAP.put("processMonth", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("structureId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table pis_MonthlySalary (monthlySalaryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,grossDeduction DOUBLE,grossIncome DOUBLE,netPayble DOUBLE,processMonth DATE null,employeeId LONG,structureId LONG)";

	public static final String TABLE_SQL_DROP = "drop table pis_MonthlySalary";

	public static final String ORDER_BY_JPQL =
		" ORDER BY monthlySalary.monthlySalaryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY pis_MonthlySalary.monthlySalaryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long MONTHLYSALARYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MonthlySalary toModel(MonthlySalarySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MonthlySalary model = new MonthlySalaryImpl();

		model.setMonthlySalaryId(soapModel.getMonthlySalaryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setGrossDeduction(soapModel.getGrossDeduction());
		model.setGrossIncome(soapModel.getGrossIncome());
		model.setNetPayble(soapModel.getNetPayble());
		model.setProcessMonth(soapModel.getProcessMonth());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setStructureId(soapModel.getStructureId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MonthlySalary> toModels(MonthlySalarySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MonthlySalary> models = new ArrayList<MonthlySalary>(
			soapModels.length);

		for (MonthlySalarySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MonthlySalaryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _monthlySalaryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMonthlySalaryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _monthlySalaryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MonthlySalary.class;
	}

	@Override
	public String getModelClassName() {
		return MonthlySalary.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MonthlySalary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MonthlySalary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MonthlySalary, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MonthlySalary)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MonthlySalary, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MonthlySalary, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MonthlySalary)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MonthlySalary, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MonthlySalary, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, MonthlySalary>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			MonthlySalary.class.getClassLoader(), MonthlySalary.class,
			ModelWrapper.class);

		try {
			Constructor<MonthlySalary> constructor =
				(Constructor<MonthlySalary>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<MonthlySalary, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MonthlySalary, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MonthlySalary, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MonthlySalary, Object>>();
		Map<String, BiConsumer<MonthlySalary, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MonthlySalary, ?>>();

		attributeGetterFunctions.put(
			"monthlySalaryId", MonthlySalary::getMonthlySalaryId);
		attributeSetterBiConsumers.put(
			"monthlySalaryId",
			(BiConsumer<MonthlySalary, Long>)MonthlySalary::setMonthlySalaryId);
		attributeGetterFunctions.put("groupId", MonthlySalary::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<MonthlySalary, Long>)MonthlySalary::setGroupId);
		attributeGetterFunctions.put("companyId", MonthlySalary::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MonthlySalary, Long>)MonthlySalary::setCompanyId);
		attributeGetterFunctions.put("userId", MonthlySalary::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<MonthlySalary, Long>)MonthlySalary::setUserId);
		attributeGetterFunctions.put("userName", MonthlySalary::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MonthlySalary, String>)MonthlySalary::setUserName);
		attributeGetterFunctions.put(
			"createDate", MonthlySalary::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MonthlySalary, Date>)MonthlySalary::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MonthlySalary::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MonthlySalary, Date>)MonthlySalary::setModifiedDate);
		attributeGetterFunctions.put(
			"grossDeduction", MonthlySalary::getGrossDeduction);
		attributeSetterBiConsumers.put(
			"grossDeduction",
			(BiConsumer<MonthlySalary, Float>)MonthlySalary::setGrossDeduction);
		attributeGetterFunctions.put(
			"grossIncome", MonthlySalary::getGrossIncome);
		attributeSetterBiConsumers.put(
			"grossIncome",
			(BiConsumer<MonthlySalary, Float>)MonthlySalary::setGrossIncome);
		attributeGetterFunctions.put("netPayble", MonthlySalary::getNetPayble);
		attributeSetterBiConsumers.put(
			"netPayble",
			(BiConsumer<MonthlySalary, Float>)MonthlySalary::setNetPayble);
		attributeGetterFunctions.put(
			"processMonth", MonthlySalary::getProcessMonth);
		attributeSetterBiConsumers.put(
			"processMonth",
			(BiConsumer<MonthlySalary, Date>)MonthlySalary::setProcessMonth);
		attributeGetterFunctions.put(
			"employeeId", MonthlySalary::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId",
			(BiConsumer<MonthlySalary, Long>)MonthlySalary::setEmployeeId);
		attributeGetterFunctions.put(
			"structureId", MonthlySalary::getStructureId);
		attributeSetterBiConsumers.put(
			"structureId",
			(BiConsumer<MonthlySalary, Long>)MonthlySalary::setStructureId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMonthlySalaryId() {
		return _monthlySalaryId;
	}

	@Override
	public void setMonthlySalaryId(long monthlySalaryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_monthlySalaryId = monthlySalaryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public float getGrossDeduction() {
		return _grossDeduction;
	}

	@Override
	public void setGrossDeduction(float grossDeduction) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_grossDeduction = grossDeduction;
	}

	@JSON
	@Override
	public float getGrossIncome() {
		return _grossIncome;
	}

	@Override
	public void setGrossIncome(float grossIncome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_grossIncome = grossIncome;
	}

	@JSON
	@Override
	public float getNetPayble() {
		return _netPayble;
	}

	@Override
	public void setNetPayble(float netPayble) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_netPayble = netPayble;
	}

	@JSON
	@Override
	public Date getProcessMonth() {
		return _processMonth;
	}

	@Override
	public void setProcessMonth(Date processMonth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_processMonth = processMonth;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public long getStructureId() {
		return _structureId;
	}

	@Override
	public void setStructureId(long structureId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_structureId = structureId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MonthlySalary.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MonthlySalary toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MonthlySalary>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MonthlySalaryImpl monthlySalaryImpl = new MonthlySalaryImpl();

		monthlySalaryImpl.setMonthlySalaryId(getMonthlySalaryId());
		monthlySalaryImpl.setGroupId(getGroupId());
		monthlySalaryImpl.setCompanyId(getCompanyId());
		monthlySalaryImpl.setUserId(getUserId());
		monthlySalaryImpl.setUserName(getUserName());
		monthlySalaryImpl.setCreateDate(getCreateDate());
		monthlySalaryImpl.setModifiedDate(getModifiedDate());
		monthlySalaryImpl.setGrossDeduction(getGrossDeduction());
		monthlySalaryImpl.setGrossIncome(getGrossIncome());
		monthlySalaryImpl.setNetPayble(getNetPayble());
		monthlySalaryImpl.setProcessMonth(getProcessMonth());
		monthlySalaryImpl.setEmployeeId(getEmployeeId());
		monthlySalaryImpl.setStructureId(getStructureId());

		monthlySalaryImpl.resetOriginalValues();

		return monthlySalaryImpl;
	}

	@Override
	public int compareTo(MonthlySalary monthlySalary) {
		long primaryKey = monthlySalary.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MonthlySalary)) {
			return false;
		}

		MonthlySalary monthlySalary = (MonthlySalary)object;

		long primaryKey = monthlySalary.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MonthlySalary> toCacheModel() {
		MonthlySalaryCacheModel monthlySalaryCacheModel =
			new MonthlySalaryCacheModel();

		monthlySalaryCacheModel.monthlySalaryId = getMonthlySalaryId();

		monthlySalaryCacheModel.groupId = getGroupId();

		monthlySalaryCacheModel.companyId = getCompanyId();

		monthlySalaryCacheModel.userId = getUserId();

		monthlySalaryCacheModel.userName = getUserName();

		String userName = monthlySalaryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			monthlySalaryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			monthlySalaryCacheModel.createDate = createDate.getTime();
		}
		else {
			monthlySalaryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			monthlySalaryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			monthlySalaryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		monthlySalaryCacheModel.grossDeduction = getGrossDeduction();

		monthlySalaryCacheModel.grossIncome = getGrossIncome();

		monthlySalaryCacheModel.netPayble = getNetPayble();

		Date processMonth = getProcessMonth();

		if (processMonth != null) {
			monthlySalaryCacheModel.processMonth = processMonth.getTime();
		}
		else {
			monthlySalaryCacheModel.processMonth = Long.MIN_VALUE;
		}

		monthlySalaryCacheModel.employeeId = getEmployeeId();

		monthlySalaryCacheModel.structureId = getStructureId();

		return monthlySalaryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MonthlySalary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MonthlySalary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MonthlySalary, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((MonthlySalary)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MonthlySalary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MonthlySalary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MonthlySalary, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MonthlySalary)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MonthlySalary>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _monthlySalaryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private float _grossDeduction;
	private float _grossIncome;
	private float _netPayble;
	private Date _processMonth;
	private long _employeeId;
	private long _structureId;

	public <T> T getColumnValue(String columnName) {
		Function<MonthlySalary, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MonthlySalary)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("monthlySalaryId", _monthlySalaryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("grossDeduction", _grossDeduction);
		_columnOriginalValues.put("grossIncome", _grossIncome);
		_columnOriginalValues.put("netPayble", _netPayble);
		_columnOriginalValues.put("processMonth", _processMonth);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("structureId", _structureId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("monthlySalaryId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("grossDeduction", 128L);

		columnBitmasks.put("grossIncome", 256L);

		columnBitmasks.put("netPayble", 512L);

		columnBitmasks.put("processMonth", 1024L);

		columnBitmasks.put("employeeId", 2048L);

		columnBitmasks.put("structureId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MonthlySalary _escapedModel;

}