/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.ayudh.comnet.admin.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ApplicationAccess service. Represents a row in the &quot;comnet_ApplicationAccess&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>net.ayudh.comnet.admin.model.impl.ApplicationAccessModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>net.ayudh.comnet.admin.model.impl.ApplicationAccessImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationAccess
 * @generated
 */
@ProviderType
public interface ApplicationAccessModel
	extends BaseModel<ApplicationAccess>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application access model instance should use the {@link ApplicationAccess} interface instead.
	 */

	/**
	 * Returns the primary key of this application access.
	 *
	 * @return the primary key of this application access
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application access.
	 *
	 * @param primaryKey the primary key of this application access
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the application access ID of this application access.
	 *
	 * @return the application access ID of this application access
	 */
	public long getApplicationAccessId();

	/**
	 * Sets the application access ID of this application access.
	 *
	 * @param applicationAccessId the application access ID of this application access
	 */
	public void setApplicationAccessId(long applicationAccessId);

	/**
	 * Returns the group ID of this application access.
	 *
	 * @return the group ID of this application access
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this application access.
	 *
	 * @param groupId the group ID of this application access
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this application access.
	 *
	 * @return the company ID of this application access
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this application access.
	 *
	 * @param companyId the company ID of this application access
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this application access.
	 *
	 * @return the user ID of this application access
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this application access.
	 *
	 * @param userId the user ID of this application access
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this application access.
	 *
	 * @return the user uuid of this application access
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this application access.
	 *
	 * @param userUuid the user uuid of this application access
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this application access.
	 *
	 * @return the user name of this application access
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this application access.
	 *
	 * @param userName the user name of this application access
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this application access.
	 *
	 * @return the create date of this application access
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this application access.
	 *
	 * @param createDate the create date of this application access
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this application access.
	 *
	 * @return the modified date of this application access
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application access.
	 *
	 * @param modifiedDate the modified date of this application access
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee ID of this application access.
	 *
	 * @return the employee ID of this application access
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this application access.
	 *
	 * @param employeeId the employee ID of this application access
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the application ID of this application access.
	 *
	 * @return the application ID of this application access
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this application access.
	 *
	 * @param applicationId the application ID of this application access
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the status of this application access.
	 *
	 * @return the status of this application access
	 */
	public int getStatus();

	/**
	 * Sets the status of this application access.
	 *
	 * @param status the status of this application access
	 */
	public void setStatus(int status);

	/**
	 * Returns the deleted of this application access.
	 *
	 * @return the deleted of this application access
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this application access is deleted.
	 *
	 * @return <code>true</code> if this application access is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this application access is deleted.
	 *
	 * @param deleted the deleted of this application access
	 */
	public void setDeleted(boolean deleted);

}