/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adj.userportlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserPortlet service. Represents a row in the &quot;UP_UserPortlet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adj.userportlet.model.impl.UserPortletModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adj.userportlet.model.impl.UserPortletImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserPortlet
 * @generated
 */
@ProviderType
public interface UserPortletModel
	extends BaseModel<UserPortlet>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user portlet model instance should use the {@link UserPortlet} interface instead.
	 */

	/**
	 * Returns the primary key of this user portlet.
	 *
	 * @return the primary key of this user portlet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user portlet.
	 *
	 * @param primaryKey the primary key of this user portlet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user portlet.
	 *
	 * @return the uuid of this user portlet
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this user portlet.
	 *
	 * @param uuid the uuid of this user portlet
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this user portlet.
	 *
	 * @return the ID of this user portlet
	 */
	public long getId();

	/**
	 * Sets the ID of this user portlet.
	 *
	 * @param id the ID of this user portlet
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this user portlet.
	 *
	 * @return the group ID of this user portlet
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user portlet.
	 *
	 * @param groupId the group ID of this user portlet
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user portlet.
	 *
	 * @return the company ID of this user portlet
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user portlet.
	 *
	 * @param companyId the company ID of this user portlet
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user portlet.
	 *
	 * @return the user ID of this user portlet
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user portlet.
	 *
	 * @param userId the user ID of this user portlet
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user portlet.
	 *
	 * @return the user uuid of this user portlet
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user portlet.
	 *
	 * @param userUuid the user uuid of this user portlet
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user portlet.
	 *
	 * @return the user name of this user portlet
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user portlet.
	 *
	 * @param userName the user name of this user portlet
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user portlet.
	 *
	 * @return the create date of this user portlet
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user portlet.
	 *
	 * @param createDate the create date of this user portlet
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user portlet.
	 *
	 * @return the modified date of this user portlet
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user portlet.
	 *
	 * @param modifiedDate the modified date of this user portlet
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the portlet ID of this user portlet.
	 *
	 * @return the portlet ID of this user portlet
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this user portlet.
	 *
	 * @param portletId the portlet ID of this user portlet
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the thumbnail of this user portlet.
	 *
	 * @return the thumbnail of this user portlet
	 */
	@AutoEscape
	public String getThumbnail();

	/**
	 * Sets the thumbnail of this user portlet.
	 *
	 * @param thumbnail the thumbnail of this user portlet
	 */
	public void setThumbnail(String thumbnail);

	/**
	 * Returns the added of this user portlet.
	 *
	 * @return the added of this user portlet
	 */
	public boolean getAdded();

	/**
	 * Returns <code>true</code> if this user portlet is added.
	 *
	 * @return <code>true</code> if this user portlet is added; <code>false</code> otherwise
	 */
	public boolean isAdded();

	/**
	 * Sets whether this user portlet is added.
	 *
	 * @param added the added of this user portlet
	 */
	public void setAdded(boolean added);

}